### ISSUE TITLE
Sponsor images needed on logged out home page

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1006]
![sponsors](https://cloud.githubusercontent.com/assets/4432106/6925805/139d5d6a-d7b0-11e4-9ebd-5d00e25d1a7d.png)

**Comment by dboyer** [comment]
Sponsor logos sent via email.

**Comment by maurizi** [comment]
We still need some images, but we no longer show placeholder images

**Comment by jwalgran** [comment]
Removing "soft launch" because we are awaiting approvals.

**Comment by dboyer** [comment]
This likely will not happen until next sprint.

**Comment by dboyer** [comment]
Waiting on sponsor approval of the mockups but needs to happen by April 23.
