### ISSUE TITLE
No way to return to home page while in soft launch mode

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1013]
If the user clicks the about page in the side navigation or the login or register buttons, there's no way to get back to the home page other than clicking the back button in the browser.

**Comment by jwalgran** [comment]
#441 is a possible solution to this

**Comment by dboyer** [comment]
Agreed. @jfrankl what are your thoughts on the Trees Count text in the header linking to the home page?

**Comment by jfrankl** [comment]
+1 to TreesCount logo in header linking to homepage.

On Tue, Mar 31, 2015 at 8:19 PM, dboyer <notifications@github.com> wrote:

> Agreed. @jfrankl <https://github.com/jfrankl> what are your thoughts on
> the Trees Count text in the header linking to the home page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1013#issuecomment-88291877>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>
