### ISSUE TITLE
Change line breaks in text in hero image

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1014]
The current arrangement looks odd since "York City" ends on it's own line. Ideally, the lines would be

We're mapping
every street tree in
New York City.

In could also be on the third line, if that's better for alignment purposes.

**Comment by dboyer** [comment]
@designmatty This may be for you?

**Comment by RickMohr** [comment]
Could use `New&nbsp;York&nbsp;City`

**Comment by jwalgran** [comment]
nonbreaking space seems like a good idea. Because "every street tree" is in a different color, for emphasis, ``every&nbsp;street&nbsp;tree" would be good addition, too.
