### ISSUE TITLE
Set password button on confirm password reset page needs styling

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1018]
See below. This is at accounts/password/reset/confirm/

![screen shot 2015-03-31 at 9 01 23 pm](https://cloud.githubusercontent.com/assets/516764/6932565/3c54540a-d7e9-11e4-9ab5-385547863c6b.png)

**Comment by designmatty** [comment]
#1002 fixed all style issues with credential/login forms, including buttons.

**Comment by dboyer** [comment]
I'm still seeing this on staging on the release build being tested for launch.
