### ISSUE TITLE
Validation errors not tied to a specific field should not be styled with a "pointer"

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1023]
The error message in this screenshot is a "form level" error as opposed to a "field level" error. It may confuse a registrant to have the password error "pointing" to the username field.

![screen shot 2015-04-01 at 8 05 19 am](https://cloud.githubusercontent.com/assets/17363/6944013/653753a6-d846-11e4-9881-a743b8452539.png)

**Comment by designmatty** [comment]
Does this occur anywhere else or only in the register user?

**Comment by jwalgran** [comment]
Anywhere there is a ``form.non_field_errors`` in an HTML template, there is a possibility of showing a form-level error message. Practically, we may not have form-level validations for all the pages in the list below.

```
./nyc_trees/apps/core/templates/core/partials/email_form.html:4:        {{ form.non_field_errors }}
./nyc_trees/apps/event/templates/event/partials/event_form.html:5:        {{ form.non_field_errors }}
./nyc_trees/apps/login/templates/login/forgot_username.html:17:        {{ form.non_field_errors }}
./nyc_trees/apps/users/templates/groups/settings.html:49:                        {{ form.non_field_errors }}
./nyc_trees/templates/registration/activation_complete.html:15:    {{ form.non_field_errors }}
./nyc_trees/templates/registration/login.html:17:    {{ form.non_field_errors }}
./nyc_trees/templates/registration/password_change_form.html:11:    {{ form.non_field_errors }}
./nyc_trees/templates/registration/password_reset_confirm.html:11:    {{ form.non_field_errors }}
./nyc_trees/templates/registration/password_reset_form.html:13:    {{ form.non_field_errors }}
./nyc_trees/templates/registration/registration_form.html:11:    {{ form.non_field_errors }}

**Comment by designmatty** [comment]
Is there a means of adding a unique class to non_field_errors?

**Comment by designmatty** [comment]
I could go through and add a wrapping `<div class="foo"></div>` around each `form.non_field_errors` but I feel this isn't the best way to tackle the issue.

**Comment by jwalgran** [comment]
We just added a dependency on https://github.com/kmike/django-widget-tweaks so we could easily attach classes to form elements, but I just tried it and it does not work with the non-field error list.

This SO answer has a suggestion, which amounts to wrapping: http://stackoverflow.com/a/16215790

```python
{% if form.non_field_errors %}
  <div class="non-field-errors">
    {% for err in form.non_field_errors %}
      <p class="form-error">{{ err }}</p>
    {% endfor %}
  </div>
{% endif %}
```

We could put this in a partial and include it in our forms, so we only do the wrapping in one physical location.

**Comment by jwalgran** [comment]
We have decided to go with a partial. Matt W can help with styling.
