### ISSUE TITLE
"Your events this week" list not showing RSVPd events in the near future

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1027]
![screen shot 2015-04-01 at 10 21 27 am](https://cloud.githubusercontent.com/assets/17363/6947147/1d6a7292-d85a-11e4-927e-e66c5d4d74b7.png)

![screen shot 2015-04-01 at 10 21 51 am](https://cloud.githubusercontent.com/assets/17363/6947153/2100ead0-d85a-11e4-96e8-658528a6cf34.png)

**Comment by kdeloach** [comment]
I was able to reproduce this bug by RSVPing to an event (with a date in the near future) which belongs to a group that I am *not* following. It seems reasonable that this list should include events regardless of group follows.

**Comment by dboyer** [comment]
Yes, the list should include all events for which you've RSVPd, not just those by groups you follow.

**Comment by kdeloach** [comment]
I agree. Just for future reference, I'd like to clarify what this section displays.

This used to display all upcoming events for all groups that you are following. This will now only display events that you have explicitly RSVPd to.
