### ISSUE TITLE
No page title

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1028]
We should add a `<title>` element and a favicon.

**Comment by dboyer** [comment]
@jfrankl Related to #502

**Comment by maurizi** [comment]
https://github.com/azavea/nyc-trees/pull/1071 added favicons, but we still need a `<title>` element

**Comment by kdeloach** [comment]
We will just use the same title for all pages.  @dboyer, do we have something to use for a title?

**Comment by dboyer** [comment]
Let's use TreesCount! 2015

Take out the exclamation point if special characters can't be used.

**Comment by kdeloach** [comment]
Fixed by #1138.
