### ISSUE TITLE
Parks logos cut off

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1030]
This is on production.

In the header, the circle appears cut off slightly along the bottom and right side.

In the center of the page, the NYC Parks text is cut off along the bottom. 

![parks-logo-small](https://cloud.githubusercontent.com/assets/516764/6949806/93b18830-d884-11e4-83b7-8d5ea22e45e2.png)

**Comment by dboyer** [comment]
The NYC Parks text under their logo is cut off on the home page and in the footer. This is on both production and staging. 
![parkslogo](https://cloud.githubusercontent.com/assets/516764/7233208/0010faf6-e74e-11e4-91c9-db6c6e6df263.png)

**Comment by RickMohr** [comment]
That's in the actual image file, I think we need a better one from them:

![logo-nycparks](https://cloud.githubusercontent.com/assets/2162993/7233403/17859a06-e74f-11e4-8e8d-2be327d5fba4.png)

**Comment by dboyer** [comment]
@designmatty are any of the logos in design\NYC Parks Logo what we need? Otherwise, I'll try to get a new one.

**Comment by designmatty** [comment]
Yeah I have the files needed to fix this. I'll get the updated image up today.

**Comment by RickMohr** [comment]
+1
