### ISSUE TITLE
Individual mapper status 'Learn More' link needs an href

### ISSUE THREAD

**Issue by designmatty** [azavea/nyc-trees#1039]
Currently the link goes no where. 

![screen shot 2015-04-02 at 9 41 13 am](https://cloud.githubusercontent.com/assets/1928955/6965050/97e32ae2-d91c-11e4-83cb-fce34951c9d2.png)

**Comment by dboyer** [comment]
I'm waiting on text from Parks, but we need to add this in this sprint. Perhaps it can go under #1431

**Comment by maurizi** [comment]
@dboyer Any update?

**Comment by dboyer** [comment]
Get rid of the "learn more" link and change the text under the Mapper Status heading to say:

Congratulations! As an independent mapper, you can reserve available block edges, borrow equipment from a lending hub, and map on your own. Click on “Reservations” to get started!

**Comment by designmatty** [comment]
I'll get this in today. Thanks
