### ISSUE TITLE
Change reservations page URL to /blockedge

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1042]
The proper terminology is block edge rather than block face so we need to change the URL.

**Comment by RickMohr** [comment]
"blockface" appears in these page URLs:

/blockface/progress/
/blockface/
/blockface/reserve/
/blockface/reservations-instructions/
/blockface/checkout/
/blockface/checkout-confirmation/

Change them all?

**Comment by dboyer** [comment]
Yep, change them all. Parks is using blockedge as the terminology in the training material and other content and we need to be consistent with that wording.

**Comment by maurizi** [comment]
@dboyer should this be `/blockside/` now, instead of `/blockedge/`?

**Comment by maurizi** [comment]
@dboyer Nevermind, I'm misremembering things.

**Comment by dboyer** [comment]
No problem. Yes, it should always be blockedge
