### ISSUE TITLE
Adding non-breaking spaces to the header text causes uneven box borders

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1047]
![screen shot 2015-04-02 at 10 23 11 am](https://cloud.githubusercontent.com/assets/17363/6969289/4952f92e-d922-11e4-91f4-c98b4dba4076.png)

![screen shot 2015-04-02 at 10 23 00 am](https://cloud.githubusercontent.com/assets/17363/6969290/4954341a-d922-11e4-8b20-0f937a5f1b28.png)

**Comment by jfrankl** [comment]
I think this is fixed in #1054. Could you please confirm?

**Comment by jwalgran** [comment]
The really skinny right border is resolved. Larger phones still have have a lot of white space in the right border. Go ahead and close this if that is just the expected tradeoff for not breaking the words up.

![screen shot 2015-04-03 at 11 44 32 am](https://cloud.githubusercontent.com/assets/17363/6986926/f03de5a8-d9f6-11e4-8ad0-164b7ff118e5.png)

**Comment by jfrankl** [comment]
@designmatty Can you take a look and see if there is a reasonable fix?

**Comment by designmatty** [comment]
@jfrankl One thing that comes to mind – when on mobile we could center that hero text. It would match the centered text of the button and the header midway down the page. Thoughts?

![screen shot 2015-04-06 at 12 02 45 pm](https://cloud.githubusercontent.com/assets/1928955/7007152/0f8b7a28-dc55-11e4-83b5-74c09a7050e9.png)

**Comment by jfrankl** [comment]
@designmatty That looks good. Let's move forward in that direction.
