### ISSUE TITLE
Add text for email users receive when reservations expiring soon

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1052]
Subject: Your block edge reservations are expiring soon

From: noreply@treescount.nycgovparks.org
To: helpful@mapper.com

 The following block edge reservations are expiring on [DATE]:

-	Block edge ID
-	Block edge ID

Visit https://treescount.nycgovparks.org/blockedge to begin mapping your reserved block edges 

If you need to cancel your block edge reservations you can do so by following [LINK]

**Comment by kdeloach** [comment]
The URL to cancel & reserve blockfaces is the same. Should we repeat the URL for "If you need to cancel..." or just omit this last sentence?

**Comment by dboyer** [comment]
Combine the last two sentences to read: Visit https://treescount.nycgovparks.org/blockedge to begin mapping your reserved block edges or cancel a block edge reservation.

**Comment by kdeloach** [comment]
Thanks.
