### ISSUE TITLE
Add text for email users receive after reserving block edges if mapping via app

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1053]
Subject: Your block edge reservations are confirmed
From: noreply@treescount.nycgovparks.org
To: helpful@mapper.com

Thank you for signing up to map on your own during TreesCount! 2015.  The following block edges have been confirmed:

-	Block edge ID
-	Block edges ID

The block edges will be reserved for you to map until [DATE].   

You can view and change your other block edge reservations at http://treescount.nycgovparks.org/blockedge

**Comment by RickMohr** [comment]
+1 I made some new reservations and saw the email in the celery log with only the new IDs.
