### ISSUE TITLE
Create achievement definitions and write a function to check and assign them to users

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1058]
Badge Name | Task
-------|-----
In Pursuit of Mappiness | Followed 5 Groups
Ready, Set, Roll | Finished Online Training
Certified Mapper | Attended a Training Event
Free Mapper | Attended a Mapping Event
Mapped 50 Block Segments | Mapped 50 Block Segments
Mapped 100 Block Segments | Mapped 100 Block Segments
Mapped 200 Block Segments | Mapped 200 Block Segments
Mapped 400 Block Segments | Mapped 400 Block Segments
Mapped 1000 Block Segments | Mapped 1000 Block Segments

**Comment by RickMohr** [comment]
@dboyer, @jfrankl, from the achievement code I see the idea of showing how much progress a user has made toward a particular achievement. But I don't think we have planned to show that in the UI, which would simplify the implementation of these achievements. Are we in fact omitting this "progress" concept, or should I write code for it?

**Comment by jfrankl** [comment]
@dboyer I had suggested a while back that Parks/we come up with special titles for the Mapped XX Blocks achievements. So, "Mapped 50 Blocks" could be "Mega Mapper" (that's just off the top of my head).

Right now I think it's odd for some of the achievements to have special titles and for some to not; it's going to make displaying them unnecessarily confusing/awkward. Can we either do all one or the other?

**Comment by dboyer** [comment]
@RickMohr I don't think we need to include the concept of progress toward an achievement. The wireframes include an "In Progress" achievement section but that can just refer to whatever is the next achievement related to # of blocks mapped. I don't think we need to track something like "25% of the way toward Mapping 50 Blocks, etc" @jfrankl You agree?

**Comment by jfrankl** [comment]
Agreed. Let's keep it simple. The goal is to helpfully guide the user
towards the next achievement, but I don't think it needs to show progress
on individual achievements—just the next one (Rick and I discussed how they
are fairly linear).

On Mon, Apr 13, 2015 at 12:24 PM, dboyer <notifications@github.com> wrote:

> @RickMohr <https://github.com/RickMohr> I don't think we need to include
> the concept of progress toward an achievement. The wireframes include an
> "In Progress" achievement section but that can just refer to whatever is
> the next achievement related to # of blocks mapped. I don't think we need
> to track something like "25% of the way toward Mapping 50 Blocks, etc"
> @jfrankl <https://github.com/jfrankl> You agree?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1058#issuecomment-92416560>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
@jfrankl I'll try again to get an answer on the names for the other achievements. My vote is to always display a special title since they did choose titles for some of them. I'll try to get the other names from Parks.
