### ISSUE TITLE
Styling for tabbed progress circles

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#1063]
The latest version of wireframes shows a tabbed interface for the progress bars, allowing the user to switch between "All Time", "This Week" (the past 7 days), and "My Trees" (the individual's progress).

![image](https://cloud.githubusercontent.com/assets/1809908/6986295/e63d5ab2-da09-11e4-8bc6-eb4d3102c1c3.png)

![image](https://cloud.githubusercontent.com/assets/1809908/6986292/dfdcc5c2-da09-11e4-9f9c-8a4ac05d31ce.png)

![image](https://cloud.githubusercontent.com/assets/1809908/6986289/d9e6034a-da09-11e4-874f-07ad4dca71bb.png)

**Comment by maurizi** [comment]
@RickMohr This was fixed by  #1060 correct?

**Comment by jfrankl** [comment]
Yep! Rick, you're awesome.

**Comment by RickMohr** [comment]
Thanks! It all works but needs some styling help, so I am reopening this.

**Comment by jfrankl** [comment]
Fixed by #1119.
