### ISSUE TITLE
Incorrect pluralization for "Territories" on admin site

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1065]
![image](https://cloud.githubusercontent.com/assets/43062/6989426/2a03abba-da29-11e4-8f05-e902554b9d49.png)

**Comment by maurizi** [comment]
Also incorrect: `Speciess`

**Comment by steventlamb** [comment]
https://docs.djangoproject.com/en/1.7/ref/models/options/#verbose-name-plural
