### ISSUE TITLE
Users still required to follow groups to complete training

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1084]
I went through training and ended on the /training/pure/groups_to_follow/ page. I can't follow groups anymore since we removed that button. I can finish this step in training by selecting skip or continue, but following groups shouldn't be tied to finishing training.

**Comment by steventlamb** [comment]
@dboyer: @jwalgran, is the plan to totally remove 'groups to follow' from the app?

**Comment by dboyer** [comment]
No, I think we should still show the groups page at the end of training so that users know they have the option to follow groups. It just shouldn't be mandatory to either click Skip or Continue on that page before you're considered as completing training.

Let's change the text in the last sentence on this page to say - "Visit a group's info page and follow them to get information and RSVP to an event occurring near you.

**Comment by steventlamb** [comment]
I'm a little confused and think users may be by this as well. If I understand your proposed change correctly, this will happen:
* a user finished the intro quiz and a redirect will happen.
* at this moment, training is over. the user has completed training.
* the redirect takes them to the groups page, with the added text in your comment.
* the user can click a group, or click the nav bar, or whatever. they linear workflow is over.
* the user never receives confirmation that training is over

**Comment by dboyer** [comment]
I agree it's confusing since people may never reach the training complete page if they click on a group name or elsewhere on the groups to follow page. Perhaps after completing the quiz, we take them to the Training Complete page but keep the groups to follow option at the bottom of the list with a Start button there indicating they still have the option to follow groups. We could also change the text on the top of that page to say:

Visit the dashboard to explore TreesCount! 2015 and start mapping! You can also visit the Groups page to learn more about mapping opportunities and follow groups for event information.
