### ISSUE TITLE
Clicking okay in the copy event URL does not actually copy the URL

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1088]
1. Click the Copy button in the Share Link section on an event detail page
2. Click OK in the pop-up box
3. Try to paste into another tab
4. Nothing happens

**Comment by RickMohr** [comment]
@dboyer, you have to actually copy the text (hit Ctrl-C), like it tells you to do.

**Comment by dboyer** [comment]
Parks reported confusion with this too as they also thought clicking OK meant the text was copied. If we need to keep the current functionality, let's 

1. Change the text to say: Please manually copy the selected text.
2. Only have one button that says Close since OK and Cancel essentially do the same thing.

**Comment by kdeloach** [comment]
We can do (1) but not (2).

Do we want to invest more time into creating a more comprehensive solution?

**Comment by dboyer** [comment]
Let's do just 1 for now. We have other things more important to spend time on.
