### ISSUE TITLE
Need styling on the copy link option

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1089]
Click the copy button on an event detail page. The pop-up box isn't styled.

**Comment by designmatty** [comment]
@dboyer The pop up which shows the copy link is a native alert box. Browsers don't allow you to apply style changes to alert boxes. 

We would have to get a developer to use a bootstrap modal instead of an alert box if we wanted to change the look.

**Comment by dboyer** [comment]
Let's not worry about it right now. I'll close this.
