### ISSUE TITLE
Need styling on the time field when adding or editing an event

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1090]
The time fields are misaligned.

**Comment by designmatty** [comment]
What do you think of doing this @dboyer ? ![screen shot 2015-04-09 at 3 28 15 pm](https://cloud.githubusercontent.com/assets/1928955/7075050/1c0fe57a-decd-11e4-9357-e8d664ccc685.png)

**Comment by jfrankl** [comment]
@designmatty Looks good to me.

**Comment by dboyer** [comment]
Looks good to me too.
