### ISSUE TITLE
Add event icons on all events

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#1095]
Right now the events page shows certain icons for location/type/etc but these are not displayed on other pages.

![image](https://cloud.githubusercontent.com/assets/1809908/7073004/6c37d53a-debe-11e4-916c-a91a84456f44.png)

![image](https://cloud.githubusercontent.com/assets/1809908/7072999/643c99f6-debe-11e4-8416-b095c8757099.png)

**Comment by steventlamb** [comment]
Icons still missing on the events tab of the group admin page. Good otherwise.
![screenshot from 2015-04-10 16 31 00](https://cloud.githubusercontent.com/assets/1699455/7096878/0a82eb4a-df9f-11e4-94d2-ae8b7f89f7e5.png)
