### ISSUE TITLE
Edit events page should use standard map template

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#1096]
![image](https://cloud.githubusercontent.com/assets/1809908/7073311/8b7f89c2-dec0-11e4-8782-bf84e0281fd2.png)

**Comment by jfrankl** [comment]
Because of the way this page is structured, it will take a considerable amount of time to make this work.

I think the current version is serviceable, especially considering how few people we expect to use it on mobile. I am going to leave this open for now in case we have extra time at the end, but I am considering this a low priority enhancement.

**Comment by dboyer** [comment]
I agree that this isn't necessary.
