### ISSUE TITLE
How should we handle block segment expiration reminder emails

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#11]
A few things to consider:

* A single, unified method of sending email may preferable to different methods for different app features (account confirmation vs. event registration details vs. block segment expiration)
* Reservations can be extended, so we can't just schedule an email to be sent in future and forget about it.

**Comment by jwalgran** [comment]
We have decided on a cron job that runs a management task which reads and modifies additional tracking fields on the reservation model, then queues email sending celery tasks as needed.

**Comment by RickMohr** [comment]
@jwalgran, what's the advantage of using celery tasks rather than sending the e-mails directly from the management task?

**Comment by jwalgran** [comment]
That was just what we wrote into #850. We may choose to send them directly.

**Comment by hectcastro** [comment]
The idea behind queueing each e-mail message in Celery is that when sending failures occur, retrying that e-mail can be done without getting in the way of other messages being sent.
