### ISSUE TITLE
Map colors!

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#1106]
They need some final adjustments.

**Comment by dboyer** [comment]
@jfrankl The more I look at the progress map, the more I think the gray for unmapped blends in too much with the gray of the water and is not visually different from the surrounding non-NYC areas (New Jersey, Long Island, etc). Especially on desktop where there's more map visible, it's really challenging to immediately see the blocks that are unmapped. Could we try a color that is more easily seen in comparison with the grays in the base map?

**Comment by jfrankl** [comment]
@dboyer, are any of these in the right direction?

Dark brown:

![image](https://cloud.githubusercontent.com/assets/1809908/7223820/8893d6b2-e6f6-11e4-8451-ce9b38f63b1a.png)

![image](https://cloud.githubusercontent.com/assets/1809908/7223839/0cfed6c2-e6f7-11e4-986a-0e908232798e.png)

Bright blue:

![image](https://cloud.githubusercontent.com/assets/1809908/7223857/6924f238-e6f7-11e4-867a-c4c77643c8ae.png)

![image](https://cloud.githubusercontent.com/assets/1809908/7223861/721c1722-e6f7-11e4-86c3-0378995ccf78.png)

Gray blue:

![image](https://cloud.githubusercontent.com/assets/1809908/7223885/1aca96d2-e6f8-11e4-97be-6649ad1e81d2.png)

![image](https://cloud.githubusercontent.com/assets/1809908/7223890/2b68d3d2-e6f8-11e4-85b8-e1dc6028ef7b.png)

**Comment by RickMohr** [comment]
I think the Brown shows well.

**Comment by dboyer** [comment]
I also like the brown and it's somewhat tree-ish in color. If it's a hassle to keep changing colors, I can first send a screenshot to Parks for review.

**Comment by jfrankl** [comment]
@dboyer could you please send that screen shot to parks? Let me know if you
need anything else from me, and please let me know if they want to change
it.

On Mon, Apr 20, 2015 at 10:27 AM, dboyer <notifications@github.com> wrote:

> I also like the brown and it's somewhat tree-ish in color. If it's a
> hassle to keep changing colors, I can first send a screenshot to Parks for
> review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1106#issuecomment-94467313>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
@jfrankl Parks has approved the dark brown. You can swap that in.
