### ISSUE TITLE
Complete implementation of training materials and images

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1110]

**Comment by dboyer** [comment]
This is a placeholder to provide support to the design team and me on the training materials. I've implemented most of the text and images. We're waiting on a few decisions from Parks, but I need developer assistance on a couple things. Feel free to move these to new issues if that's preferable.

1. Clicking Next loads the next training page in the middle or bottom of the page, not the top 

2. Images need to be added to the Explore Your Knowledge quiz. 

- In Question 2, add   <img src="/static/img/training/Stagger-Offset/stagger-offset.png"/> after "Select all that apply."
- In Question 4, add  <img src="/static/img/training/Stump/stump.png"/> after "What is the diameter of a tree stump?"
- In Question 8, add  <img src="/static/img/training/Poor-health-one/poor-health-one.png"/> before "one reason we can tell this tree is in poor health is:" 

3. Questions 8-10 weren't added to Explore Your Knowledge. Perhaps check with @steventlamb on this? They're in the document on the fileshare at \data\Training_Materials

**Comment by dboyer** [comment]
An example related to number 1:

I'm in Firefox. I read the Tree Species page under the Tree Data section. I clicked Next. The "Perceptions of Tree Health" page loaded but not at the top of the page where I could see 5. Perceptions of Tree Health. Instead, the page loaded scrolled down to about halfway down the page. I'm guessing it's keeping the same scroll position from the previous page.

**Comment by steventlamb** [comment]
(1) moved to #1194

**Comment by steventlamb** [comment]
I was able to verify this bug in chrome. It only turns up if you have two long training subpages back-to-back, such that you scroll to the bottom of one, hit next, and the following one is large enough that the top is cut off because the whole thing doesn't fit on the page.
