### ISSUE TITLE
Hitting "Back" button from checkout page loses selected block edges

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1111]
1) Go to "Reservations" page and reserve some blocks into "cart"
2) Hit "Finish Reservations"
3) Hit browser "Back" button -- "Cart" of reserved blocks is empty

Most users won't hit "Back", but those who do will be annoyed. However, if they then hit the forward button they can still check out their original blocks.

@dboyer, does this seem important to fix?

**Comment by dboyer** [comment]
Let's not worry about it for now.
