### ISSUE TITLE
"Tool tip" help for reservations page

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1112]
(Loose end from reservations page revamp)

**Comment by kdeloach** [comment]
@dboyer While discussing this issue, the question was raised: Do we still want to do this? Considering that the 2 new tooltips do not say much more that what is already displayed on the buttons.

![image](https://cloud.githubusercontent.com/assets/43062/7435625/27cfbbf4-f013-11e4-98e6-84b467d57b4f.png)

![image](https://cloud.githubusercontent.com/assets/43062/7435629/35e30fde-f013-11e4-853e-b4429bb61f8f.png)

**Comment by kdeloach** [comment]
CC @jfrankl See my comment above.

**Comment by dboyer** [comment]
I don't think they're necessary anymore but will defer to @jfrankl

**Comment by jfrankl** [comment]
I'm fine with dropping them.

On Mon, May 4, 2015 at 10:30 AM, dboyer <notifications@github.com> wrote:

> I don't think they're necessary anymore but will defer to @jfrankl
> <https://github.com/jfrankl>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1112#issuecomment-98726970>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>
