### ISSUE TITLE
Allow census admins to download a data dump zip file

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1115]

**Comment by kdeloach** [comment]
We also need to add the date in the name of the zip file.

**Comment by kdeloach** [comment]
We also need to add the date in the name of the zip file.

**Comment by kdeloach** [comment]
Can Parks directly download this file directly from S3 using their AWS credentials?

**Comment by RickMohr** [comment]
@dboyer, can you please ask Parks to choose one of the following options for getting data dumps:

1. Directly from S3 using their AWS credentials. They could script a download and/or use the AWS GUI.

2. Via a script-friendly endpoint we create for them.

3. Via a human-friendly page we create for them.

Easiest for us is #1 because we don't have to do anything at all.

**Comment by dboyer** [comment]
Just a note for everyone that I've been communicating with Parks on this and they have tentatively agreed to 1. Just need to check on a couple things with AWS credentials.

**Comment by dboyer** [comment]
Parks has confirmed that they will have access to the AWS console to download the data. We can proceed with that plan for providing them information.

**Comment by hectcastro** [comment]
Based on the bucket naming strategy on staging, the buckets with data on production would be:

- `django-storages-private-vpc-8cc796e9`
- `django-storages-vpc-8cc796e9`

They're not there yet though – I think they're lazily created on-demand by the application.

**Comment by jwalgran** [comment]
I just ran ``dump_db`` on prod, and it did produce data, but it also produced errors ([logged in Kibana](http://monitoring.treescount.nycgovparks.org:5601/#/discover?_g=(time:(from:'2015-04-23T21:20:14.176Z',mode:absolute,to:'2015-04-23T22:20:14.176Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:ERROR%5C%2FWorker)),sort:!('@timestamp',desc))))

The zip operation did not run because there were task failures earlier in the chord

```
<Error><Code>OperationAborted</Code><Message>A conflicting conditional operation is currently in progress against this resource. Please try again.</Message><RequestId>7D5E2482AEA9B042</RequestId><HostId>i0Wnmo8+ny39rA9iq44YPDzBwKw0xClaaUZHCiM6ISyTE/xy8dlp71iy6YESxtJ/w5eZSVcRB6w=</HostId></Error>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/census_admin/tasks.py", line 220, in dump_model
    destination_path = _storage.save(file_name, f)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 51, in save
    name = self._save(name, content)
  File "/usr/local/lib/python2.7/dist-packages/storages/backends/s3boto.py", line 409, in _save
    key = self.bucket.get_key(encoded_name)
  File "/usr/local/lib/python2.7/dist-packages/storages/backends/s3boto.py", line 295, in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/storages/backends/s3boto.py", line 333, in _get_or_create_bucket
    bucket.set_acl(self.bucket_acl)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 943, in set_acl
    headers, version_id)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 907, in set_canned_acl
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 409 Conflict

**Comment by jwalgran** [comment]
I ran this job again manually (it is not yet running automatically. see #1456) and it completed successfully. I suspect that, although the job is set up to create the bucket if it does not exist, the existence check is not thread/s3 safe. Now that the bucket has been created, this should not be an issue. I was able to trigger a successful dump task.

**Comment by jwalgran** [comment]
We are now producing a zip on S3 in production and Parks is ok with downloading dumps via the s3 console.
