### ISSUE TITLE
Enhance health check endpoint for tiler

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1129]
Currently the tiler health check targets `/`. This doesn't really exercise the tiler application much and doesn't give us a good representation of the service's health.

**Comment by kdeloach** [comment]
Any suggestions for metrics to add to the tiler health check endpoint?

**Comment by hectcastro** [comment]
Main objective here was to find something better than `/` to use for the health check. If Windshaft can't talk to Redis or PostgreSQL, hitting `/` still returns a 200 with useless text. Windshaft exposes a `/version` endpoint too, but that behaves the same way.

There may be something [around here](https://github.com/CartoDB/Windshaft/blob/0.19.4/lib/windshaft/server.js#L389) that we can reuse. All I really care about is knowing when the tiler can't render tiles.

**Comment by jwalgran** [comment]
Yup, I am attaching a route that just opens test connections to both postgres and redis, using the client libraries that are already installed under windshaft.

**Comment by jwalgran** [comment]
On staging the postgres connection is failing.

```javascript
{
  "cache": {
    "ok": true
  },
  "database": {
    "error": {
      "name": "error",
      "length": 86,
      "severity": "FATAL",
      "code": "3D000",
      "file": "postinit.c",
      "line": "775",
      "routine": "InitPostgres"
    }
  }
}

**Comment by jwalgran** [comment]
Assigned to hectcastro while he is investigating the failure

**Comment by jwalgran** [comment]
The staging load balancer it showing ``”ok”: true`` for the database.
