### ISSUE TITLE
Training navigation buttons on tablet size layout touch the bottom of the page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1137]
Training page tablet layout

![screen shot 2015-04-13 at 9 19 23 am](https://cloud.githubusercontent.com/assets/17363/7119937/74f96e1a-e1be-11e4-98d6-57ba65900469.png)

The mobile and desktop layouts have padding or a footer below the buttons

![screen shot 2015-04-13 at 9 19 48 am](https://cloud.githubusercontent.com/assets/17363/7120110/89e231d0-e1bf-11e4-902f-5191f4661dab.png)

![screen shot 2015-04-13 at 9 20 05 am](https://cloud.githubusercontent.com/assets/17363/7120111/8ba84612-e1bf-11e4-835c-78964a0330e5.png)

**Comment by jfrankl** [comment]
Nice call. I think this will be fixed by #1149.
