### ISSUE TITLE
HTTP exceptions are being masked by AttributeError

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1144]
Under certain conditions, views return HTTP errors with useful messages for logging/troubleshooting purposes. If the `update_with` decorator is used on a route that returns an HTTP error (non-dict response), it raises an AttributeError, which masks the exception that we would like to capture.

The simplest way to reproduce this bug is to try and view the survey page of an event that is *not* in-progress. Note: If you are not RSVPd to the event, you will get a different, but related, error message.

![image](https://cloud.githubusercontent.com/assets/43062/7122948/c44a4916-e1ec-11e4-9fa6-8039002bb0e5.png)

**Comment by steventlamb** [comment]
@kdeloach fixed by https://github.com/azavea/nyc-trees/commit/aed573da2bfe261e564af20b03101af7326cb161 ?

**Comment by kdeloach** [comment]
Yup. Closing.
