### ISSUE TITLE
Event emails need an "Unsubscribe" link

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#115]
Per Jeff, emails to users about events should have an "Unsubscribe to emails about this event" link. If the user clicks it they should be opted out of emails for that event and taken to their profile settings page "Emails" tab, which should display the "you have unsubscribed" message shown in the wireframes.

**Comment by kdeloach** [comment]
Seems like a nice-to-have. Won't have lots of email for an event, and you can unsubscribe on the profile page.

Simple solution -- link to profile page section.

**Comment by hectcastro** [comment]
If Amazon starts logging complaints in SES, then the need for this becomes more pressing.

**Comment by kdeloach** [comment]
@dboyer Wonder if I could get your opinion on this issue.

> If the user clicks it they should be opted out of emails for that event and taken to their profile settings page...

We can easily create a link that unsubscribes a user from event emails, however, it will require more effort to automatically login a user and redirect them to the user settings page. There is also a security risk involved if we create a URL that can automatically login as anybody.

The alternative I'd like to propose is that when a user clicks the unsubscribe link, we display a static page that says something like "You have been unsubscribed from event XYZ...". What do you think?

**Comment by jwalgran** [comment]
I was thinking we could deal with just a static link to /user/settings/#emails-pane

**Comment by kdeloach** [comment]
That would certainly be the easiest solution. I already have this feature like 99% working if that makes any difference (https://github.com/kdeloach/nyc-trees/commit/f46bb93e676e8a10e6c712f7368ff83b082ecb33).

**Comment by dboyer** [comment]
Getting to this late, but I don't feel strongly about either approach. A general unsubscribe with no link to profile settings is fine as is the route Justin proposed.

**Comment by hectcastro** [comment]
Confirmed on release stack.
