### ISSUE TITLE
Measure impact of Windshaft metatile setting

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1151]
## Measurement environment details

- Local development setup
- Loaded all blockfaces
- Recorded requests inbound to tiler from the default progress view with [gor](https://github.com/buger/gor)
- Replayed recorded requests with different `metatile` settings of `1`, `4`, `8`, `16`, `32`
- Restarted tile server after each configuration change

![metatile](https://cloud.githubusercontent.com/assets/43639/7124542/e6dc3f1a-e1f7-11e4-82d6-2e9658aa9fdd.png)

**Note**: `32` has no data because setting `metatile` to `32` causes the tiler to crash running out of memory.

Also worth noting that the `N.grid.json` queries always seem to take significantly longer than `N.png`. I assume this is expected, but with `metatile=1` each individual `N.grid.json` request takes between 10-30 seconds.

**Comment by RickMohr** [comment]
What are the x and y axes in this graph?

**Comment by hectcastro** [comment]
Y is milliseconds, and X is time. The entire set of recorded requests was run twice fore ach `metatile` setting.

**Comment by hectcastro** [comment]
Similar tests using recorded requests of the default progress page, but this time against two tilers behind a load balancer:

![metatile ELB](https://cloud.githubusercontent.com/assets/43639/7129710/dda39c1a-e231-11e4-8429-82636813dd6e.png)

**Comment by jwalgran** [comment]
Thanks for graphing these. I just merged #1132, which significantly speeds up the queries behind the tiles. I am interested to see what effect this has on the overall, multiple-tile request timing.

I tried setting ``useProfiler: true`` in my Windshaft config and hitting the tiler, but my Graphite dashboard does not have a ``statsite.timers.windshaft`` folder. Is there additional setup required to capture tile timings?

**Comment by hectcastro** [comment]
I'd try refreshing the UI or ensuring that `statsite` is running on the `services` virtual machine. It may also be possible that you haven't restarted the tiler process for the profiler setting to take effect.

**Comment by hectcastro** [comment]
Things appear to be significantly faster (using the same series of requests as above) after #1132:

![localhost](https://cloud.githubusercontent.com/assets/43639/7165616/af43b95e-e376-11e4-89a7-8f497940590c.png)

I'm comfortable closing this issue without any further changes.

**Comment by jwalgran** [comment]
Interesting that this now shows 8 slightly worse than 4, where the previous graph showed 8 as almost 2x faster. Measuring is awesome.

We could get another boost from including the tile bounds in our where clauses https://github.com/azavea/nyc-trees/issues/1128#issuecomment-92351809

**Comment by hectcastro** [comment]
Created an issue with a clearer title for that and CC'd everyone here.
