### ISSUE TITLE
Logged-in home: All reserved blocks listed

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1169]
Until fairly recently most of your reserved blocks were hidden behind a "More +" link. Now they all show up:

![image](https://cloud.githubusercontent.com/assets/2162993/7145104/c7b001ec-e2b7-11e4-9913-11f8f065f20c.png)

**Comment by kdeloach** [comment]
@jfrankl Is this intentional?

**Comment by jfrankl** [comment]
This is intentional. The + more link still shows up on mobile. I don't think we're as worried about screen real estate on desktop and I would rather show them all (knowing it is limited to 12 by parks, or however many) than have that link.
