### ISSUE TITLE
Design needs for training materials

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1188]
The training materials are in place on staging. Some design assistance is needed for:

1. Bulleted list isn't showing up as bulleted - training/progress/the_mapping_method/
2. Spacing between images and text. Some of pages would be more readable with an extra line between the image and the next paragraph of text. 
3. Size of images on tree trunk size page. They're a little large.
4. Green Ash and Swamp Oak images on tree species page are too large.
5. Material in “Perceptions of Tree Health” is supposed to be in a box as marked on the flat pages. Not sure if this will work with the layout available.

**Comment by jwalgran** [comment]
@dboyer I don't understand what is being requested in

    Material in “Perceptions of Tree Health” is supposed to be in a box as marked on the flat
    pages. Not sure if this will work with the layout available.

@designmatty do you understand this item and is it addressed in #1188 ?

**Comment by dboyer** [comment]
@jwalgran I discussed the content boxes with @designmatty and he added some background shading where possible to pull together certain images and text. I consider that problem solved.
