### ISSUE TITLE
Possibly move "Finish"/"Try Again" buttons to the top of the quiz results page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1190]
The app does not mark the quiz training step as complete until the quiz taker clicks the "Finish" button. Now that we are showing the results of every question on the score page, and there will ultimately be 10 quiz questions, the "Finish" button is way "below the fold." It seems likely that a person will click the header or the burger menu to leave the page rather than clicking finish.

![screen shot 2015-04-15 at 10 50 06 am](https://cloud.githubusercontent.com/assets/17363/7165712/1c1f8a4e-e35e-11e4-83e8-f1258b8b5f91.png)

**Comment by RickMohr** [comment]
How about BOTH at the top and the bottom?

**Comment by jfrankl** [comment]
I think we should mark the quiz as being complete when landing on this page, not upon clicking finish.

I also like the idea of the finish button being under the "Your best score..." line.

**Comment by jwalgran** [comment]
+1 to having the buttons both at the top and the bottom.

Not having to click finish ties into #1176. @steventlamb how badly would it break our training system to mark the quiz as complete though an alternate method?

**Comment by steventlamb** [comment]
I'm pretty sure it will be easy to mark the quiz step as complete upon landing on this page. I just pulled out some code that looked like it was doing that, in order to stop the `training_finished_intro_quiz` from being mutated twice in a confusing matter. It shouldn't be hard to put that code back in, along with the code to create the training result, and then just test everything to make sure it works.

I'll throw another commit onto #1176 to fix this. If it looks too complicated, I'll back out and defer.

**Comment by jfrankl** [comment]
Awesome, thanks Steve. I think that's going to save at least a few users from confusion.

**Comment by steventlamb** [comment]
It's sorta begs for the quiz completion page to also say "you've finished your training" though, no?

**Comment by jfrankl** [comment]
I think I get where you're coming from, but I think it's okay as is. The change we're talking about is to prevent a situation where somebody gets a perfect score on the quiz and then, knowing it's the last step, navigates to another page of the site. I don't think that's going to come up a ton.

I think the "You've finished your training" page has value too and I am reluctant to mix it in with the test results.

**Comment by steventlamb** [comment]
I agree. Mixing the pages would also greatly reduce users' likelihood of seeing the link to 'Groups to Follow' which only appears on the training page when it switches to `complete` mode.
