### ISSUE TITLE
Add tile bounding box to Windshaft queries

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1191]
> We should try applying the tile's bounding box in this query, as @ddohler did in http://gitlab.internal.azavea.com/upenn/veteran_homelessness/merge_requests/1874

> He commented: "This modifies Windshaft to perform a bounding box filter on selected geometries. By default, Mapnik appends a bounding box filter to the subquery generated by Windshaft, but that was causing slowdowns because geometries were getting included in a JOIN clause that were ultimately going to be filtered out anyway."

/cc @RickMohr @jwalgran @ddohler

**Comment by ddohler** [comment]
This tends to provide the greatest performance gains at high zoom levels (that is, when you're zoomed in close); the farther out you zoom, the less the bounding box reduces the number of rows in any JOINs. If most of your geometries will be on the map most of the time, this may not provide much of a boost.

**Comment by jwalgran** [comment]
We have both situations. If it does not make the zoomed out tiles slower, it is probably worth it, since the bulk of the "real work" is going to be done at the group and street level.
