### ISSUE TITLE
Blockface reservations aren't saved to localStorage

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1201]
This is a minor regression as a result of revamping the reservations workflow.

**Comment by maurizi** [comment]
Saving to localStorage was purposefully removed because it could be confusing, especially when you have cancellations in your "shopping cart"

Related: https://github.com/azavea/nyc-trees/issues/1111

**Comment by kdeloach** [comment]
Got it, there's still some references to `SavedState` in that file so wasn't sure if it was intentional.
