### ISSUE TITLE
Date display on event page is less square on mobile

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1205]
Mobile

![screen shot 2015-04-16 at 8 33 02 am](https://cloud.githubusercontent.com/assets/17363/7184686/6ec8384e-e413-11e4-957c-e2c2a6686bef.png)

Desktop

![screen shot 2015-04-16 at 8 34 23 am](https://cloud.githubusercontent.com/assets/17363/7184688/700f0638-e413-11e4-8696-4abd61373513.png)

**Comment by jwalgran** [comment]
Marked as "question" because it may be intentional.

**Comment by jfrankl** [comment]
Definitely not intentional. We'll take a look.
