### ISSUE TITLE
Group page event menu buttons have different styles at different widths

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1217]
The change corresponds to a width breakpoint somewhere before the tablet layout kicks in 

![screen shot 2015-04-16 at 12 16 55 pm](https://cloud.githubusercontent.com/assets/17363/7189267/a83cf41a-e432-11e4-8a8d-918803fc1cd3.png)

![screen shot 2015-04-16 at 12 17 12 pm](https://cloud.githubusercontent.com/assets/17363/7189268/a9fc65b0-e432-11e4-9f90-668cc185da89.png)

**Comment by jfrankl** [comment]
@designmatty, can you take a look at this? Seems related to 7562affe62339ccf2d1868eb9947f6e7543f60d7

**Comment by jwalgran** [comment]
+1 I now see the blue, filled in dropdown buttons at all widths

![screen shot 2015-04-20 at 9 31 00 am](https://cloud.githubusercontent.com/assets/17363/7234990/07ab97e8-e740-11e4-96fe-3a4b48cf592d.png)

![screen shot 2015-04-20 at 9 31 13 am](https://cloud.githubusercontent.com/assets/17363/7234991/0b2aafe4-e740-11e4-8b45-3f19f336b8db.png)
