### ISSUE TITLE
Make Treecorder easier to find

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1228]
From training events:

Participants were asked to go to the Treecorder but could not figure out how to navigate to it. 

Suggestions - @jfrankl  and @designmatty , what are your thoughts?

     a.  Could the Treecorder be added as an additional link in the Navigation bar, as a single point of entry to mapping functions (rather than through reservations / events)?
     b.  On the data entry Treecorder screen, could the heading “Treecorder” remain at the top of the screen even when users scroll down, so they remember they are in the Treecorder
     c.  Upon entry to the Treecorder screen, can the map automatically zoom to your location rather than needing the user to do something?

**Comment by jfrankl** [comment]
A. I think it would be good to add a Treecorder link in the main navigation. +1. Developers should do this (involves some conditional components).

My only addition is that if someone isn't an individual mapper and does not have an event starting, we should show some information on that page that makes it clear that they need to do one of those things before they start mapping.

B. I think that's a good idea. Design can handle that.

C. What happens now? It seems like it should zoom to the extent of your reserved blocks or blocks for the event you're attending. Developers will need to do this.

**Comment by dboyer** [comment]
@jfrankl Sounds good. I'll split this into a few issues accordingly. In terms of C, yes it zooms to the extent of your reserved blocks or the blocks for the event you're attending.

**Comment by dboyer** [comment]
Closing as split into individual issues.
