### ISSUE TITLE
Start Mapping link in nav bar when it shouldn't be

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1234]
When logged out, a Start Mapping link was present in the nav bar.  Clicking it sent me back to the page I was currently on.

**Comment by maurizi** [comment]
![tmp_14184-screenshot_2015-04-17-13-10-011310690121](https://cloud.githubusercontent.com/assets/4432106/7206849/639e1736-e503-11e4-849b-4b77953cbfe8.png)

**Comment by dboyer** [comment]
Let's think about this in the context of #1228

**Comment by maurizi** [comment]
This link is now gone
