### ISSUE TITLE
Unavailable blocks on the reservations page are not styled as unavailable according to the legend

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1247]
Legend showing different colors

![screen shot 2015-04-17 at 3 22 34 pm](https://cloud.githubusercontent.com/assets/17363/7211980/d2451cc2-e515-11e4-991a-2b17e77e5731.png)

Single tile

![98519](https://cloud.githubusercontent.com/assets/17363/7211965/ad9f2020-e515-11e4-9eda-a01ca4d6e62f.png)

Grid associated with the tile

![screen shot 2015-04-17 at 3 23 46 pm](https://cloud.githubusercontent.com/assets/17363/7211973/ca6b8edc-e515-11e4-8c88-2ba10213f928.png)

After clicking an unavailable block

![screen shot 2015-04-17 at 3 25 11 pm](https://cloud.githubusercontent.com/assets/17363/7211991/ffc2340a-e515-11e4-9cf9-7fbed5460626.png)

**Comment by RickMohr** [comment]
@jwalgran, I could only reproduce this when logged in as the administrator for the group sponsoring the event.

**Comment by kdeloach** [comment]
I was able to reproduce this issue for trusted mappers and also group admins.
