### ISSUE TITLE
Percent complete isn't advancing

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1250]
Staging has 63 blocks mapped and is still at 0% complete. Is that too few to advance the count?

**Comment by maurizi** [comment]
There are 128558 blockfaces on staging, which should make that be 0.05%
complete.

**Comment by dboyer** [comment]
So maybe we don't show any decimal points in the percentage and that's the issue. Adding decimals could make that progress circle look a bit too full of text though.

**Comment by RickMohr** [comment]
How about if we show one decimal point until we hit 10% and then show no decimal points?

**Comment by dboyer** [comment]
Sounds good to me as long as @jfrankl doesn't think it will throw off the display.
