### ISSUE TITLE
Keep Treecorder heading at top of Treecorder screens

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1251]
Split off from #1228 

On the data entry Treecorder screen, could the heading “Treecorder” remain at the top of the screen even when users scroll down, so they remember they are in the Treecorder

**Comment by RickMohr** [comment]
On my iPhone 4s there was already precious little vertical space. I would hate to lose even more for a permanent header.

**Comment by dboyer** [comment]
I also have space concerns about this. User testing on the Treecorder showed that people were very confused about how it was part of the overall TreesCount site. The header was a suggestion to remind people of where they are in the app.

**Comment by jwalgran** [comment]
This may help buy us the space we need

https://github.com/azavea/nyc-trees/pull/1258

**Comment by RickMohr** [comment]
I had this issue confused with #942. I've removed it from the current milestone, as I'm not sure of its priority. @dboyer?

**Comment by dboyer** [comment]
I think we can wait on it and implement if necessary based on the first few weeks of mapping.

**Comment by maurizi** [comment]
@dboyer Think we can close this?

**Comment by dboyer** [comment]
Yes
