### ISSUE TITLE
Move map to user's location when they enter the Treecorder

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1253]
Split off from #1228 

Upon entry to the Treecorder screen, can the map automatically zoom to your location rather than needing the user to do something?

**Comment by kdeloach** [comment]
Only if within NYC. Test by emulating location w chrome devtools

**Comment by kdeloach** [comment]
Should resolve #1107

**Comment by kdeloach** [comment]
@dboyer There was a bug where the Treecorder failed to zoom to the event location. Now that we have fixed that, is it still worthwhile to geolocate to the user position? Consider that this map also contains a geolocate button.

**Comment by RickMohr** [comment]
If we geo-locate when a user loads the treecorder, many users will get an "OK to use location?" prompt every time they go to the page. For example, that is the default setting on my iPhone -- the setting is not remembered.

I would favor not automatically geo-locating, along with perhaps a first-time tooltip for the geo-locate button.

**Comment by dboyer** [comment]
Fixing the event location but should help, although users may be counting trees several blocks from the identified location of the event since a group's census zone may be large. 

I'm fine with adding just a help tip to the geolocate button. What did you end up doing @kdeloach ?

**Comment by kdeloach** [comment]
Thanks. I will revise my PR to disable automatic geolocation and to display a help tooltip the first time that the Treecorder is accessed.
