### ISSUE TITLE
Add text below introductory sentence on dashboard

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1272]
The text in the hero image says "Welcome back, voluntreer!"

Underneath, it should say: 

In the past week, XXX trees on XXX blocks have been mapped! Keep up the great work helping us make trees count!

**Comment by RickMohr** [comment]
@dboyer, how about only showing this if more than 10 blocks have been mapped in the past week? To avoid:

```
In the past week, 0 trees on 0 blocks have been mapped! Keep up the great work helping us make trees count!
```

**Comment by maurizi** [comment]
I believe these were purposefully removed by @jfrankl because the same information is now available in the progress circles.

**Comment by jfrankl** [comment]
Yes, these were purposely removed. They are not in the most recent version of the wireframes. I think this space is better utilized by showing the progress circles.

**Comment by RickMohr** [comment]
@dboyer, close this?

**Comment by dboyer** [comment]
Leave it open but don't work on it. I'll confirm with Parks.

**Comment by dboyer** [comment]
We can forget about this.
