### ISSUE TITLE
Add text to dashboard

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1273]
<b>Intro text before the Progress section - between the hero image and the Progress label:</b>
Play a key role in the future of our urban forest!  Sign up for a mapping event or make a block edge reservation to map more trees across NYC!  

<b>Add text between Progress heading and All Time/Past Week/My Trees section:</b>
See the progress you and other volun<b>treers</b> have made in helping us count our street trees!

<b>Add text between Events heading and the Attending/Recommended tabs:</b>
Join other tree-loving citizens at street tree mapping events across the five boroughs! Sign up and help us make trees count!

<b>Add text between Groups heading and listed groups:</b>
TreesCount! Partner Groups are the heart of the 2015 Street Tree Census, having committed to mapping trees across the five boroughs! Find more groups to follow here. (more groups to follow here linked to groups page)

**Comment by dboyer** [comment]
@jfrankl This may need to go to you first due to potential impact on layout.

**Comment by jfrankl** [comment]
@dboyer and I discussed this morning. We are going to make the case to parks that adding all of this additional text will make the dashboard less useful. The dashboard should provide the user with a quick overview of the project. This additional text is going to clutter the now streamlined page, resulting in significantly more scrolling to access the content.

#1331 adds links to the headings on the dashboard. This will enable folks to learn more about those sections if they want. I don't think each of these sections needs a description though. See the attached screen shots.

Now:

![tc-notext-1](https://cloud.githubusercontent.com/assets/1809908/7264352/a3ef8894-e858-11e4-8582-2b2095713693.png)

With the proposed text:

![tc-extratext-1](https://cloud.githubusercontent.com/assets/1809908/7264351/a3ef2994-e858-11e4-9cd7-f9f387eeee56.png)

**Comment by dboyer** [comment]
I've contacted Parks and am waiting for response.

**Comment by dboyer** [comment]
Please add in the text on the dashboard.
