### ISSUE TITLE
Add Events page content

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1279]
Update text to say:

Check out our upcoming TreesCount! events and sign up to map street trees with fellow volun<b>treer</b>s!  
Click to view as a list or find an event nearby using the map!  

On map tab:

Select an event to view additional details!

Take a look at upcoming events and find your next tree mapping project.

Click to view as a list or find an event nearby using the map!

**Comment by kdeloach** [comment]
This panel isn't designed to show different text per tab. Do we really need different text on the map panel?

**Comment by dboyer** [comment]
Leave it as is for now and I'll check with Parks.

**Comment by dboyer** [comment]
Use this content for both the list and map views:

Check out our upcoming TreesCount! events and sign up to map street trees with fellow volun<b>treers</b>!

Click to view as a list or find an event nearby using the map. Select an event to view additional details!

**Comment by kdeloach** [comment]
Thanks.
