### ISSUE TITLE
Compile a list of URLs that we want crawlers to avoid and include them in a robots.txt

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1287]

**Comment by jwalgran** [comment]
The progress and reservation map pages are prime candidates for exclusion.

**Comment by maurizi** [comment]
Even if we don't exclude anything, it would be nice to have a robots.txt to avoid a bunch of spurious 404s in the logs.

**Comment by dboyer** [comment]
Unlikely to happen
