### ISSUE TITLE
Add Wrapping Up as a new training section 

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1291]
I can probably add the text and images, but I need someone to create the section so that it's add to the checklist of training sections that need to be completed by the user. 

Should be the final section and it does involve a couple pages. Details are in the text at T:\NYCParks_StreetTreeCensus\data\Training_Materials

**Comment by steventlamb** [comment]
fixed in https://github.com/azavea/nyc-trees/commit/3b41b912d1fa2640c779089eea122a0079a92ea9
