### ISSUE TITLE
Change text on page for assigning zones to groups

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1297]
Text at /census_admin/territory/ should be changed to:

Heading - Partner Group Census Zones

Body - Select a partner group to modify its census zone. Add and remove blocks by clicking them or by drawing an area. 

Is there anyway the URL can change to /censuszone/ ?

**Comment by RickMohr** [comment]
Fine to change the URL. Probably it should be `/census_admin/census_zones/` (or just `/census_admin/zones/`)

**Comment by dboyer** [comment]
census_admin/census_zones please
