### ISSUE TITLE
Yellow block edges on partner zone assignment page on production

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1298]
The /census_admin/territory/ page on production includes yellow line segments. What do these correspond to? If they're unavailable segments, shouldn't they be a different color?

**Comment by RickMohr** [comment]
Yellow represents your currently-selected segments. When you load a particular group its current territory is selected. As you select and de-select segments the yellow continues to show what segments are selected, and when you hit "Save" the group's territory is updated to match that selection.

Should we add a legend entry for yellow saying something like "Selected block edges"?

**Comment by dboyer** [comment]
Yes, let's add it to the legend.
