### ISSUE TITLE
Survey 'leave page' prompt is redundant

### ISSUE THREAD

**Issue by steventlamb** [azavea/nyc-trees#1305]
![screenshot from 2015-04-21 10 02 23](https://cloud.githubusercontent.com/assets/1699455/7254104/e223e5e6-e80e-11e4-96d8-7f5c3faa9496.png)

**Comment by steventlamb** [comment]
Proposed:
![screenshot from 2015-04-21 10 07 31](https://cloud.githubusercontent.com/assets/1699455/7254107/ebc8cee0-e80e-11e4-9dfd-60ba5c63b8d9.png)

**Comment by dboyer** [comment]
Say block edge instead of block. Otherwise it's good.
