### ISSUE TITLE
Hero image is high resolution and loads slowly

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1310]
The "hero image" is 3161 x 2100 (1.7Mb), and is often visibly slow to paint.

I suggest we downres it by half to 1580 x 1050 (0.4Mb), or keep a separate version for retina screens.

**Comment by dboyer** [comment]
I defer to @jfrankl on this.

**Comment by jfrankl** [comment]
Good catch. I don't think I ever touched this image. I'll make standard and retina versions.
