### ISSUE TITLE
Events map does not work when there are no future events

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1329]
It's clear what should happen on the map tab when there are no future events.  Perhaps we should just hide the "map" tab?

This is what it looks like now:
![events-map](https://cloud.githubusercontent.com/assets/4432106/7263641/6a13b0de-e851-11e4-9ae3-871b9cb53532.png)

**Comment by maurizi** [comment]
@jfrankl @dboyer your thoughts on what to do about this?

**Comment by kdeloach** [comment]
How about we add an event that expires in 12 months?

**Comment by maurizi** [comment]
After talking with @jfrankl I'm just going to show a blank map.

**Comment by jfrankl** [comment]
Mike and I just spoke. We will show a map with no event dots on it.

On Tue, Apr 21, 2015 at 6:12 PM, Michael Maurizi <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> @dboyer <https://github.com/dboyer>
> your thoughts on what to do about this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1329#issuecomment-94958156>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
Parks should be adding the first events in the next two days, but if they don't, I agree the blank map is a good solution.
