### ISSUE TITLE
Images are permanently hidden when you retry a failed training exercise

### ISSUE THREAD

**Issue by steventlamb** [azavea/nyc-trees#1338]
Need to refresh the page to get them back. I can produce this on staging and in development.

![screenshot from 2015-04-21 23 06 21](https://cloud.githubusercontent.com/assets/1699455/7266669/305bceb0-e87b-11e4-8f9e-a1e36d5a1704.png)
then
![screenshot from 2015-04-21 23 06 38](https://cloud.githubusercontent.com/assets/1699455/7266671/30645170-e87b-11e4-963f-bbf592cc9bf4.png)
then
![screenshot from 2015-04-21 23 06 49](https://cloud.githubusercontent.com/assets/1699455/7266670/305eb9f4-e87b-11e4-8154-69d4b5af7f4b.png)

**Comment by jwalgran** [comment]
I reproduced this on ``develop``. Testing the fix in this branch now.
