### ISSUE TITLE
Need styling for in-progress event notification?

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1348]
Currently "This event is currently in-progress!" Is shown in plain text, do we want something stronger?

![image](https://cloud.githubusercontent.com/assets/2162993/7277649/2e40d1fc-e8df-11e4-870c-45959b406812.png)

**Comment by dboyer** [comment]
Yes, I'd vote for using the same banner background or other styling we use for event checkin/resume mapping. Labeling as design.

**Comment by jfrankl** [comment]
I will add styling for this element.

Also, this is related to an issue I just opened: #1358. There are changes from wireframes a while back that were never implemented. I'll need a developer to work on those.

**Comment by jfrankl** [comment]
Closed by #1358. Nice job Mike!
