### ISSUE TITLE
Popup on reservations page goes under the legend.

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1349]
![popup-under-legend](https://cloud.githubusercontent.com/assets/4432106/7277846/3f9db2ca-e8e0-11e4-896a-e3f293a3c745.png)

**Comment by jfrankl** [comment]
This might be impossible to fix without:

1. Changing the layout of the page (using a sidebar instead of an overlay)
2. Moving the leaflet popup outside of the map container in the DOM (not going to happen)

I'm going to look into option 1.

**Comment by RickMohr** [comment]
Another option would be using JavaScript to change the legend's DOM location to be inside the leaflet map.

**Comment by jfrankl** [comment]
@RickMohr that would definitely be my ideal solution. Does that seem feasible? Is it something you all could get to next sprint?

**Comment by jfrankl** [comment]
If not, I'll do the sidebar.

**Comment by RickMohr** [comment]
Moving the legend into the map is straightforward, but we might have to strategize together how to have it continue to show up as a modal for mobile.

![image](https://cloud.githubusercontent.com/assets/2162993/7281207/0dcbbd12-e8f6-11e4-884c-23c56332811b.png)

**Comment by jfrankl** [comment]
Removing design label because Rick is on this.

**Comment by RickMohr** [comment]
We decided to fix this by auto-panning the map to avoid the sidebar. #1559
