### ISSUE TITLE
Training: description of Treecorder UI describes crosshairs, which aren't there

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1351]
"Use the target to highlight your first block edge as a red line."

![image](https://cloud.githubusercontent.com/assets/2162993/7278042/3528b83e-e8e1-11e4-8033-3a9dcef41c41.png)

**Comment by jwalgran** [comment]
We plan to add them in https://github.com/azavea/nyc-trees/issues/884

**Comment by jwalgran** [comment]
You can't actually do any mapping until events start happening in May, so it may be ok to proceed with this copy for now.

**Comment by dboyer** [comment]
Let's leave the copy for now.
