### ISSUE TITLE
Add/change text when redirecting the Treecorder navigation link

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1352]
If you register/activate an account and then click the Treecorder link, you are redirected to /training/instructions which says:

"Before you're able to RSVP to mapping events you'll need to do the following."

This redirect is correct, and necessary, but the text is now a little disorienting because it assumes you arrived by clicking an "RSVP" button.

A possible solution to this is to add a query string argument that can be passed by the redirect so that the instruction text can be changed.

**Comment by maurizi** [comment]
We may be able to just change the text slightly so it applies to both.

My suggestion for replacement text:
"Before you're able to map trees at events you'll need to do the following."

**Comment by dboyer** [comment]
I agree with @maurizi that we can deal with this by changing the text.
