### ISSUE TITLE
Training: "missing image" icons

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1353]
"Tree Data" section, "2. Tree Trunk Size":

![image](https://cloud.githubusercontent.com/assets/2162993/7278273/5a4486ba-e8e2-11e4-8b6e-0218a613e16d.png)

**Comment by steventlamb** [comment]
I think I saw that these may be fixed in @designmatty's most recent PR

**Comment by steventlamb** [comment]
This is also on reproducible on staging.

**Comment by jwalgran** [comment]
03a2678 Is on the way to staging now, which includes working images

**Comment by jwalgran** [comment]
These are now visible on staging

![screen shot 2015-04-22 at 10 43 43 am](https://cloud.githubusercontent.com/assets/17363/7281142/77a4e0d4-e8dc-11e4-9633-b3ba917787e8.png)
