### ISSUE TITLE
In progress event popup obscured on tablet/desktop, missing on mobile

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1354]
![screen shot 2015-04-22 at 8 27 48 am](https://cloud.githubusercontent.com/assets/17363/7278320/94256e62-e8c9-11e4-8e38-544eaee088f3.png)

![screen shot 2015-04-22 at 8 27 36 am](https://cloud.githubusercontent.com/assets/17363/7278322/94394f36-e8c9-11e4-8605-a7307a6a7516.png)

**Comment by jfrankl** [comment]
This element should be removed. It will no longer be on the header on all screens because people found it confusing during user testing. See #1358.
