### ISSUE TITLE
Training: quiz question not covered in training

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1359]
Question 7 "How will you know which block to map at a mapping event?" -- if you answer incorrectly it refers you to the "Orientation" section, but that section doesn't address the question (nor does any section).

**Comment by dboyer** [comment]
Excellent point. I'll let Parks know they may want to modify that text.

**Comment by dboyer** [comment]
The text of the Orientation section has been changed to address this issue.
