### ISSUE TITLE
Image disappears if training question is answered incorrectly 

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1364]
If you select the wrong answer for any training question, then click "Try Again", the image isn't there anymore.

Step 1
![image](https://cloud.githubusercontent.com/assets/43062/7279315/fa5b123a-e8e8-11e4-9557-0568a3f6fdb4.png)

Step 2
![image](https://cloud.githubusercontent.com/assets/43062/7279317/fd403070-e8e8-11e4-8d7c-00a52039e743.png)

Step 3
![image](https://cloud.githubusercontent.com/assets/43062/7279319/0067b73c-e8e9-11e4-9e6d-49a94c79bb47.png)

**Comment by jwalgran** [comment]
#1341 was supposed to have resolved this. Are you running a develop branch that includes this fix?

**Comment by kdeloach** [comment]
Yes.

**Comment by kdeloach** [comment]
Worked after rebuilding static assets. Closing.
