### ISSUE TITLE
Ensure that census_admins pages are available to permitted users in soft launch mode

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1372]

**Comment by RickMohr** [comment]
They are not.

I disabled "full_access" for everyone but left it enabled for superusers.
![image](https://cloud.githubusercontent.com/assets/2162993/7283413/5d92f03c-e904-11e4-8e4c-a8f446765243.png)

I logged in as a superuser, but got only the restricted site.

However, @dboyer seemed to think it was fine for parks to wait until the site is live to upload their polygons.
