### ISSUE TITLE
Changes to sponsors section of home page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1385]
1. Replace "Partner Sponsors" with "Partners and Sponsors" 

2. Histree should come before TreeKIT on the second line

**Comment by jwalgran** [comment]
Confirmed on staging 

![screen shot 2015-04-23 at 8 53 06 am](https://cloud.githubusercontent.com/assets/17363/7301223/32204994-e996-11e4-8c56-ca9eb1f9d590.png)
