### ISSUE TITLE
Explore Your Knowledge questions already completed even though I never took the quiz

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1399]
I created debtest0422 tonight and had never gone to the quiz before. I went through the whole training and when I got to the quiz:
 
Question 1 and 3 said I had already answered them correctly. 
Question 2 did not say that but had the correct answer highlighted in blue. 
Question 4 and 5 had the wrong answer highlighted in blue.
There were similar things for the remaining questions. The quiz thought I had already been there when I hadn't.

**Comment by jwalgran** [comment]
We save the quiz answers in local storage on the device. This behavior is by design.

**Comment by dboyer** [comment]
Even when I'm logged in as a different user? That seems less than ideal.

**Comment by jwalgran** [comment]
I agree. We can try adding the logged-in username into the local storage key so that every user has their own "database" of recorded answers

**Comment by dboyer** [comment]
That might be useful but perhaps not necessary for launch. Your call.
