### ISSUE TITLE
Odd characters in email subject line

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1401]
You are registered for NYC Parks&#39; 1st Training Event on Tuesday, May 19th

Received an email with that as the subject line when I registered for /group/nyc-parks/event/trees-count-2015-mapping-event/

**Comment by jwalgran** [comment]
Can you append a screenshot? I do not see any odd characters in the issue description.

**Comment by dboyer** [comment]
![email](https://cloud.githubusercontent.com/assets/516764/7288905/a3cbbd90-e936-11e4-87e1-4f0ecd93bec3.png)

**Comment by jwalgran** [comment]
``&#39;`` is an HTML code for an apostrophe and it looks like it does not render properly in a plain text subject line
