### ISSUE TITLE
Progress page Groups view: can't easily zoom back out to overview after clicking a polygon

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1412]
1) Open Progress page
2) Choose "Groups" view, see entire city
3) Click on a group polygon, map zooms in

Now if you want to see the entire city again you have to laboriously zoom back out many steps.

**Comment by maurizi** [comment]
Possible partial solution to this: When choosing "All Users" from the dropdown we change the map bounds back to the initial view of the entire city.
