### ISSUE TITLE
Add TreesCount logo and change text in event PDF

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1414]
Currently, it says TreesCount! 2015 Event Map. Add in the logo before Event Map.

For you @jfrankl  - I think. @RickMohr is the person to talk to about PDFs.

**Comment by dboyer** [comment]
Also, we need to add: 

- the location description field 
- whether it's a training or mapping event

**Comment by dboyer** [comment]
We are holding on this. No need to get it in before launch - it can be a hot fix on Monday.

**Comment by hectcastro** [comment]
If there are any already generated event PDFs, we may have to force an update to regenerate them with the logo.

**Comment by RickMohr** [comment]
@jfrankl, happy to pair on this if you want.

**Comment by dboyer** [comment]
@jfrankl Is it possible to label the location description with the "How to find us" title as it is on the website?
