### ISSUE TITLE
Events can't be edited through Django admin on production

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1417]
Census admins can't edit events on the Django page because they get they attached error, even when a location was added. 

Any change there's a fix for this on staging already?

![screen shot 2015-04-23 at 11 08 52 am](https://cloud.githubusercontent.com/assets/516764/7300256/2e580af0-e9a9-11e4-87b8-0ee6687eb1a1.png)

**Comment by maurizi** [comment]
Yes, this works on staging

On Thu, Apr 23, 2015 at 11:09 AM, dboyer <notifications@github.com> wrote:

> Census admins can't edit events on the Django page because they get they
> attached error, even when a location was added.
>
> Any change there's a fix for this on staging already?
>
> [image: screen shot 2015-04-23 at 11 08 52 am]
> <https://cloud.githubusercontent.com/assets/516764/7300256/2e580af0-e9a9-11e4-87b8-0ee6687eb1a1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1417>.
>



-- 
Michael V. Maurizi Jr
Software Developer
Azavea |  340 N 12th St, Suite 402, Philadelphia, PA
mmaurizi@azavea.com  | T 215.558.6190
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>

**Comment by dboyer** [comment]
I just got it to work too. My first attempt didn't work for some reason. Why isn't it working on production?

**Comment by maurizi** [comment]
I believe the issue on production was fixed by
https://github.com/azavea/nyc-trees/pull/1231

On Thu, Apr 23, 2015 at 11:14 AM, dboyer <notifications@github.com> wrote:

> I just got it to work too. My first attempt didn't work for some reason.
> Why isn't it working on production?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1417#issuecomment-95621303>.
>



-- 
Michael V. Maurizi Jr
Software Developer
Azavea |  340 N 12th St, Suite 402, Philadelphia, PA
mmaurizi@azavea.com  | T 215.558.6190
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>

**Comment by dboyer** [comment]
Excellent. I'll leave this open as a reminder to confirm once we're deployed to production, but will remove launch labels. Thanks for checking.
