### ISSUE TITLE
Add new training image

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1427]

**Comment by dboyer** [comment]
Image attached. This needs to be in a PR so I can reference it in the training materials. 
![orientation_image](https://cloud.githubusercontent.com/assets/516764/7306335/92e1267c-e9d2-11e4-8d15-18c0d0a319fc.jpg)

**Comment by steventlamb** [comment]
Since this email was included via github, it doesn't have a sane name. Can you provide one?
