### ISSUE TITLE
Tiler performance evaluation

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1430]

**Comment by RickMohr** [comment]
For each page using the tiler, here's a spreadsheet showing expected blockface count (order of magnitude) and expected traffic (high/medium/low): https://docs.google.com/a/azavea.com/spreadsheets/d/1C3Iz03YaA-YEBhkNktuMlwF98RL_Mzarn_8O2yIPxwM/edit?usp=sharing

The "Progress - All Users" page looks like the most important by far.

I think we should strongly consider building a static tile set (for a few outer zoom levels) so we only have to render blockfaces mapped after a certain date. To avoid performance degradation we can regenerate it periodically and bump the date.

Also, on the many pages where we zoom to show particular blockfaces we should make sure we are zooming **before** issuing tile requests. Rendering a small number of blockfaces should be quick for the tiler, but not if we mistakenly render the entire city first.

**Comment by RickMohr** [comment]
@maurizi and I realized we could get most of the benefit of the "static layer + recent updates layer" approach without the complexity of generating static tiles. We'd rely on CloudFront for the static layer, updating its cache buster only every week or so. If you happen to miss the cache you have an expensive tile, but usually it will be cheap.

**Comment by hectcastro** [comment]
All of the following are recordings of the `all-users-3x-zoom-blockedge-progress.jmx` JMeter test plan executed against the staging environment with a pair of tiler instances behind a load balancer.

---

### Instance comparison with `metatile=4` and `db.m3.large`

**m3-medium-metatile-4-db-m3-large**

![m3-medium-metatile-4-db-m3-large](https://cloud.githubusercontent.com/assets/43639/7351674/a64a85aa-ecd4-11e4-940d-58b66d846800.png)

**m3-large-vs-c3-large-metatile-4-db-m3-large**

![m3-large-vs-c3-large-metatile-4-db-m3-large](https://cloud.githubusercontent.com/assets/43639/7351689/cd3f40d8-ecd4-11e4-91db-80f316d5abea.png)

---

### Series of `c3.large` comparisons

**c3-large-db-m3-large**

![c3-large-db-m3-large](https://cloud.githubusercontent.com/assets/43639/7351744/1d670212-ecd5-11e4-99bf-4fce5c418f84.png)

**c3-large-metatile-1-db-m3-xlarge**

![c3-large-metatile-1-db-m3-xlarge](https://cloud.githubusercontent.com/assets/43639/7351762/39d54d64-ecd5-11e4-87f4-2d05a3a71e82.png)

**c3-large-metatile-2-db-m3-xlarge**

![c3-large-metatile-2-db-m3-xlarge](https://cloud.githubusercontent.com/assets/43639/7351763/39d75546-ecd5-11e4-86f8-0c91f6511d66.png)

**c3-large-metatile-4-db-m3-xlarge**

![c3-large-metatile-4-db-m3-xlarge](https://cloud.githubusercontent.com/assets/43639/7351761/39d3bb7a-ecd5-11e4-9a80-12ecd149a5fa.png)

**c3-large-pgpool-db-m3-xlarge**

![c3-large-pgpool-db-m3-xlarge](https://cloud.githubusercontent.com/assets/43639/7351772/4c0ea624-ecd5-11e4-8676-57eaa7c8f3f8.png)
