### ISSUE TITLE
Achievements page on production is requiring login to view

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1435]

**Comment by maurizi** [comment]
It shows your achievements and the ones you have yet to earn, so I assumed it would have to be only visible to logged in users.

I suppose we can just hide the first section with your achievements?

**Comment by dboyer** [comment]
It's the way users can learn about what achievements are available so I think it should be visible to everyone. I don't think we need to hide the Earned section. It would just be blank.
