### ISSUE TITLE
Make gunicorn retry refresh when in development mode

### ISSUE THREAD

**Issue by steventlamb** [azavea/nyc-trees#144]
Sometimes I save files in the middle of typing a line of code. In this case, gunicorn reloads with syntax errors, and the process dies. I have to restart it. It would be great if it retried a few times.

Using gunicorn in development has been awesome so far!

**Comment by kdeloach** [comment]
I've actually grown accustomed to this behavior.

**Comment by kdeloach** [comment]
Close?

**Comment by maurizi** [comment]
@kdeloach +1, I almost never want gunicorn to restart when it fails, because generally I have a syntax error somewhere.
