### ISSUE TITLE
DB dump task not running daily

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1456]
https://github.com/azavea/nyc-trees/blob/develop/deployment/ansible/roles/nyc-trees.app/tasks/cron.yml#L9 defines a cron job that should run daily, but the S3 bucket does not contain daily dumps.

**Comment by maurizi** [comment]
Possibly caused by the failure noted in https://github.com/azavea/nyc-trees/issues/1115?

**Comment by jwalgran** [comment]
I triggered the dump manually this morning (5/27) and it ran without error.
