### ISSUE TITLE
Group admin can't reserve blocks in their territory

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1462]
On the reservations page such blocks are shown as blue (available) but clicking on one gives "Unavailable Block Edge"

**Comment by kdeloach** [comment]
I think we should seriously consider merging `restrictions` and `survey_type` to prevent this from happening.

**Comment by jwalgran** [comment]
Related to the more general #1247

**Comment by kdeloach** [comment]
I was able to reserve blocks as group admin. Could this have been a styling issue on the blocks (as described by #1247)?

**Comment by dboyer** [comment]
I also was able to reserve blocks as a group admin.

**Comment by maurizi** [comment]
@RickMohr is this still an issue for you?

**Comment by RickMohr** [comment]
I also verified that this is fixed.
