### ISSUE TITLE
Simplify process of adding another tree or submitting data in the Treecorder

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1483]
From Parks: we also found that users were getting confused with where the "Distance to End" button is located - they automaticaly click "Add another tree" to only then realize there isn't another tree to be added because they are at the end of the block.

Possible change -  Perhaps a way to tweak this would be to give the user two button options at the end of each tree's data entry screen - "Add another Tree" or "End of the Block" so they have to make a deliberate decision whether or not to add another tree.

Thoughts @jfrankl  or @designmatty ?

**Comment by designmatty** [comment]
I think it would be smart to hide the "Distance to End" block and only toggle it on when "End of the Block" is clicked.

**Comment by dboyer** [comment]
If we go that route, we still have to require people enter a distance to end before they can submit the data. I'm a little concerned about the wording of "End of Block." It seems like users might only think to click that if the tree is located at the very end of the block and not if it's in the middle of the block but actually the last tree on the block.

**Comment by designmatty** [comment]
Could we change the wording of the button to something like "No Further Trees" and then change the label of "Distance to End" to "Distance to End of Block"? Or does that still not solve the problem?

![screen shot 2015-04-29 at 12 08 53 pm](https://cloud.githubusercontent.com/assets/1928955/7395554/898dc3ba-ee68-11e4-90f9-76c0afe12f84.png)

**Comment by jfrankl** [comment]
Matt, I like your + Another Tree / No Further [or More] Trees buttons.
Could we combine that with not showing the distance to end of block until
someone presses no further trees?

On Wed, Apr 29, 2015 at 12:09 PM, Matt Williams <notifications@github.com>
wrote:

> Could we change the wording of the button to something like "No Further
> Trees" and then change the label of "Distance to End" to "Distance to End
> of Block"? Or does that still not solve the problem?
>
> [image: screen shot 2015-04-29 at 12 08 53 pm]
> <https://cloud.githubusercontent.com/assets/1928955/7395554/898dc3ba-ee68-11e4-90f9-76c0afe12f84.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1483#issuecomment-97482993>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
I also like the idea of the combined button plus not showing Distance to End until someone selects No Further Trees. I need to run this by Parks since it's a workflow change.

**Comment by maurizi** [comment]
Presumably we will also need to hide/disable the "Submit" button until "Not Further Trees" is selected (since we can't show a validation that distance to end is required if the field is hidden).

**Comment by dboyer** [comment]
@designmatty Parks is good with this approach. A couple comments:

1. In the above design, the + Another Tree/No Further Trees looks as if it could be a multi-select option similar to the problems section. Could they be two distinct buttons instead? Or at least more obviously an either/or set of options where the user doesn't think they could choose both (even though those options conflict).

2. We likely should hide or at least disable the submit button until someone enters the distance to end. 

3. There's also this newly added option - https://github.com/azavea/nyc-trees/pull/1504 - which may impact design.

**Comment by dboyer** [comment]
Never mind on my third point. It's just an X next to the tree number, which is great.

**Comment by RickMohr** [comment]
@dboyer, re (2) -- "distance to end" is just one of many fields a user could forget.  Having it disable the submit button where other missing fields don't could be confusing. Currently if you hit submit with the field empty it scrolls you right there and tells you to enter a value (as with all missing fields).  We should stay consistent IMHO.

**Comment by dboyer** [comment]
I'm fine with having distance to end not be displayed until the user makes the previous + Another Tree/No Further Trees selection unless @designmatty has concerns about that approach.

**Comment by designmatty** [comment]
We could leave a statement explaining they must map the last tree before they can submit. When they click on "no further trees" hide the statement and show the "distance to end" and the submit button.

![screen shot 2015-05-04 at 11 55 11 am](https://cloud.githubusercontent.com/assets/1928955/7456744/cfe0c93a-f254-11e4-9672-eeae00cb835f.png)
![screen shot 2015-05-04 at 11 57 11 am](https://cloud.githubusercontent.com/assets/1928955/7456743/cfe0212e-f254-11e4-9875-454d98ab6c23.png)

**Comment by dboyer** [comment]
Let's try that approach. Please change the text to: When you've added all the trees, please select "No Further Trees on Block" and submit your data.

**Comment by designmatty** [comment]
Okay, I'll work on this today.
