### ISSUE TITLE
Generate a point column on the blockface table and show it as the initial layer on the all progress map

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1490]
The data is not distinguishable as lines at low zooms, so using a point layer will cut the amount of data that the tilers need to process in half

CartoCSS must be tweaked to reflect line vs. point

Measurements to compare before/after change
  - Data size passed between VMs
  - Slow query log output

**Comment by jbranigan** [comment]
FWIW, the CartoCSS from http://cdb.io/1bTTjKA
```
/** lines */

#bronx_compiled[zoom<12] {
   line-width: 0;
   line-opacity: 0.7;
}

#bronx_compiled[zoom>=12] {
   line-width: 2;
   line-opacity: 0.7;
}

#bronx_compiled[expertmapp=0] {
   line-color: #592e11;
}
#bronx_compiled[expertmapp=1] {
   line-color: #229A00;
}
/** points */

#bronx_compiled_center {
   marker-fill-opacity: 0.5;
   marker-line-width: 0;
   marker-placement: point;
   marker-type: ellipse;
   marker-width: 2;
   marker-allow-overlap: true;
}

#bronx_compiled_center[expertmapp=0] {
   marker-fill: #592e11;
}
#bronx_compiled_center[expertmapp=1] {
   marker-fill: #229A00;
}
```

**Comment by kdeloach** [comment]
Thanks John.

**Comment by kdeloach** [comment]
This change had the following result: The data transfer rate between the db and the tiler decreased by half, but the duration of time to render tiles on the client increased significantly.

With that in mind, I don't think this change is worthwhile. Closing for now.

**Comment by hectcastro** [comment]
More context for the issue below. Tests were against a pair of c3.larges with a m3.large database:

![pasted_image_5_4_15__09_27](https://cloud.githubusercontent.com/assets/43639/7454264/ed1cce6e-f23f-11e4-810c-c0fe47488b97.png)

![pasted_image_5_4_15__09_29](https://cloud.githubusercontent.com/assets/43639/7454276/01e53688-f240-11e4-9db9-04de7d02c4f9.png)

![pasted_image_5_4_15__09_29](https://cloud.githubusercontent.com/assets/43639/7454283/12131ca0-f240-11e4-8b57-e6285a82f1e2.png)
