### ISSUE TITLE
Remove grid requests from progress page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1492]
~~Measure first - remove grid requests from JMeter script and run on existing code~~

Trade clickability for cutting tile requests in half. 

Measurements to compare before/after change
  - Data size passed between VMs
  - Slow query log output

**Comment by hectcastro** [comment]
Graphed output that compares the `all-users-3x-zoom-blockedge-progress.jmx` JMeter test plan with and without the UTF grid requests:

![image](https://cloud.githubusercontent.com/assets/43639/7397915/79c93b38-ee79-11e4-9828-2757ac9d0b32.png)

![image](https://cloud.githubusercontent.com/assets/43639/7397925/82054b84-ee79-11e4-958a-e79d28598325.png)

![image](https://cloud.githubusercontent.com/assets/43639/7397929/884ab9fc-ee79-11e4-83c8-c5e7c6af235d.png)

![image](https://cloud.githubusercontent.com/assets/43639/7397941/8d1aa992-ee79-11e4-9b6b-576421d60ece.png)

![image](https://cloud.githubusercontent.com/assets/43639/7397942/912b94ce-ee79-11e4-811e-6021a5dc6c83.png)

![image](https://cloud.githubusercontent.com/assets/43639/7397944/9527e8fc-ee79-11e4-9fcb-fa8d3dfd237b.png)

**Comment by hectcastro** [comment]
How I'm measuring traffic from PostgreSQL to the tiler virtual machine:

```bash
vagrant@tiler:~$ sudo iftop -i eth1 -B -f "src port 5432 and host 33.33.33.30”
```

**Comment by jwalgran** [comment]
All graphs show a decrease in resource usage. Since we round trip to the server to get block details, it is pretty clear that we should follow through with removing the grid.

**Comment by jwalgran** [comment]
Fetching a geom by ID is  0.035 ms. Fetching via a spherical distance query is 0.247 ms.

```
SELECT  "survey_blockface"."id", "survey_blockface"."geom", "survey_blockface"."is_available", "survey_blockface"."expert_required", "survey_blockface"."source", "survey_blockface"."created_at",
"survey_blockface"."updated_at" FROM "survey_blockface" WHERE "survey_blockface"."id" = 220441; 

 Index Scan using survey_blockface_pkey on survey_blockface  (cost=0.42..8.44 rows=1 width=119) (actual time=0.015..0.016 rows=1 loops=1)
   Index Cond: (id = 220441)
 Total runtime: 0.035 ms
```

```
p = Point(...tap location...)
qs = Blockface.objects.filter(geom__dwithin=(p, 0.0001))\
                      .distance(p)\
                      .order_by('distance')

SELECT (ST_distance_sphere("survey_blockface"."geom",ST_GeomFromEWKB('\001\001\000\000 \346\020\000\000\000\000\000\200\245|R\300\271\210\264h3WD@'::bytea))) AS "distance", "survey_blockface"."id", "survey_blockface"."geom", "survey_blockface"."is_available", "survey_blockface"."expert_required", "survey_blockface"."source", "survey_blockface"."created_at", "survey_blockface"."updated_at" FROM "survey_blockface" WHERE ST_DWithin("survey_blockface"."geom", ST_GeomFromEWKB('\001\001\000\000 \346\020\000\000\000\000\000\200\245|R\300\271\210\264h3WD@'::bytea), 0.0001) ORDER BY "distance" ASC;

 Sort  (cost=8.81..8.82 rows=1 width=119) (actual time=0.220..0.221 rows=4 loops=1)
   Sort Key: (_st_distance(geography(geom), '0101000020E610000000000080A57C52C0B988B46833574440'::geography, 0::double precision, false))
   Sort Method: quicksort  Memory: 25kB
   ->  Index Scan using survey_blockface_the_geom_webmercator_id on survey_blockface  (cost=0.28..8.80 rows=1 width=119) (actual time=0.171..0.213 rows=4 loops=1)
         Index Cond: (geom && '0103000020E61000000100000005000000B22E6E23A77C52C0552BD82130574440B22E6E23A77C52C01DE690AF365744404ED191DCA37C52C01DE690AF365744404ED191DCA37C52C0552BD82130574440B22E6E23A77C52C0552BD82130574440'::geometry)
         Filter: (('0101000020E610000000000080A57C52C0B988B46833574440'::geometry && st_expand(geom, 0.0001::double precision)) AND _st_dwithin(geom, '0101000020E610000000000080A57C52C0B988B46833574440'::geometry, 0.0001::double precision))
         Rows Removed by Filter: 1
 Total runtime: 0.247 ms
```

**Comment by RickMohr** [comment]
Note potential optimization described in http://postgis.refractions.net/documentation/manual-2.0/geometry_distance_centroid.html -- get nearest neighbor candidates using fast imprecise `<->` operator (which uses spatial index) and refine using slow precise `ST_distance_sphere`.

**Comment by jwalgran** [comment]
I set the network throttling in the Chrome dev tools to "Regular 3G (750kbps)" and the tap responses felt immediate. I am content with 250 microseconds.
