### ISSUE TITLE
Checked-in users can continue mapping in a group's area until midnight the day of the event

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#150]

**Comment by dboyer** [comment]
@jwalgran Parks just confirmed that midnight the day of the event is the cutoff for all data entry, even if they are mapping on paper. They don't want data entry to linger for days after an event.

**Comment by maurizi** [comment]
@dboyer How do they access the survey page? Should they treecorder link in the nav still go to the event until midnight the day of?

**Comment by dboyer** [comment]
Good question. Yes, having the Treecorder link go to the location of the event until midnight seems logical.
