### ISSUE TITLE
Restrict the functionality of banned users and show ambassador status on check-in page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1530]

**Comment by RickMohr** [comment]
Currently our User model has unused fields `is_flagged`, `is_banned`, and `is_ambassador`. We should either do something with them or remove them.

**Comment by dboyer** [comment]
Parks would like the ban option. Waiting to hear back from them on flagged and ambassador.

**Comment by jwalgran** [comment]
ambassador and flagged are for reporting, but won't be shown in the UI

**Comment by dboyer** [comment]
Parks confirmed the following info:

- Checking the banned box on the Django admin page should prevent that user from being able to log into TreesCount.

- Checking the flagged box should cause a flag on the user table. Parks will use that data, joined to the survey table, to see all surveys added by flagged users.

- If the ambassador flag is checked, an "ambassador" note should be next to that user's username on the event check-in page. The ambassador designation does not need to be displayed anywhere else. If group admins know who the ambassadors are, they can designate those people to serve as assistants to more novice mappers.

**Comment by dboyer** [comment]
To clarify, displaying the ambassador status on the event check-in page can just be the word "Ambassador" under that person's user name. There is no need to have a filter by ambassador function or special icon or anything like that.
