### ISSUE TITLE
Shorten width of species autocomplete list

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1539]
From Parks:

It is also hard to click away from the list, especially on the mobile screen - there is just not enough inactive white space to click on, to make the list go away.  Perhaps this could be addressed by making the field slightly less wide than the screen, so that when the user scrolls down the screen to the next variable they do not accidentally trigger the species list, which is making them frustrated.

Thoughts @designmatty ? This is likely also connected to the other species list issues described in #885

**Comment by designmatty** [comment]
This is something I had thought about in the past. Making the box width smaller is a good solution

**Comment by dboyer** [comment]
Great. Let's do that then.
