### ISSUE TITLE
Make Yes button more prominent on survey review page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1540]
Make Yes the first button in the list rather than "No, restart" or "No, submit for review." It can also be a bit larger or otherwise more prominent than the other two buttons.

**Comment by designmatty** [comment]
@dboyer Would you prefer the first or second?

![screen shot 2015-05-07 at 9 52 52 am](https://cloud.githubusercontent.com/assets/1928955/7516695/f2c3b6e6-f49e-11e4-84b8-24bf29da9d36.png)
![screen shot 2015-05-07 at 9 53 23 am](https://cloud.githubusercontent.com/assets/1928955/7516696/f2c6a39c-f49e-11e4-8818-3726a449c1a6.png)

**Comment by dboyer** [comment]
I like the first better, but don't feel strongly so will defer to your design skills if you like the latter.

**Comment by designmatty** [comment]
I was leaning toward the first as well.
