### ISSUE TITLE
Reservations page: clicking empty space gives JavaScript exception

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1546]
This exception is only visible if you have the developer tools open, but may prevent other important code from running (now or in the future).

SelectableBlockfaceLayer.onAdd (reserveBlockfacePage.js:89)
module.exports.BlockfaceLayer.extend.addBlockface (SelectableBlockfaceLayer.js:71)
(anonymous function) (SelectableBlockfaceLayer.js:56)
L.Mixin.Events.fireEvent (leaflet-src.js:461)
L.UtfGrid.L.Class.extend._click (leaflet.utfgrid-src.js:118)
L.Mixin.Events.fireEvent (leaflet-src.js:473)
L.Map.L.Class.extend._fireMouseEvent (leaflet-src.js:2224)
L.Map.L.Class.extend._onMouseClick (leaflet-src.js:2204)
L.DomEvent.addListener.handler (leaflet-src.js:6403)

**Comment by kdeloach** [comment]
I have a fix in one of my PRs but it didn't get merged in yet. See https://github.com/kdeloach/nyc-trees/commit/e19f7b14cf25cb652bfb0c0f6c6a7b894316df69.

**Comment by maurizi** [comment]
@kdeloach Is this fixed now?

**Comment by kdeloach** [comment]
Fixed by e19f7b14cf25cb652bfb0c0f6c6a7b894316df69.
