### ISSUE TITLE
Email content showing escaped characters

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1565]
When rendering plain text emails, HTML escaping needs to be disabled

![screen shot 2015-05-06 at 8 00 38 am](https://cloud.githubusercontent.com/assets/17363/7495974/35d770be-f3c6-11e4-8beb-4539be8e9997.png)

**Comment by steventlamb** [comment]
relevant: http://stackoverflow.com/questions/8774902/how-to-prevent-auto-escape-in-django-templates

**Comment by jwalgran** [comment]
also relevant https://github.com/azavea/nyc-trees/pull/1406/files

**Comment by steventlamb** [comment]
True, but with the way we send emails being kinda frameworky, it probably makes sense to abstract this too.
