### ISSUE TITLE
RSVP email doesn't give event end time

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1569]
RSVP for an event, and check your inbox. The email gives the event start time but not the event end time.

Also, there is a spurious line break between "or" and "check-in":
```
You can view the full details of the event, cancel your reservation, or
check-in when the event starts by following this link
```

**Comment by kdeloach** [comment]
I think the end time is intentionally omitted.

**Comment by dboyer** [comment]
The text from Parks included a date/time line with start and end dates (example below). If possible, we should add the end time, but this can also wait until after launch.

When: Wednesday, April 1st 8AM to 10PM

**Comment by kdeloach** [comment]
Looks like an error on my part when I updated the RSVP email template last time. Will make this correction now.

**Comment by RickMohr** [comment]
+1, tested
