### ISSUE TITLE
"My Progress" map shows no tiles

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1581]
1) Go to https://treescount.azavea.com and log in as rmohr / rmohr
2) Click "MY TREES" and note that this user has mapped 2 blocks
3) Go to the Progress page 
4) Open the developer tools, Network tab, filter by "png", and click the clear button
5) Choose "My Progress" from the drop-down

The map zooms to the extent of the mapped blocks, but no map tiles are displayed. The network tab shows that only base map tiles were requested, no blockface tiles.

This problem does not happen if logged in as admin / admin.

**Comment by hectcastro** [comment]
Reproduced following the steps above. Adding a note that switching to "All Progress" and back to "My Progress" does fire off new requests.
