### ISSUE TITLE
Update species list

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1583]
Parks has sent some changes.

**Comment by jwalgran** [comment]
@dboyer I could not find the updates on the file share or attached to an email. Could you point me to them?

**Comment by dboyer** [comment]
I've emailed the file, but the necessary changes are:

1. Remove Halesia caroliniana from the list entirely (row 62)
2. Update Salix babylonica (row 135)
3. Add Acer platanoides 'Crimson King' (row 11), Aesculus X carnea (row 19), Carpinus betulus (row 29), Crataegus crusgalli var. inermis (row 52), Prunus cultivar (row 101), Prunus virginiana (row 102)
