### ISSUE TITLE
Change Individual Mapper button and add text

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1605]
1. Change the "Request Individual Mapper Status" button on the dashboard and profile pages to "Request Independent Mapper Status"

2. Add text near the button (not sure whether there's room above or below):

Submit a request to map block edges independently, outside of mapping events.

**Comment by RickMohr** [comment]
The text "individual mapper" appears in many other places as well. Presumably we should change them all to "independent mapper"?

**Comment by dboyer** [comment]
I have a question out to Parks about that. I'm assuming yes but waiting for confirmation.

**Comment by designmatty** [comment]
@RickMohr there are a bunch of `.py` files which contain "Request Individual Mapper Status". Am I to change those as well, or should i focus solely on `.html` files

**Comment by kdeloach** [comment]
@designmatty Feel free to update the python files. It looks like those references are from unit tests.

**Comment by RickMohr** [comment]
Yes, if it's anywhere in the project as part of a string we should change it. (Once @dboyer says go...)

**Comment by dboyer** [comment]
Unfortunately no word from Parks yet. I'll ping them again.

**Comment by dboyer** [comment]
@designmatty Parks confirmed that we should mass change individual mapper to independent mapper. Please change all mentions of individual mapper in the app.
