### ISSUE TITLE
[Part of 1592] Change color ramp on progress map

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1635]
Include Parks greens

standard green - 
RGB R108, G190, B70
HEX #88C659

dark green - 
RGB R0, G104, B61
HEX #0407056

@jfrankl - maybe for you?

**Comment by dboyer** [comment]
See color ramp at https://github.com/azavea/nyc-trees/pull/1578

**Comment by jfrankl** [comment]
@dboyer does the second ramp in https://github.com/azavea/nyc-trees/pull/1578#issuecomment-99908299 seem okay to you?

**Comment by dboyer** [comment]
I think that's fine.
