### ISSUE TITLE
styling issue on treecorder map

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1656]
There is an odd space at the top of the screen when the page loads.  After interacting with anything on (panning the map, opening the side nav, touching the actionbar) the spacing goes away.

 (Tested on Firefox for android)

**Comment by maurizi** [comment]
![tmp_5827-screenshot_2015-05-14-15-55-58-882861680](https://cloud.githubusercontent.com/assets/4432106/7640612/34cbd196-fa52-11e4-96f8-de9c0409f9c3.png)
![tmp_5827-screenshot_2015-05-14-15-55-42388174511](https://cloud.githubusercontent.com/assets/4432106/7640615/37d8bf66-fa52-11e4-8989-8b23c7fddcfa.png)

**Comment by jfrankl** [comment]
I was able to reproduce this glitch. It happens on all maps. Took some time trying to fix it with no success.

**Comment by dboyer** [comment]
@jfrankl Should this go into the next milestone or should we drop it for now? Doesn't seem to impact usability.

**Comment by jfrankl** [comment]
I think we should drop it for now. This doesn't break functionality, and it's only on an uncommon browser.
