### ISSUE TITLE
action bar on event map is below the fold.

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1657]
When clicking on an event on the event list map, I had to scroll the page to see all of the action bar (hard to do on a page with a map)

Tested on firefox for Android

![tmp_5827-screenshot_2015-05-14-16-03-341248189385](https://cloud.githubusercontent.com/assets/4432106/7640726/0a88426a-fa53-11e4-8f18-a78db4b1c113.png)

**Comment by maurizi** [comment]
Sometimes the actionbar fully visibly, but scrolling the map will scroll the page in addition to the map.

**Comment by jfrankl** [comment]
I couldn't reproduce this on the office Nexus in Firefox. I also don't get this issue across Android devices using default browser or on iOS.

**Comment by jfrankl** [comment]
Also, my understanding is that Firefox has a very small marketshare on Android. If this issue is limited to specific versions of Firefox on specific devices, I don't think it's worth putting resources into this glitch.
