### ISSUE TITLE
Out of date screenshot of Training materials

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1659]
The text and screenshot should probably be updated to reflect that you must choose "No more trees on this block" in order to input the distance to the end of the block.

Current screenshot:
![](https://treescount.azavea.com/static/img/training/Distance_To_End.png)

**Comment by maurizi** [comment]
This is on: page 1 of "Wrapping up", page 5 of "The mapping Method"

**Comment by dboyer** [comment]
Use the attached instead with the filename Distance_To_End.png so that it matches the current path.

![screenshot_2015-05-14-22-39-02](https://cloud.githubusercontent.com/assets/516764/7646556/13deebc6-fa93-11e4-9b9c-1f8366d2dd85.png)

**Comment by dboyer** [comment]
Also, I'll talk to Parks and update the text myself if necessary.

**Comment by jwalgran** [comment]
It is important that the case of the file name and extension match exactly.
The last tile I replaced one of these images a change in extension case led
to problems.

**Comment by hectcastro** [comment]
Confirmed on release stack.
