### ISSUE TITLE
Make all event bulk event email send from a verified address by set the Reply-To header to the event contact

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1660]
Amazon SES will only allow sending from verified addresses. Currently the "email attendees" page fails to send emails because it is attempting to set the "from:" address to the group admin. ~~We can fix this by either:~~

1. ~~Sending all "email attendees" messages from treescount.help@parks.nyc.gov~~
1. ~~Using the AWS console to verify the addresses of all event contact. This will require personal coordination with the owners of the email accounts and will require ongoing maintenance to add new contacts.~~

We can use the Reply-To header get around this problem.

```python

if event.contact_name:
    from_email = '%s <%s>' % (event.contact_name, settings.DEFAULT_FROM_EMAIL)
else:
    from_email = settings.DEFAULT_FROM_EMAIL

msg = EmailMessage("Test Subject", "Test Body", from_email, ["recipient@domain.com"], [],
                   headers={'Reply-To': 'event-contact@foo.bar'})

**Comment by dboyer** [comment]
The second option doesn't seem realistic. We could make the first work if the help text above the email form mentioned that group admins should include their email address in the email text so that event registrants can contact them. I'll run this by Parks.

**Comment by jwalgran** [comment]
I emailed Parks and proposed @hectcastro 's suggestion of using the Reply-To field, so that all mail will come from the single, verified address, but the Reply-To header will be set to the event contact email.

**Comment by jwalgran** [comment]
Parks agreed to the Reply-To option

**Comment by hectcastro** [comment]
Confirmed on release stack.
