### ISSUE TITLE
Treecorder buttons cut off on iPhone 4

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1662]
![img_0003](https://cloud.githubusercontent.com/assets/4432106/7641699/6965b320-fa59-11e4-9971-fd1425223507.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/4432106/7641703/70cf1b1a-fa59-11e4-8358-87930f823531.PNG)

**Comment by RickMohr** [comment]
When you scroll most web pages on an iPhone the Safari footer disappears and the header shrinks. That doesn't happen with TreesCount!, which reduces are available space significantly.

Probably it doesn't happen because of our fixed header. @jfrankl, @designmatty, any thoughts?
