### ISSUE TITLE
Actionbar text scrolls over map on iPhone 4

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1663]
Happens whenever you drag to scroll from one of the fixed elements, like the actionbar or header
![img_0007](https://cloud.githubusercontent.com/assets/4432106/7641729/a1180dc2-fa59-11e4-909f-b0a1d1673420.PNG)
![img_0008](https://cloud.githubusercontent.com/assets/4432106/7641732/a6c40190-fa59-11e4-85b0-c9bef03cd652.PNG)
![img_0009](https://cloud.githubusercontent.com/assets/4432106/7641736/aa0c2828-fa59-11e4-9ba2-0585bf2db380.PNG)

**Comment by jfrankl** [comment]
What version of iOS?

**Comment by maurizi** [comment]
iOS7, using the iPhone 4 we have in the office

**Comment by jfrankl** [comment]
Do the screens get stuck in the position of your screen shot or do they bounce back?

**Comment by maurizi** [comment]
They bounce back

**Comment by jfrankl** [comment]
Seems like how iOS scrolling works. I don't know how to change that, but let me know if you know something I don't know.

**Comment by maurizi** [comment]
I would have expected the map to scroll too, so that the text doesn't
doesn't sit over the map.  If that is hard to fix though, this isn't
exactly a showstopper bug, since it does bounce back.
