### ISSUE TITLE
404 when requesting trusted mapper status

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1666]
1. While not logged in, I went to the group page for A Tree Grows in Brooklyn and clicked the request independent mapper status button. 
2. I was prompted to login and did so with my dboyer account which has census admin privileges.
3. group/tree-grows-brooklyn/request-trusted-mapper-status/ loaded but displayed as a 404.

**Comment by dboyer** [comment]
Maybe related. 

1.I went to the homepage then back to groups page then a tree grows in Brooklyn page. 
2. Clicked request independent mapper status again
3. Was taken to the reservations instructions page where all requirements were checked as completed.

**Comment by RickMohr** [comment]
@dboyer, your second issue (landing on the reservations instructions page) is what we do if you are the group admin or are already a trusted mapper for the group in question. Is one of those true in this case?

**Comment by RickMohr** [comment]
For these (second issue) cases we could instead show a page saying something like "You already have independent mapper status for this group."

In addition, if you are logged in and have independent mapping rights for the group, the group page could show a message like "You have independent mapping privileges in this group's Census Zone." rather than showing the independent mapping information and button.

**Comment by kdeloach** [comment]
The endpoint for requesting mapper status only accepts POST, not GET requests, which results in a 404. We should probably redirect back to the group detail page after login.

**Comment by RickMohr** [comment]
Created #1668 for the second issue.

**Comment by kdeloach** [comment]
For the "reservations instructions page" issue:

If the user has independent mapper status already, clicking this button should take them to the Reservations page. If you don't have all the requirements necessary to make reservations you get forwarded to the Reservations Instructions page. We should either disable this button or figure out why qualified trusted mappers are being forwarded to the Reservations Instructions page.
