### ISSUE TITLE
[Part of 1592] Group admin can change event capacity to less than the number of people registered

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1676]
1. I set up an event with a capacity of two.
2. I RSVPed two people to the event.
3. I logged in as the group admin and changed the event capacity to one.
4. The event then had 2 of 1 people registered - /group/american-hornbeam-appreciation-society/event/a-new-event-may-15/

We should not allow the group admin to change the event capacity to fewer than the number of people already registered.

**Comment by dboyer** [comment]
This has become an issue on production - https://treescount.nycgovparks.org/group/prospect-park-alliance/event/GRkZLRtmbJefzJqfBozuVa/

**Comment by jwalgran** [comment]
I mistakenly fixed this before noticing that it was in the milestone for next sprint.
