### ISSUE TITLE
Add a management command to install the ESRI:102718 NY state plane projection

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1684]
The state plane projection which gives us the most accurate geometry construction is not included with PostGIS by default. We will need to add a command to our [setupdb.sh](https://github.com/azavea/nyc-trees/blob/develop/scripts/aws/setupdb.sh) script to ensure that we have a row for SRID 102718 in ``spatial_ref_sys``. The query we need to run is already [documented](https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/apps/survey/fixtures/README.md#source-data).

**Comment by jwalgran** [comment]
This may not be required. Looking into it.

**Comment by hectcastro** [comment]
Before attempting to update `spatial_ref_sys`, we need to set the owner to `rds_superuser`:

```sql
ALTER TABLE public.spatial_ref_sys OWNER TO rds_superuser;
```
