### ISSUE TITLE
Remove blockface geom field from the Django admin

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1696]
The field does not display properly, and we don't want editing to be available anyway.

![image](https://cloud.githubusercontent.com/assets/43062/7707030/e0f66ac2-fe1b-11e4-8c85-56dd0898ddcb.png)

**Comment by dboyer** [comment]
Unless this is a quick fix, we don't need to address it since the census zone can be seen on the publicly visible group detail page.
