### ISSUE TITLE
On iOS8, the species autocomplete list does not appear until after the first key is pressed

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1698]
When you tap the species autocomplete, you should see a dropdown telling you to "type 3 or more characters".  This dropdown does not appear in iOS8 until after a key is pressed.

It does appear immediately in iOS7.

**Comment by maurizi** [comment]
Interestingly, this is not a problem for the teammate autocomplete.

**Comment by dboyer** [comment]
This seems minor enough that we don't need to spend time on it.
