### ISSUE TITLE
Events are over capacity

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1707]
![capture](https://cloud.githubusercontent.com/assets/2162993/7749201/6741f208-ff99-11e4-9e54-3d4fc25fd62f.PNG)

![capture](https://cloud.githubusercontent.com/assets/2162993/7749213/82096ed6-ff99-11e4-8cbe-db84eeb02b94.PNG)

Not clear how the events got this way.  They currently say "At Capacity" and I cannot RSVP.

**Comment by dboyer** [comment]
Closing as duplicate of #1676
