### ISSUE TITLE
Many public events have "private" slugs

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1708]
For example:

https://treescount.nycgovparks.org/group/prospect-park-alliance/event/GRkZLRtmbJefzJqfBozuVa/

https://treescount.nycgovparks.org/group/new-york-botanical-garden/event/4sQRUurcVgK2WLhLq6bXN7/

https://treescount.nycgovparks.org/group/qc_counts2015/event/fjLoJXfdvzqsm8AMeUGgcQ/

**Comment by jwalgran** [comment]
I believe were created as private events, and then switched to public events before we had code in place to update the slug when the privacy value changed. Since Parks has the ability to update slugs through the Django admin, I am inclined to close this.

**Comment by dboyer** [comment]
I agree. Closing.
