### ISSUE TITLE
Tree count too low for groups [Part of 1714]

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1717]
The NYC Parks group (https://treescount.nycgovparks.org/group/nyc-parks/) only shows 5 trees mapped despite holding 18 events with 89 attendees. 

Parks reports that blocks around event locations are marked as mapped by independent mapper rather than as part of the event.

**Comment by dboyer** [comment]
Maybe fit this under #1714

**Comment by dboyer** [comment]
I'm checking with Parks on a few questions, but we should also look into the second part of the issue where the progress map indicates the blocks near events have been mapped by independent mappers rather than NYC Parks. See the block near this event (https://treescount.nycgovparks.org/group/nyc-parks/event/treescounttraining-520-fid-5/) as an example.

**Comment by maurizi** [comment]
Ok, so the issue here has to do with assigning block edges to census zones.

When we are adding/removing block edges from census zones, we don't let you add a mapped block edge to a group (because it was not a part of that group when mapped).

*But*, there seems to be a bug in that code, such that when you update a group's block edges, it *removes* all of the mapped block edges from that group.

**Comment by dboyer** [comment]
I think there's something else going on. The Parks group had 400 some trees mapped yesterday morning and now only has 15 trees mapped and the block counter is at 0.0%.

**Comment by maurizi** [comment]
@dboyer That would make sense if they updated the census zone for the NYC Parks group yesterday.  All of their mapped blocks would be "lost" and cause their counts to go down (but we can get them back).

**Comment by dboyer** [comment]
Actually, Parks may have done a census zone update yesterday afternoon which would explain the change. I'm confirming that.

However, they also confirmed that the blocks mapped around 50th Street and 10th Avenue were mapped by non-independent mappers and yet display as mapped by independent mappers.

**Comment by maurizi** [comment]
@dboyer We just assume any block not in group territory was mapped by an independent mapper, which is why those "lost" blocks shows as mapped by an independent mapper on the progress page.  When we get those blocks back in the NYC Parks territory, they'll show up correctly on the progress map.

**Comment by dboyer** [comment]
Got it. Parks confirmed they updated territory yesterday afternoon so that's definitely the source of the problem.

**Comment by dboyer** [comment]
Well, this bug is the source of the problem but you know what I mean.
