### ISSUE TITLE
Increase CacheCluster freeable memory threshold to at least 100MB

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#1723]
On staging, the Redis cache cluster node did not drop its freeable memory below 60MB, yet began to swap. I think that it may need to be increased to at least 100MB so that we have time to react before it gets close to ~60MB:

![cloudwatch_management_console](https://cloud.githubusercontent.com/assets/43639/7778798/e2b6452a-009c-11e5-9c5a-0712ff6188ed.png)

**Comment by maurizi** [comment]
@hectcastro Do you still think this is necessary?
