### ISSUE TITLE
Improve the performance of rendering the teammate autocomplete

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1726]
As of  6c1d6bd1, on a vagrant VM, rendering the ``survey.html`` template with 2200+ users causes gunicorn to peg the CPU and not finish within the Nginx timeout. The same code, with the same data works in production.

Inlining the ``teammate_item.html`` template into ``teammates.html`` prevents the CPU spike in development, but performance degrades as you increase the user count.

**Comment by maurizi** [comment]
The fact that inlining the template "fixed" the issue makes me suspicious that the Django debug toolbar is to blame, since it shows every template that was included in the page and context for each one.

**Comment by jwalgran** [comment]
Parks is also getting feedback this is now slow an unwieldy with ~3000 users. They suggested making the teammate list work like the species list, where you must enter a few characters before the autocomplete list is displayed. This is a good idea, but there could be users with 1 or 2 character usernames, so, we need to make sure those users are selectable.

**Comment by dboyer** [comment]
This is unblocked and we should go ahead and implement.
