### ISSUE TITLE
Restore whitespace between teammate combo and "next" button on treecorder

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1774]
I needed to increase the size of the action bar to accommodate more help text. It looks like there was a small style regression as a result.

![screen shot 2015-06-26 at 8 02 52 am](https://cloud.githubusercontent.com/assets/17363/8380343/10e806c4-1bda-11e5-81b7-cae0b9d0bf4c.png)

**Comment by maurizi** [comment]
I don't see this on staging, so I think this may actually be a regression introduced by my PR.

**Comment by jwalgran** [comment]
Needs to be fixed in #1773, not develop
