### ISSUE TITLE
View From the Peanut Gallery

### ISSUE THREAD

**Issue by xeaa2ll** [azavea/nyc-trees#1775]
I am an independent mapper user of the mapping app. It is a nice piece of work. Thanks!

There are a few things I would like to comment on. (I don't know how to just comment on a project in GITHUB, the only means of my contacting you that I see it New Issue. Sorry for that.)

Merged 1773 / inline teammate ... to AJAX - I like that the list isn't going to populate unless something is entered. I map with my wife, so the other person is constant. Show previous people first? Moving to the next edge is just slow, time consuming and should be faster to accomplish with less steps.

When I make reservations at home (zoom is easier on a real PC with mouse) and go out onto the street, there is no proceed to mapping button. I have to change the reservations somehow to get mapping.

After deleting a reservation (one of the changes from above), I can't start mapping the rest of the reserved edges. No button to do it.

As an independent, I'm mapping in the same neighborhood. Zoom in to that area to start reservations so I don't have to zoom in from the city level.

Enable scrolling of the map under the data collection area? I just mapped a 1000 foot block with 15 trees twice. In the middle it had a curb stone for a corner. I 'completed' it to see the verification map. Had to restart, as the three choices, Yes, No, Submit for Review, did not fit the case of continue mapping. Or, add a continue option.

Show block numbers even after mapped. I messed up the block across the street from 321850. I don't know the number so I can't request that it be 'undone'.

Thanks for all the work. I like what I'm using this time. This is much easier than it was in the past two census data gathering periods.

Ed

**Comment by RickMohr** [comment]
Thanks very much for the comments. Note you can always "Start Mapping" by clicking the "Treecorder" link in the main menu:
![image](https://cloud.githubusercontent.com/assets/2162993/8408659/dc87f8c2-1e3f-11e5-9303-429feb3b4c09.png)

**Comment by xeaa2ll** [comment]
Nice to know that. Training was less then comprehensive.



Thanks,
Ed

**Comment by xeaa2ll** [comment]
I just submitted this to Parks, not sure how it gets to you.
We have been mapping for a few weeks as independent mappers. After the
software change to speed up the teammate autocomplete (that has improved),
I now see problems in the app. It is crashing my tablet (Nook HD+) and the
data capture 'page' refresh is not smooth or complete. Sometime I lose an
entire question, it just does not refresh. Sometimes I lose a button on
problems (other).
It is working, but it is very frustrating. It worked 5 or 6 sessions with
no issues. Since that fix for autocomplete, it has been 'bad'.
I have not seen any traffic in the forum on my observed problem, so I
thought I would report it directly rather than lurk.


Thanks,
Ed

**Comment by dboyer** [comment]
Thanks for explaining the issue with the data capture pages. I've also forwarded your comments to Parks to see if they have also noticed the issue.

**Comment by xeaa2ll** [comment]
I sent this follow up to Parks, they wanted some more data

Nook HD+ 2.2.1
Android 4.0.4
Chrome 42.0.2311.111
As soon as I start recording an edge of trees, the data capture window on
top of the map starts to misbehave and refresh randomly or not completely.

Up until this week, for three mapping session, the browser and app behaved
fine. Upload and download speed don't appear to be an issue. This started
when the Team-mate dropdown was changed to require a letter to be entered
(I'm following the forum on GITHUB, seeing the comments from the
development staff) before being displayed (they shifted to AJAX).




Thanks,
Ed

**Comment by xeaa2ll** [comment]
Just sent this to Parks:

Back to the Future - 2005
The application behaving poorly on two tables and one HTC Evo 4G phone.
Can't use it. Had to revert to paper and key entry on PC and even the PC is
having problems in Firefox 38.05 on WIn 8.1. I pasted in a cut off prompt
box. Only happened that one time. I am attaching two screen shots of the
tablet, I hope you can see the treecorder pane not painting correctly. I
mapped at Arvern, in a group, using the same tablet and had no problem for
6 edges.


[image: Inline image 1]



Thanks,
Ed
