### ISSUE TITLE
Show mapped and unmapped blocks on event map PDF

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1780]
Use the colors from the progress map (green for mapped and brown for unmapped). May be useful to do in conjunction with #1779

**Comment by jwalgran** [comment]
For this map to be accurate, any time a block is mapped within the territory, we need to trigger the regeneration of the PDF. When an event is in progress, this would trigger many times, enough to block our celery queues uncomfortably. As part of the implementation we should test how the staging environment reacts to a large number of queued map render requests.

**Comment by maurizi** [comment]
It is possible to cancel a queued celery task, so one way to handle large
queues is to save the celery I'd in the DB and cancel any outstanding jobs
for the event when retriggering a PDF job.

**Comment by dboyer** [comment]
Parks understands that the map currently only regenerates when the event location moves and is fine with keeping that as the only thing that causes a new map.

**Comment by dboyer** [comment]
This feature is more about being able to assign block edges for mapping at the beginning of an event rather than having a constantly updated map during the event.

**Comment by jwalgran** [comment]
My concern was around this situation:

- An event is created and scheduled two weeks into the future. It is never edited.
- In those two weeks, individual mappers survey block edges around the event location.
- On event day, the original event map PDF shows block edges as available, but those edges have been surveyed.

This may not be a likely occurrence, but I want to make sure that all the event organizers understand how the application works, and that these maps may not be current at the time they are downloaded.
