### ISSUE TITLE
Content changes needed

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1794]
On staging:

1. Header on rewards page says "all achievements" rather than "all rewards"

2. Sprout mapper reward - extra r in tree-rrific

3. Mayoral mapper reward - VIP should be bold

**Comment by hectcastro** [comment]
Whoever grabs this, please make the pull request go against `release/11.0.150804`.

**Comment by RickMohr** [comment]
"tree-rrific" is from their doc. I think it's supposed to have two r's like "terrific".

**Comment by RickMohr** [comment]
PR merged to `release/11.0.150804`
