### ISSUE TITLE
Investigate progress map coloring for block edges that were marked as unmappable for a reason

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1800]

**Comment by dboyer** [comment]
Blocks marked by the user as "unmappable" do not appear on the progress map as mapped (green) or count towards the progress counter although the block edge can no longer be reserved / is no longer available for mapping, as designed.

**Comment by maurizi** [comment]
From @dboyer: Unmappable blocks could be a different color on the progress map, but they would count toward the progress counter.

**Comment by dboyer** [comment]
Blocks marked as unmappable should be shown as a third color on the progress map - a grey color similar in shade to the green and brown on the map. Blocks marked as unmappable count toward the progress counts and are not available to reserve and map again.
