### ISSUE TITLE
Add dot showing your location to Reservations pages

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1812]
The Treecorder currently has a dot showing your location. Add it to Reservations as well.

**Comment by steventlamb** [comment]
Don't change initial extent. Show dot if it happens to be in current extent.

**Comment by dboyer** [comment]
Is this on staging? I can't see the dot but that may be due to my location outside NYC.

**Comment by maurizi** [comment]
@dboyer You should be able to see the dot somewhere in Philadelphia (likely not our actual location but the location of our ISP).

**Comment by dboyer** [comment]
Unfortunately, not. It zoomed to our location but I see no dot in the greater Philly/Delaware region.

**Comment by jwalgran** [comment]
I loaded up the staging site, used the Chrome location emulator and saw a dot on the reservations page.

<img width="855" alt="screen shot 2015-10-01 at 3 50 28 pm" src="https://cloud.githubusercontent.com/assets/17363/10235769/4d40d9d6-6854-11e5-99cb-4d45cadf8e78.png">
