### ISSUE TITLE
Implement final text changes

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1860]
- Need to add "Reward in development. Stay tuned!"

- Possible changes to event text on rewards and dashboard pages?

**Comment by dboyer** [comment]
- In registration email, change the first sentence after the activation email link to: "Once you have clicked the link above, your email address will be added to our list for updates on TreesCount! progress.

- Text not visible on Progress Map page. Tested as independent mapper with and without winter mapping access and public user and it never appeared.

- There's an extra period after "training materials here" on the training page when viewing it as a user who has completed training.

- There needs to be a space between "gear!" and "This block edge..." on the new reservation confirmation page.(blockedge/checkout-confirmation/)

**Comment by maurizi** [comment]
Also need to change "Restart Block" to just "Restart" on the treecorder preview screen.

**Comment by dboyer** [comment]
From Parks:

FAQ AND ABOUT
·         When can I view the data?

Please change NYC Street Tree Map to “NYC Tree Map”       

·         Please Remove “If you have an urgent question, please call 212-360-TREE”

**Comment by dboyer** [comment]
- Remove events section from logged in dashboard
