### ISSUE TITLE
Crosshairs on Treecorder block selection misaligned

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1866]
On smaller screens, the crosshairs fall behind the help text or are not centered on the map.

**Comment by dboyer** [comment]
![img_0472](https://cloud.githubusercontent.com/assets/516764/15032258/f6cf16e8-122c-11e6-80e0-6eed387905b4.PNG)

**Comment by dboyer** [comment]
![img_0472](https://cloud.githubusercontent.com/assets/516764/15032271/14add6a4-122d-11e6-917a-958b1d10f0fa.png)

**Comment by jwalgran** [comment]
I think this is the source of the regression

https://github.com/azavea/nyc-trees/commit/e77f3ab23b83c23499f8d2bd8b950d6aeab82c9b#diff-2d673cf24021cc99e1c1a29e34d437deR25

If I revert the media query back to what it was

```sass
@media (max-width: $screen-sm) {
    bottom: 20rem;
}
```

The crosshairs start working again because the map div shrinks properly.

**Comment by designmatty** [comment]
@jwalgran you're totally right. Adding that 20rem back in will fix this.

**Comment by maurizi** [comment]
@designmatty I believe adding it back in will break something else on the treecorder screen. I can stop by and show you.

**Comment by designmatty** [comment]
@maurizi I'll work on it tomorrow so we can chat about it then
