### ISSUE TITLE
Tree tab arrows stack after previewing a block

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1868]
Seen on a Galaxy tab. Screenshot attached.
![arrow_stack](https://cloud.githubusercontent.com/assets/516764/15050125/d716e9d2-12bf-11e6-9e64-d8fcd5239802.png)

**Comment by maurizi** [comment]
I tried using several different Android phones on browserstack.com (including a Galaxy Tab 4 and a Galaxy Tab 2), and I could not reproduce this issue.

@dboyer Do we have any more information about how this bug was triggered?  Does it happen reliably on the device they're testing with?

**Comment by dboyer** [comment]
More info - 

The error occurs after clicking the preview block button for only the next tree. In the attached photo I only previewed the block on Tree 2, Tree 4, and Tree 6 creating that arrow stacking formation. When I didn’t click the preview button, Tree 1, Tree 3, and Tree 5, the trees were added normally.
 
This issue occurs on a Galaxy Tablet, the device our data collectors use, using 5.1.1 android operating system.
![screenshot_2016-05-09-12-35-58](https://cloud.githubusercontent.com/assets/516764/15124440/17e0c7ec-15f6-11e6-9404-bc6232b5159e.png)

**Comment by jwalgran** [comment]
I tried to replicate the steps described on BrowserStack using the following devices 

* Nexus 9 - Android 5.1
* Galaxy 6S - Android 5
* Galaxy Note 4 - Android 4.4

I did not see the stacking issue, but none of these devices is a perfect match to the 7" Galaxy Tab running Android 5.1.

We do not have a video of the issue, so it is possible that I was missing a crucial step when trying to reproduce the workflow as described.

**Comment by designmatty** [comment]
I also tried on a Nexus 5 - Android 5.1.

I was not able to reproduce the issue.

**Comment by dboyer** [comment]
I believe we can close this as something that can't be reproduced.
