### ISSUE TITLE
Map on Reservations page only fills half of screen

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1875]
See attached screenshot. I replicated this issue on a Samsung phone.
![screenshot_2016-05-16-13-25-34](https://cloud.githubusercontent.com/assets/516764/15323410/e6b5e402-1c0f-11e6-90f9-39445d12a442.png)

**Comment by designmatty** [comment]
I'm taking a look into this.

**Comment by designmatty** [comment]
this was also happening on other map pages (not the treecorder though). I fixed it on reservations and the progress map. Are there any other map pages in the application I should be aware of @dboyer

**Comment by designmatty** [comment]
oh found the group pages was also affected

**Comment by dboyer** [comment]
That should be it. Thanks!
