### ISSUE TITLE
Tool to append lat/lng to a CSV of tree measuements

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1879]
Refer to 2016_06_15_TreesCount_Support_Hours_Geometry_Constructor.docx

**Comment by maurizi** [comment]
New spreadsheet:
projects/NYCParks_StreetTreeCensus/downloads/2016_11_23_NYC_Parks_Data_for_Treecorder.xlsx

**Comment by jwalgran** [comment]
Some technical discussion that happened during the estimation process

> We can adapt the JS getLatLngs function to work in Python, get the start and end points of the specified blockface, and determine to which blockface point the supplied survey start point is closer. Since we are only comparing distances, not using them for math, we don’t have to worry about the fact that we will be running linear distance calculations on spherical points.

> Psudo code

```
lat_lngs = get_lat_lngs(blockface)
distance_to_start = calculate_distance(start_point, lat_lngs[0])
distance_to_end = calculate_distance(start_point, lat_lngs[len(lat_lngs) - 1])
survey.is_mapped_in_blockface_polyline_direction = distance_to_start < distance_to_end
```
