### ISSUE TITLE
Support shutting down TreesCount

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1890]

**Comment by jwalgran** [comment]
From the scope of work:

> When requested by NYC Parks, Azavea will backup the TreesCount database and provide a compressed archives of the code available in the public Github repository. Detailed documentation on how the code was assembled will not be included. NYC Parks will be responsible for shutting down the TreesCount website and redirecting the URL. NYC Parks is responsible for all AWS hosting costs.
