### ISSUE TITLE
Allow census admins to map any block, regardless of individual mapper or trusted mapper status

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#199]

**Comment by dboyer** [comment]
@jwalgran Parks would like census admins to be able to edit data anywhere. So they automatically get individual mapper status and can map in any group's area without requiring approval from the group first. They can also map in a group's area even if that group has denied individual mappers.

**Comment by kdeloach** [comment]
I will verify the existing behavior, ensure that census admins can reserve/survey any block regardless of individual/trusted mapper status, and add unit tests.

**Comment by kdeloach** [comment]
Didn't realize this was not assigned to the current sprint milestone. Will hold off on this until we finish all issues in the current sprint first.

**Comment by jwalgran** [comment]
Parks has requested, and I think it is a good idea, to use ``is_superuser = 't' `` to lift the ``group_territory`` restriction in https://github.com/azavea/nyc-trees/blob/develop/src/tiler/sql/user_reservable.sql#L29-L31

**Comment by jwalgran** [comment]
This doesn't have to happen this sprint, so I am going to put it into the backlog.
