### ISSUE TITLE
Styling needed for User Settings > Emails

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#216]
1) Wireframes show large checkboxes (Or will they be large automatically on mobile?)
2) Double rule at the bottom

![image](https://cloud.githubusercontent.com/assets/2162993/5572388/a2c17f0e-8f6b-11e4-8eaa-9f07fc05f884.png)

**Comment by jfrankl** [comment]
Actually, I can't figure out how to fix this. Need developer assistance.

Here's what I'd like to see happen:

- Remove the chevron: remove ```.rightarrow```
- The entire item shouldn't be a link. The title of the event can be a link, but not the whole containing element.
- Add ```.text-right``` class on the element that contains the check box so it's flush against the right

**Comment by dboyer** [comment]
I'm not seeing the checkboxes to sign up for emails for an event. Now it just has the event info and a chevron.

**Comment by kdeloach** [comment]
Related to #633; Fixed by #635.
