### ISSUE TITLE
Accessing profile privacy settings is confusing

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#219]
It seems like there are two ways to access profile privacy settings. 

1. From the main profile page (/user/deb/), I click the Privacy button shown below which loads a pop-up box with the privacy settings. 

![profile_privacy](https://cloud.githubusercontent.com/assets/516764/5580145/563fb020-9014-11e4-9a64-dfbdbbdb88ab.png)

![profile_privacy_popup](https://cloud.githubusercontent.com/assets/516764/5580147/5a5a6948-9014-11e4-91db-de653704c2a1.png)

2. From the settings page (/user/settings/), I can click on the privacy tab to load the same options but not as a pop-up and without the X to close the profile. 

![settings_privacy](https://cloud.githubusercontent.com/assets/516764/5580179/a1e2560e-9014-11e4-9ab9-2567927e5d51.png)

There's also a Privacy link in the sidebar navigation (not yet active). Does that take you to the privacy tab on the settings page or does that load the pop-up that is accessible from the main profile page? 

So the question is do we need both of these privacy screens since they do the same thing? Could the privacy button on the main profile page take you to the privacy tab on the settings page? Thoughts @jfrankl ?

**Comment by jfrankl** [comment]
The privacy button on the navigation would go to the settings page.

The benefit of using a modal window for the privacy options on the profile
page is that it makes it easy for someone to change their privacy settings
and be right back on the profile page. If we send someone to a separate
settings page, it's a little less fluid, but still okay. Deb, if you'd
prefer that, we can do that.

Jeff

On Tue, Dec 30, 2014 at 11:14 AM, dboyer <notifications@github.com> wrote:

> Also, I don't think we need the X button if we have a cancel. But that
> might just be me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/219#issuecomment-68369683>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
I'll defer to your design expertise @jfrankl . Let's stick with the modal for now.

**Comment by jfrankl** [comment]
We should make sure to get feedback on this during user testing.

On Wed, Jan 7, 2015 at 5:28 PM, dboyer <notifications@github.com> wrote:

> I'll defer to your design expertise @jfrankl <https://github.com/jfrankl>
> . Let's stick with the modal for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/219#issuecomment-69104222>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>
