### ISSUE TITLE
Event drop-down not visible 

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#221]
I signed in as a group admin, went to the events tab, and clicked the drop-down arrow by an event. See the below screenshot. 

![event_dropdown](https://cloud.githubusercontent.com/assets/516764/5580396/3ae55b5a-9018-11e4-910b-fdc78ffdb05a.png)

**Comment by dboyer** [comment]
This is mostly fixed, but there needs to be some padding between the bottom of the drop-down and the bottom of the page. 
![events](https://cloud.githubusercontent.com/assets/516764/5982744/59f1c526-a894-11e4-9040-c8e5fc220e5e.png)

**Comment by maurizi** [comment]
@dboyer Alternatively, we could make it go "up" instead of down.

**Comment by dboyer** [comment]
I defer to @jfrankl on that

**Comment by jfrankl** [comment]
This might be fixed when we add in the footer. Let's hold off until then.

On Fri, Jan 30, 2015 at 3:32 PM, dboyer <notifications@github.com> wrote:

> I defer to @jfrankl <https://github.com/jfrankl> on that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/221#issuecomment-72265721>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
Fixed in wide and skinny views

![screen shot 2015-02-26 at 10 51 16 am](https://cloud.githubusercontent.com/assets/17363/6397944/736988e2-bda5-11e4-8b68-9e17423dc934.png)

![screen shot 2015-02-26 at 10 50 39 am](https://cloud.githubusercontent.com/assets/17363/6397945/7369988c-bda5-11e4-956f-b5b473c2f06e.png)
