### ISSUE TITLE
Prevent creating or editing an events with a start time in the past

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#226]
I can add an event with a date in the past. I feel like users should have to select a future date. Any reason we should allow event creation for dates that have already passed?

**Comment by dboyer** [comment]
There is no need to support events dated in the past. We're adding a "field training complete" field on the user model to support marking someone as trained instead. Events should not be able to be back dated.

**Comment by kdeloach** [comment]
Related #400.

**Comment by kdeloach** [comment]
Fixed by #466?

**Comment by maurizi** [comment]
@kdeloach Yep
