### ISSUE TITLE
Create an application health check endpoint

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#232]
Add a health check endpoint to the application that load balancers can hit to determine application health.

**Comment by kdeloach** [comment]
Done in #657.

**Comment by hectcastro** [comment]
I'd like to reopen this because I think the health check reference in the Nginx configuration was misleading.

Right now `/health-check` via Nginx hits the `/` Django route. Ideally, there would be a custom Django `/health-check` route that purposely pokes other important parts of the application to determine health. When that exists, the Nginx configuration would be updated to point to it.

There is a specific configuration block in Nginx for `/health-check` to bypass the automatic 301 redirect to HTTPS. To the ELB, anything other than a 200 gets treated as a failure, even if that's a 301 -> 200.

**Comment by kdeloach** [comment]
I see, that makes sense.

**Comment by hectcastro** [comment]
I was pointed to an [interesting library](http://django-watchman.readthedocs.org/en/latest/index.html) that attempts to address this issue in a reusable way by @notthatbreezy.

**Comment by jwalgran** [comment]
Based on the docs Watchman looks like a great platform for health checks. The management command is a nice bonus for CI.

I would vote for a bare minimum setup, adding watchman to our requirements/settings, and mounting it under our existing url `url(r'^health-check/', include('watchman.urls'))`.

**Comment by hectcastro** [comment]
In addition to the PR referenced above, here is an associated change in Pingdom:

![banners_and_alerts_and_uptime_reports](https://cloud.githubusercontent.com/assets/43639/6564798/dae78548-c681-11e4-84ca-468b3adc41fc.png)
