### ISSUE TITLE
Make image and contact URL not required when adding a group via the Django admin

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#233]
Some groups will be too small to have websites and the census admin setting up the group  may not have access to a logo image. The group administrator can add those items via the group edit page on the public facing side of the site.

**Comment by dboyer** [comment]
Group admin as well. I could see Parks setting up a group without knowing who the admin would be.

**Comment by steventlamb** [comment]
@dboyer echoing @maurizi's question here:
> While we're here should we make contact_email have blank=True as well?

**Comment by steventlamb** [comment]
Reopening because it has a remaining question.

**Comment by dboyer** [comment]
@steventlamb Let's leave it required for now as there most likely will be an email address for the group since that group needs to be communicating with Parks for them to even be added to the system. We can remove it later if we need to.

**Comment by steventlamb** [comment]
Great, closing then.
