### ISSUE TITLE
Need Affiliation field on the groups model

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#234]
There should be a field called Affiliation that is an open text field. The group admin can enter the name of a larger group with which their group is affiliated (i.e. Brooklyn Maple Lovers enters Maple Lovers of Greater New York in the affiliation field). The affiliation field will be searchable from the groups page.

This is a new item that may not be represented on the wireframes.

**Comment by jwalgran** [comment]
Make sure to update the group search JS to include affiliation.

**Comment by dboyer** [comment]
Affiliation is not a required field.
