### ISSUE TITLE
Create application server IAM roles

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#242]
Create an IAM role for the staging and production AWS accounts named `AppServerInstanceProfile` with the following policy (we don't have IAM write access):

```javascript
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ses:SendEmail",
        "ses:SendRawEmail"
      ],
      "Resource": "*"
    }
  ]
}
```

(This allows us to send e-mail via SES via EC2 instances.)

---

1. Click "Roles"

![screen_shot_2014-12-31_at_15_22_17](https://cloud.githubusercontent.com/assets/43639/5590401/3211bb1a-9101-11e4-94f2-1a50e550d411.png)

2. Create New Role

![screen_shot_2014-12-31_at_15_22_24](https://cloud.githubusercontent.com/assets/43639/5590403/50c6a3ea-9101-11e4-9066-7c2f51933aab.png)

3. Name Role

![screen shot 2014-12-31 at 15 22 59](https://cloud.githubusercontent.com/assets/43639/5590407/5e7641a8-9101-11e4-86da-72e4faa7350f.png)

4. Select Amazon EC2

![screen_shot_2014-12-31_at_15_23_05](https://cloud.githubusercontent.com/assets/43639/5590413/7a15bb3c-9101-11e4-9310-2e942e16bf75.png)

5. Set Policy

![screen shot 2014-12-31 at 15 23 12](https://cloud.githubusercontent.com/assets/43639/5590415/8c1f48e8-9101-11e4-8019-fc17dd08260e.png)

![screen shot 2014-12-31 at 15 23 24](https://cloud.githubusercontent.com/assets/43639/5590418/956364a2-9101-11e4-8311-f28af2ef3366.png)

6. Finalize

![screen shot 2014-12-31 at 15 23 28](https://cloud.githubusercontent.com/assets/43639/5590420/9e1249a6-9101-11e4-84ff-54c5d4d4c7ef.png)

**Comment by hectcastro** [comment]
@dboyer Just tested this and it works on both the staging and production accounts.

**Comment by dboyer** [comment]
Great. Thanks for handling that.
