### ISSUE TITLE
What customizations need to be done to the paper worksheets based on reservation details

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#246]
From the scope:

    PDF of the paper worksheet (TreeKIT or NYC Parks will provide Azavea with a non-PDF
    version of the worksheet for use in customizing based on the blocks reserved)

What customization is needed?

**Comment by ebarry** [comment]
Is this regarding the context map that a mapper would download based on their reservation?

**Comment by jwalgran** [comment]
Not the context map, but rather the blank worksheet where users record distance, species, etc. for each tree.

**Comment by ebarry** [comment]
Since blockfaces do not have street names in their attributes, i do not believe there is any customization needed on the data collection worksheets based on the reservation made. Context maps based on reservations do need to be customized though.

**Comment by jwalgran** [comment]
Thanks for the clarification. Every mapper who chooses to work on paper will get the same worksheets, and a custom map that shows the blockfaces that have been reserved.
