### ISSUE TITLE
Fix event attendance counts on Group Detail

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#251]
When a single user attends 2 events held by the same group, should that count as 1 "event attendee" or 2?

**Comment by dboyer** [comment]
I've sent this question to Parks. Waiting on response.

**Comment by dboyer** [comment]
@maurizi Parks has confirmed that the items in the contributions section on the Groups page should be -

    trees mapped
    events held
    % of the group's area mapped
    event attendees

Event attendees should be total attendees - a straight up count of the number of people at all events. This is not a unique attendee count; people should be counted twice if they attend more than one event.

**Comment by kdeloach** [comment]
@maurizi Does this go against the current behavior? (Reference: https://github.com/azavea/nyc-trees/commit/918d4c39da7d777ed242b18cbf09b97ffa6f2104#diff-f6382fd5dd7d68018a59c37f7e328c97R281)
