### ISSUE TITLE
If user is outside New York, don't zoom to their address.

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#253]
If the user clicks the "geolocate" button on one of our maps, don't zoom to their address if they are outside of New York City.

We should wait to implement this so we can continue to test geolocation from outside New York City.

**Comment by kdeloach** [comment]
I tried a few Philadelphia addresses and the search module returned no results.

**Comment by maurizi** [comment]
I think Rick is talking about the "Zoom to my current location" button, not
the address search.

On Thu, Feb 26, 2015 at 10:53 AM, Kevin DeLoach <notifications@github.com>
wrote:

> I tried a few Philadelphia addresses and the search module returned no
> results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/253#issuecomment-76202484>.
>



-- 
Michael V. Maurizi Jr
Software Developer
Azavea |  340 N 12th St, Suite 402, Philadelphia, PA
mmaurizi@azavea.com  | T 215.558.6190
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>

**Comment by kdeloach** [comment]
You're right, this is still an issue (or is it?).
