### ISSUE TITLE
Error: '/var/log/nyc-trees-app.log' isn't writable 

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#254]
After a fresh checkout and provisioned as development the debugserver script fails to run.

    > ./scripts/debugserver.sh 
    + vagrant ssh app -c 'sudo service nyc-trees-app stop || /bin/true'
    nyc-trees-app stop/waiting
    Connection to 127.0.0.1 closed.
    + vagrant ssh app -c 'cd /opt/app/ && envdir /etc/nyc-trees.d/env gunicorn --config /etc/nyc-trees.d/gunicorn.py nyc_trees.wsgi'

    Error: Error: '/var/log/nyc-trees-app.log' isn't writable [IOError(13, 'Permission denied')]

    Connection to 127.0.0.1 closed.

**Comment by kdeloach** [comment]
I tried manually deleting `/var/log/nyc-trees-app.log` and reprovisioning but got the same error.

**Comment by steventlamb** [comment]
I was able to work around this in development with 
`sudo chmod 777 /var/log/nyc-trees-app.log`

**Comment by kdeloach** [comment]
Fixed by #255
