### ISSUE TITLE
Debugserver doesn't reload when there are changes

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#256]
The gunicorn debuserver used to reload when there were Python script changes. Now, when provisioned as dev, I have to reload it manually.

This may be fixed by 91ade66037d8c110015c974aed3b0d85c1e44644.

**Comment by maurizi** [comment]
@kdeloach Is this fixed?

**Comment by steventlamb** [comment]
I had this issue for a spell and now it's fixed.

**Comment by kdeloach** [comment]
Verified fixed.
