### ISSUE TITLE
Add indexes for tiler cache busting

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#275]
We are using the `updated_at` field of several of our models (currently `Blockface` and `Survey`, but there will almost certainly be more) as a cache buster.  (see https://github.com/maurizi/nyc-trees/blob/3bcc33d8c993fc3211435d1e712030df7e5c457b/src/nyc_trees/apps/core/views.py)

We should add indexes to these fields to ensure they can be queried quickly.

**Comment by maurizi** [comment]
Our cache busters have moved here: https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/apps/survey/layer_context.py

**Comment by maurizi** [comment]
One index was added in https://github.com/azavea/nyc-trees/pull/1318, but we still need to add the others.

**Comment by kdeloach** [comment]
We should wait to do this until we optimize tiler performance, since the tables being queries may change
