### ISSUE TITLE
Create a friendly 413 page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#286]
Nginx is set to prohibit large uploads, returning a 413 to the browser. A response only a programmer could love

![screen shot 2015-01-09 at 6 14 56 pm](https://cloud.githubusercontent.com/assets/17363/5689839/8338f0a4-982b-11e4-9846-905ce7b3d71e.png)

If we can't easily return to the form from which the file was uploaded, we should at least redirect to a styled error page explaining why we rejected the request.

**Comment by maurizi** [comment]
We may not be able to make a nicer error message for this at the `nginx` level.

According to the `nginx` documentation (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size):
> Please be aware that browsers cannot correctly display this error.

**Comment by jwalgran** [comment]
Right. I am suggesting we configure Nginx to redirect to ``/file-too-large`` or something similar

```
server {
  ...
  error_page 413 /file-too-large
  ...
}
