### ISSUE TITLE
Wrap ``vagrant provision`` so that it exits with -1 if the VM is not running

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#297]
``vagrant provision`` is exiting with 0 if the VM is not running, which can lead to builds marked as "good" when the provisioner failed.

```
$ vagrant halt app
$ vagrant provision app
==> app: VM is not currently running. Please, first bring it up with `vagrant up` then run this command.
$ echo $?
0

**Comment by hectcastro** [comment]
Jenkins runs the execute shell step with `-xe` by default, which prevents the retry mechanism in `vagrant-up.sh` from doing its thing. When a failure occurs during provisioning, the cleanup execute shell step is running `vagrant halt` before the first retry can happen.

I'm trying to remedy this by reversing the default of `-e` with with `set +e`, which doesn't halt the script on first failure. Instead, the last line of the script determines the outcome. If all of the Vagrant provisioning retries fail, the conditional below will short circuit into a failure. If any of them succeed, then the status of the build will be determined by `test.sh`.

```bash
set +e

./scripts/vagrant-up.sh && ./scripts/test.sh 
```

**Comment by jwalgran** [comment]
That makes more sense. I was not sure why the VM stopped after the failure. Do you think we should still "correct" the way "vagrant provision" exits?

**Comment by jwalgran** [comment]
using ``vagrant reload`` takes care of this
