### ISSUE TITLE
Add cache header to tiles

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#303]
Tiles generated by Windshaft have a `cache_buster` argument in their URL based on the most recent updated date of the tables used to generate them.

This should allow us to cache every tile forever.

**Comment by maurizi** [comment]
@hectcastro This is done right?

**Comment by hectcastro** [comment]
Headers are in place. Not sure how the cache busting works though:

```bash
$ curl -I https://d3a6cg2duujf6d.cloudfront.net/1424975281/nyc_trees/progress/9/152/193.png
HTTP/1.1 200 OK
Content-Type: image/png
Content-Length: 334
Connection: keep-alive
Access-Control-Allow-Headers: X-Requested-With, X-Prototype-Version, X-CSRF-Token
Access-Control-Allow-Origin: *
Cache-Control: max-age=315360000
Date: Thu, 26 Feb 2015 19:18:40 GMT
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Server: nginx/1.6.2
X-Powered-By: Express
X-Windshaft-Cache: 59491
X-Cache: Miss from cloudfront
Via: 1.1 95f35fc8c27a19d2bdc2350557a8592e.cloudfront.net (CloudFront)
X-Amz-Cf-Id: ImKzqb199pu0O1wR6g3Hx3s_ZeR7W7DO6m0PqL5m4TerkuPTMp9fZQ==
```

**Comment by maurizi** [comment]
@hectcastro The first part of the URL, (what is in your example `1424975281`), is a unix-style timestamp of the maximum updated datetime of all the tables used in the SQL query used to generate the tiles.

I think we can close this.
