### ISSUE TITLE
Add styling to the map location search

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#308]
The markup is in the location_search.html partial
https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/apps/home/templates/home/partials/location_search.html

![screen shot 2015-01-15 at 11 42 03 am](https://cloud.githubusercontent.com/assets/17363/5763924/9b448b02-9cab-11e4-87a4-f67f81621b1d.png)

**Comment by jfrankl** [comment]
Closed by 69ef9e5f3309d2766bd8015426e636be3e5cb8f1
