### ISSUE TITLE
Event alert should turn gray when it's been consumed

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#315]
When an event you have RSVPd to is starting we show a red alert icon in header of all pages.

Once the user has "consumed" that alert it should turn gray. @jfrankl, should that be when the user:
* taps the icon, or
* closes the drop-down, or
* clicks the drop-down link to visit the page?

(For implementation, @maurizi suggests using session state rather than the database.)

**Comment by jfrankl** [comment]
Good question! Let's make the consumption happen when the user taps the
icon.

On Fri, Jan 16, 2015 at 11:17 AM, Rick Mohr <notifications@github.com>
wrote:

> When an event you have RSVPd to is starting we show a red alert icon in
> header of all pages.
>
> Once the user has "consumed" that alert it should turn gray. @jfrankl
> <https://github.com/jfrankl>, should that be when the user:
>
>    - taps the icon, or
>    - closes the drop-down, or
>    - clicks the drop-down link to visit the page?
>
> (For implementation, @maurizi <https://github.com/maurizi> suggests using
> session state rather than the database.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/315>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by maurizi** [comment]
We no longer show a red alert icon, s I think we can close this.
