### ISSUE TITLE
Event alert should appear/disappear even if user doesn't change pages

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#316]
This behavior was proposed by @jfrankl. Scenario:
* The night before an event you have TreesCount open in a browser page. There is no alert icon because the event is not starting soon.
* The next day you look at the same page (without reloading it) 45 minutes before the event. You should see an alert icon because the event is starting soon.

Implementation: we don't want all pages to poll the server constantly in case an alert is needed. @maurizi proposes that when we load a page we also load data for upcoming events, and use that to update alerts locally. That could potentially give wrong information if event times are changed at the last minute, but that seems unlikely.

**Comment by dboyer** [comment]
It would be great if we could do this, but it can fall in the "nice to have" category and wait until later for implementation if necessary.
