### ISSUE TITLE
What is the best way to set up the dev environment so that tiles are loadable by non-localhost

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#334]
When running the app in development on your workstation and browsing it on your mobile device, tiles do not load because the generated URLs for the tiler are 33.33.33.*. What is the best way to expose the tiler vm to the host network?

**Comment by maurizi** [comment]
You should be able to change the `TILER_HOST` setting in https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/nyc_trees/settings/base.py#L294 to be `localhost:7000` (it may need a leading `//`)

**Comment by kdeloach** [comment]
This should do the trick:

> NYC_TREES_TILER_IP=localhost:7000 vagrant provision app

**Comment by jwalgran** [comment]
Works great
