### ISSUE TITLE
Mappers may select a teammate who assisted them with mapping

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#335]
Refers to Task 28 in the scope - Support Team Mapping. A team can be no more than two people so the user entering the data can only note that one other person helped them with mapping.

**Comment by jwalgran** [comment]
Plumbing is ready for this feature to be implemented in the data collection app. The ``teammate`` field on ``Survey`` is where the assisting user should be saved.

**Comment by dboyer** [comment]
Great. Parks just confirmed that teams can be only two people so no need to add support for more people than two.

**Comment by dboyer** [comment]
A couple notes:

1. Any registered user can be selected from the drop down, even if they had not finished online training.  This would allow an interested person to create an account on the spot and participate, and get credit for the blocks mapped.  

Both the teammate and the user logged in get credit toward the achievement levels. If the teammate hasn't completed online training, they must do so before registering for a training event in the future and they must attend a training event before registering for a mapping only event. 

2. Users can select a teammate who did not RSVP for the event, but that teammate does not get credit for attending the event as part of reaching a certain achievement level.
