### ISSUE TITLE
Resizing the event edit page causes the event point to no longer be in the center of the mini map

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#337]
![screen shot 2015-01-21 at 11 29 20 am](https://cloud.githubusercontent.com/assets/17363/5842303/eb44c464-a160-11e4-913c-be036db22094.png)

**Comment by RickMohr** [comment]
What browser? Works for me on Chrome in Windows.

**Comment by jwalgran** [comment]
Sorry I clipped the screenshot. I am in the middle of testing a full provision so I can't retest at the moment, but it was either Chrome or Safari on OS X 10.10.1

**Comment by jwalgran** [comment]
I could not reproduce this.
