### ISSUE TITLE
When setting event location, crosshairs appear and disappear if you resize the window

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#338]
Some strange crosshair behavior if you resize the window. Lines appear and disappear.

Screencap
http://cl.ly/2D1k0y1K0t32/crosshair-strangeness-on-resize.mov
(in Chrome 39.0.2171.95 on OS X 10.10.1)

Works fine in Chrome on Windows 7

**Comment by jwalgran** [comment]
I could not reproduce this in Safari or Firefox.
