### ISSUE TITLE
Location search should show suggestions as you type

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#349]
I just checked out the map search feature. I am wondering if we could change it so it shows search results as you type instead of after clicking the "search" button. The way I often see this implemented is that the "results as you type" starts happening after 3 characters or something like that. I think that this pattern is more common for location searches.

**Comment by jwalgran** [comment]
Removing myself since, if we decide to implement this, I may not be the one who does it.

**Comment by dboyer** [comment]
I think this would be a nice feature. It's definitely an enhancement so if it's more than a couple points, I say we wait until we've finished all major features first.
