### ISSUE TITLE
Change DOM location of location search

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#350]
Currently the location search is nested in a div with the classes '''.leaflet-top''' and '''.leaflet-left'''. Those classes prevent me from positioning it correctly on the page. Would it be possible to bump it up a level?

**Comment by jwalgran** [comment]
I implemented the location search as a Leaflet "control" since it was the quickest way to get it to hover over the map. I can move the markup to wherever. Should it be a direct child of the map div?

![screen shot 2015-01-26 at 11 17 58 am](https://cloud.githubusercontent.com/assets/17363/5905438/570a6e02-a54d-11e4-91e5-8b7ab0485948.png)

**Comment by jfrankl** [comment]
Could you make it a direct child of the '''.leaflet-control-container'''?

**Comment by jfrankl** [comment]
Or direct child of the map div is fine too if that's easier.

**Comment by jwalgran** [comment]
We can try adding it straight to ``.leaflet-control-container``

**Comment by jwalgran** [comment]
@jfrankl When I move the search elements directly under ``.leaflet-control-container`` they hide behind the map tiles. Do you have a quick fix? If not, do you want to pair on this?

![screen shot 2015-01-27 at 4 09 25 pm](https://cloud.githubusercontent.com/assets/17363/5929229/0c97124c-a63f-11e4-96e0-f153e7770ee6.png)

**Comment by jfrankl** [comment]
I am guessing the quick fix is to add '''position: relative''' and
'''z-index: [something higher than the map, if the map has one]'''.

If that doesn't work, we should totally pair!

On Tue, Jan 27, 2015 at 6:13 PM, Justin Walgran <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> When I move the search elements
> directly under .leaflet-control-container they hide behind the map tiles.
> Do you have a quick fix? If not, do you want to pair on this?
>
> [image: screen shot 2015-01-27 at 4 09 25 pm]
> <https://cloud.githubusercontent.com/assets/17363/5929229/0c97124c-a63f-11e4-96e0-f153e7770ee6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/350#issuecomment-71748896>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jfrankl** [comment]
That will just make it not hidden but won't position it where you want.
