### ISSUE TITLE
Training: Add Training link to sidebar menu

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#351]
The "Training" item should link to ``/training/``

**Comment by kdeloach** [comment]
As of commit ab17b2efafb4a904fe629ff0b9127d7007b0ce55 it links to `/user/training`. I think this will change once d844cc73019bdbb8662bc2b0a1777493ec84bc57 is merged in.

**Comment by steventlamb** [comment]
This is fixed.
