### ISSUE TITLE
Add support for housing image uploads in a central store - Select/write appropriate Django storage backend - Probably not default to s3 storage

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#352]
It would be great to use the Boto backed Amazon S3 storage support referenced [here](https://django-storages.readthedocs.org/en/latest/backends/amazon-S3.html). It would be even better if the plugin works with IAM role credentials (since it is backed by Boto).

**Comment by hectcastro** [comment]
I tested read/write access to S3 via the credentials supplied by the IAM role on staging and production.

See also: https://github.com/azavea/nyc-trees/issues/727

**Comment by hectcastro** [comment]
Determine impact of altering the default storage option for Django and Watchman storage health checks.

See also: https://github.com/azavea/nyc-trees/pull/755

**Comment by jwalgran** [comment]
Want to prefer getting credentials from boto, rather than keys

**Comment by hectcastro** [comment]
It appears that JEST settled on [django-storages-redux](https://pypi.python.org/pypi/django-storages-redux/), the more popular fork of `django-storages`. It might be a good idea to settle on the same, unless there is another strong alternative.

I'm working on a patch to add IAM role support to this plugin and would like to pair with whoever takes this task on to test it before trying to contribute it back.
