### ISSUE TITLE
Blockface reservation: Double-tap to zoom map reserves a blockface

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#362]
On a touch device, double-tapping the map to zoom in, selects a blockface. Pinch-zoom and panning the map by touch work as expected.

**Comment by maurizi** [comment]
I think this is an issue on all of our maps.  Double tapping to zoom will select a blockface and zoom.

**Comment by kdeloach** [comment]
Nice-to-have, tricky to fix. Not an issue for Treecorder with crosshairs.
