### ISSUE TITLE
Blockface reservation - add visual indicator when you have reached your reservation limit

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#366]
You are no longer able to select blockfaces once you have reached your limit for reservations (currently 20 reservations).

The only indication of this is a "20 / 20" counter in the lower left, which may be too subtle to notice.

**Comment by dboyer** [comment]
The limit will likely decrease from 20. Waiting on feedback from Parks.

**Comment by jfrankl** [comment]
Not sure when it was added, but there is now a popup when someone tries to go over the limit:

![image](https://cloud.githubusercontent.com/assets/1809908/6232327/42796986-b699-11e4-805b-e17230209594.png)

**Comment by jwalgran** [comment]
Implemented in 881479ad03755e5510344483ddbedd0d4e3b70bd
