### ISSUE TITLE
Legend text does not appear on modal legend

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#368]
I'm not sure if this is as intended or not.

![legend1](https://cloud.githubusercontent.com/assets/4432106/5922848/d896225c-a61c-11e4-895e-f188e8fe9b25.png)

**Comment by kdeloach** [comment]
Not clear what this means.

**Comment by maurizi** [comment]
Compare the above screenshot to:

![image](https://cloud.githubusercontent.com/assets/1809908/5907154/b9203410-a56a-11e4-8788-2f0aa842cfe8.png)

The "Reservations" and the lorem ipsum text is not present.

**Comment by kdeloach** [comment]
I assumed this was by-design because it wouldn't fit on smaller screens.

**Comment by dboyer** [comment]
Ideally, we would have at least some text on the smaller screen, even if it just the first line. I can tell Parks that the first line may be all that shows on some smaller screens.

**Comment by maurizi** [comment]
When I talked to @jfrankl the impression I got was that he wants to try and fit all of the text on here on smaller screens (so this is in fact a bug, not by design).

**Comment by jfrankl** [comment]
I'm on this.

**Comment by jfrankl** [comment]
Turns out I need some help to get this to work. @RickMohr can we pair on this when you have some time?
