### ISSUE TITLE
Map is too big in desktop view on event detail page and group detail page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#370]
On a desktop browser, the map dominates the page.

![screen shot 2015-01-27 at 11 50 41 am](https://cloud.githubusercontent.com/assets/17363/5924685/e1a4468c-a61a-11e4-8a20-d44d81ec990c.png)

**Comment by RickMohr** [comment]
Seems to me it shouldn't be full-width in the desktop layout. It may suffice to move it inside one of the other containers, since it will be narrower. (Its height will be 40% of its width.)

**Comment by RickMohr** [comment]
We should apply the same solution to the group detail page.

**Comment by jfrankl** [comment]
@designmatty Let's chat before you take this on.
