### ISSUE TITLE
Action bar on "New Resevations" not visible

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#380]
![selection_052](https://cloud.githubusercontent.com/assets/43062/5943714/53c27de0-a6ef-11e4-957e-02dd48793ffc.png)

**Comment by maurizi** [comment]
This will be fixed (somewhat) by https://github.com/azavea/nyc-trees/pull/369

**Comment by kdeloach** [comment]
It's visible now, thanks.
