### ISSUE TITLE
No DEFAULT_FROM_EMAIL setting exists

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#392]
In the staging environment, this e-mail address needs to have an `azavea.com` domain. I'm not sure we have an e-mail address to use in the production environment, but when we do, it will need to be set with `DEFAULT_FROM_EMAIL` and be verified with Amazon SES.

**Comment by jwalgran** [comment]
The question for Parks is: what should the "from" address be for automated email sent from TreesCount?

**Comment by dboyer** [comment]
Parks is working on getting us an email address. They need to finalize it.

**Comment by jwalgran** [comment]
To bootstrap user testing, set ``DEFAULT_FROM_EMAIL`` to ``azaveadev@azavea.com``

**Comment by steventlamb** [comment]
@hectcastro This looks fixed, please confirm.

**Comment by hectcastro** [comment]
I left it open as a reminder that we still need to get an e-mail address from Parks and wire it up to the application and SES.

**Comment by steventlamb** [comment]
Got it

**Comment by dboyer** [comment]
Emailed confirmed -  treescount.help@parks.nyc.gov

**Comment by hectcastro** [comment]
Waiting for them to confirm via SES and then I'll wire up and test.
