### ISSUE TITLE
Set a specific registration link domain

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#393]
Right now it comes up at `example.com`:

```
Thank you for signing up for Trees Count!

Your username is work
Please click on this link to confirm your email address.

example.com/accounts/activate/****/

If you have additional questions or need help with your account, please email us at ...
```

**Comment by jfrankl** [comment]
We will need to get this sorted out before user testing. Right now, the link in this email doesn't work. We should probably set it to treescount.azavea.com for the user test.

![image](https://cloud.githubusercontent.com/assets/1809908/6217468/2bd12c44-b5e2-11e4-9dcb-4040ea89602d.png)

**Comment by jwalgran** [comment]
I updated the domain through the Django admin. Registration emails should have working links now

**Comment by jfrankl** [comment]
Yeah @jwalgran!

**Comment by jwalgran** [comment]
I think we will want to leave this open, because we will need to do it in production as well, once that stack is created.

**Comment by jfrankl** [comment]
That makes sense.

On Mon, Feb 16, 2015 at 2:00 PM, Justin Walgran <notifications@github.com>
wrote:

> I think we will want to leave this open, because we will need to do it in
> production as well, once that stack is created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/393#issuecomment-74556487>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by hectcastro** [comment]
Would be great to have this change codified somewhere so that we can apply it to new stacks. Something we could add to `setupdb.sh` maybe?

**Comment by jwalgran** [comment]
@hectcastro we can make setting up the site an idempotent command incorporated into ``setupdb.sh`` I think the idiomatic way to do this would be to write the DNS name for the app into ``/etc/nyc-trees.d/env`` during provisioning.  Where would you suggest we thread this in? I think it need to originate in the Jenkins job config, so our stage and prod deploys can have a different value.

**Comment by hectcastro** [comment]
Dug into this today. I don't know if adding the endpoint to the environment works because that prevents the same AMI from being used across multiple environments. I played around with a few different approaches, and finally came to a variable that needs to be set at the time `setupdb.sh` is run:

```bash
$ DJANGO_SITE_DOMAIN="treescount.foo.com" /opt/nyc-trees/scripts/aws/setupdb.sh
```

These steps would default to the production domain and be set by a Django management command that is called within `setupdb.sh`.

**Comment by jwalgran** [comment]
Maintaining an AMI that can be used in any environment is important. I like the simplicity of the "prod is default; can be overridden" approach.
