### ISSUE TITLE
Prevent setting any dates < now()

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#400]
As demonstrated in sprint review

**Comment by kdeloach** [comment]
This was caused by submitting an invalid start date.

**Comment by jwalgran** [comment]
Changing the title to reflect the fix we need

**Comment by steventlamb** [comment]
By my search, these are the fields in question:
`Event.begins_at`
`Event.ends_at`
`BlockfaceReservation.expires_at`
`BlockfaceReservation.canceled_at`
`User.requested_individual_mapping_at`

Some are more obvious candidates than others, but some are unclear. I'm also not sure if we should lock down any of these wholesale - the django admin is for trusted users. What if they have to fix something?

@kdeloach which if these fields did you mean by 'invalid start date'?

**Comment by kdeloach** [comment]
I submitted a start date like `2/44/1111` or something along those lines when I was adding a new event.

**Comment by steventlamb** [comment]
Got it, thanks. Does anyone know why the original title was `Error Adding a Reservation`? Is this a compound issue?

**Comment by dboyer** [comment]
That was the original title because I entered the issue really quickly during/right after sprint review when we didn't have info on what caused the problem.
