### ISSUE TITLE
Integrate home page design

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#403]
Not sure if this is development or @jfrankl but it would be ideal to have at least the big pieces of the home page in place, even if the progress counts aren't hooked up.

**Comment by RickMohr** [comment]
@dboyer, how is this different from #404?

**Comment by dboyer** [comment]
The home page and dashboard are two different pages. The home page (p3 of wireframes) is what users see upon first visiting the site or if they aren't logged in. The dashboard (p13-16 of wireframes) is what registered users see.

**Comment by jwalgran** [comment]
The home page and dashboard are implemented and styled
