### ISSUE TITLE
Set up dashboard to match wireframes

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#404]
Right now, it just shows training. Perhaps that's fine if the person isn't trained, but we should have the major pieces on the dashboard as shown on the wireframe.

**Comment by RickMohr** [comment]
* reservations
* achievements
* upcoming events
* contributions
* groups
p.16 of wireframes

**Comment by dboyer** [comment]
Coordinate with @jfrankl on this issue. Not sure who should implement the page.

**Comment by jwalgran** [comment]
Fixed by #452, #472
