### ISSUE TITLE
Move logout for logged in user

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#411]
The login/register links should be in the top right of the navigation when a user is not logged in. When a user is logged in, the logout link should be in the slideout side navigation. See here:

![image](https://cloud.githubusercontent.com/assets/1809908/5980916/41c483be-a883-11e4-9770-2996026d9cab.png)

![image](https://cloud.githubusercontent.com/assets/1809908/5980921/48390936-a883-11e4-94be-ced325abcf1f.png)

**Comment by RickMohr** [comment]
It looks good to me. @dboyer, any adjustments to the wording for these three cases?

If user has not requested independent mapping status for a group (no change from current):

![capture](https://cloud.githubusercontent.com/assets/2162993/7729280/efc9b8da-fee1-11e4-8a48-ef275472dfe1.PNG)

If user's request has not been acted on:

![capture](https://cloud.githubusercontent.com/assets/2162993/7729321/1f372de6-fee2-11e4-8128-f164cea5e665.PNG)

If user has been approved (or if they are the group admin):

![capture](https://cloud.githubusercontent.com/assets/2162993/7729340/49653842-fee2-11e4-9a9b-3f47eba9f6ee.PNG)
