### ISSUE TITLE
Responsive styling issue on events list page

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#412]
The List/Map tabs lose their padding when the screen width is 768-920px.
![event-list](https://cloud.githubusercontent.com/assets/4432106/5981759/ff3ab1c8-a88a-11e4-8656-d1b9a5beec71.png)

**Comment by jfrankl** [comment]
Fixed by b0479d16e3b5888eb50e20c09e22d5b28f3bc058
