### ISSUE TITLE
Opening navigation window cuts off some functionality on page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#414]
I opened the navigation while on the user settings page and then clicked the Emails tab. Since the navigation is open, my screen doesn't show the buttons to save changes to the email settings. The solution is to close the navigation, but I don't think that will be obvious to every user.

![navigation](https://cloud.githubusercontent.com/assets/516764/5982864/cb75dc18-a895-11e4-9af9-5b8d1e77c70a.png)

**Comment by jfrankl** [comment]
Here's how I want this to work:

When the menu is open, clicking on the non-menu part of the page should close the menu. In addition, we could possibly add an overlay to make it more clear that the non-menu part of the page is non-functional while the menu is open.

I will take a shot at implementing this.

**Comment by jfrankl** [comment]
@dboyer,

I believe this is fixed now. Please confirm.

**Comment by dboyer** [comment]
Yep, looks good.
