### ISSUE TITLE
When showing territory on group detail page, should we show mapped/unmapped blockfaces in different colors?

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#435]
Benefit: see at a glance how the group is doing (rather than having to go find it on the progress page)
Drawback: it has to either be dead obvious what color means "mapped" and what color means "unmapped" (e.g. red/green) or else we need a legend on that little map.

**Comment by dboyer** [comment]
Good question. Let's not implement that for now but keep it in mind if user testing or internal testing shows confusion about the map on the group page.

**Comment by maurizi** [comment]
@dboyer Think we can close this now?

**Comment by dboyer** [comment]
Yes
