### ISSUE TITLE
Privacy button on the side bar does not link to anything

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#436]

**Comment by dboyer** [comment]
The privacy button on the user profile page also doesn't link to anything. Looks like you can only get to the privacy settings by clicking "settings" in the dashboard and then selecting the privacy tab.

**Comment by steventlamb** [comment]
@dboyer The privacy button on the user profile looks to be linked to a non-existent privacy popup, which sounds different than the privacy tab. Maybe this is supposed to link to same place as the 'Privacy Policy' link, on the sidebar, which also currently does nothing?

I'm opening a PR to handle the privacy button the sidebar only. It will be a very simple fix to bind these other controls to it as well, if desired.

**Comment by RickMohr** [comment]
It looks like the privacy pop-up was mistakenly deleted in this template reorganization:
https://github.com/azavea/nyc-trees/commit/fcd54630d7156ccb8934b125f8228a003da83b95#diff-a021a948cbde19d1349cfea855f17517L82

I expect it will still work if restored.

**Comment by dboyer** [comment]
@steventlamb The privacy popup should only be shown when the user clicks the privacy button directly from their user profile page. The privacy link in the navigation can go to the privacy tab on the settings page.
