### ISSUE TITLE
Change the message at the top of /training/ when all steps are complete

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#443]
When you have all your checkmarks, the header should no longer say "almost there"

![screen shot 2015-02-03 at 5 48 44 pm](https://cloud.githubusercontent.com/assets/17363/6032979/215870e8-abcd-11e4-85c5-35f38e193c73.png)

**Comment by dboyer** [comment]
This text isn't final yet so we may want to wait on this issue.

**Comment by steventlamb** [comment]
#450 adds support to easily correct the text when we're ready

**Comment by kdeloach** [comment]
What text do we want to display here?

**Comment by dboyer** [comment]
Waiting for Parks on this.

**Comment by dboyer** [comment]
After completing online training, the text should say:

Text under Training (on left side of screen when on desktop or very top of screen when on mobile):
Congratulations on becoming a trained volun<b>treer</b>!

New header to replace Training Complete:
Online Training Complete!

New body text under Online Training Complete:
Visit the dashboard (link to dashboard) to explore the site and start mapping!

The next step after completing online training is to sign up for a training event where you will practice what you've learned in the field! Sign up for training events here. ("sign up...here" linked to events page)

You can also download a PDF of the training materials here. (here linked to PDF - saved in \data\Training_Materials on fileshare but may change)

**Comment by dboyer** [comment]
#1189 is part of this

**Comment by steventlamb** [comment]
The provided text appears not to account for the recently added:

> You can also visit the Groups page to learn more about mapping opportunities and follow groups for event information.

**Comment by steventlamb** [comment]
This text looks good. Is it ok that the 'continue your training' version looks a little bare?

![screenshot from 2015-04-15 17 10 26](https://cloud.githubusercontent.com/assets/1699455/7169320/5b59b048-e392-11e4-8dc4-70719553e4c7.png)

**Comment by dboyer** [comment]
Totally fine.

**Comment by dboyer** [comment]
@steventlamb On staging, I'm seeing the new text on the training complete page, but there's no longer any content in the right column including the different sections with check marks indicating they are completed.
