### ISSUE TITLE
"Create an Account" button on the homepage should link to  /accounts/register/

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#446]

**Comment by steventlamb** [comment]
Can't reproduce. All account links on this page look correct:
![screenshot from 2015-02-04 15 29 02](https://cloud.githubusercontent.com/assets/1699455/6049060/a13dab74-ac82-11e4-849a-ca72c99ca569.png)
Grepping the project I can't find 'create an account'.

**Comment by jwalgran** [comment]
https://github.com/azavea/nyc-trees/blob/d1b676e2886a5b35557c41f43a8ec20b4f589590/src/nyc_trees/apps/home/templates/home/partials/home_public.html#L34
![screen shot 2015-02-04 at 4 42 20 pm](https://cloud.githubusercontent.com/assets/17363/6052160/d3e8ea70-ac8c-11e4-8e49-6eef0bcf80d1.png)

**Comment by steventlamb** [comment]
Doh. Stale checkout.
