### ISSUE TITLE
Progress Map action bar

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#456]
The progress map should have an action bar at the bottom, similar to the event map, that shows information about a selected block face.

- Available: you would see a button that would take you to the reservations page
- Already mapped: "Mapped by [group name]" or if no group "Mapped by an individual mapper"
- Unavailable: "This is reserved by `[group name]` (with link to group page)" or "This is reserved by an individual mapper"

When the user is zoomed far out, the action bar should have a message like "zoom in to select a block face".

**Comment by dboyer** [comment]
This may be too much to tackle before user testing, but it is confusing that currently nothing happens when you click a segment on the progress map.

**Comment by jfrankl** [comment]
Yeah, it would be great if something happened whether it goes in the action bar (ideal) or is just a standard leaflet popup (acceptable).

**Comment by maurizi** [comment]
Fixed by https://github.com/azavea/nyc-trees/pull/620
