### ISSUE TITLE
Text on events page not showing on mobile device

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#479]
I can see the placeholder text (Take a look at upcoming events...) on both the List and Map tabs when viewing the page on desktop. I can't see the text when viewing on mobile.

**Comment by jfrankl** [comment]
Deb, I think this is the same as #368. This placeholder text should appear with the content in the legend. Are you okay with me merging these issues?

**Comment by dboyer** [comment]
@jfrankl  Sure, that sounds fine.

**Comment by jfrankl** [comment]
See #368.
