### ISSUE TITLE
Need to support searching/filtering by group on Events page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#480]
I defer to @jfrankl on how to handle this, but there needs to be some option for filtering the events by group.

**Comment by kdeloach** [comment]
@dboyer, @jfrankl, for simplicity how about just directing users to the group page?

**Comment by dboyer** [comment]
@kdeloach How do you see that working? Just a line of text at the top of the page? Or would the group name become a link to that group's detail page. The latter could be difficult considering the entire event is currently a link that clicks through to the event detail page.

**Comment by jfrankl** [comment]
I think what Kevin's getting at is that someone can already see a group's events by going to their group page. I don't think we need to duplicate that functionality on the event page.

**Comment by jfrankl** [comment]
Right now we have a little box at the bottom of each individual event that connects users to that group's page to see more of their events. I feel like a similar style of message could work well at the bottom of this page. 

What this message should convey: "Looking for events for a particular group? Check out their group page."

![image](https://cloud.githubusercontent.com/assets/1809908/7349750/4831149e-ecc9-11e4-9a68-d121e97aa3b1.png)

**Comment by dboyer** [comment]
True, but there's no way for the user to know that from the events page. We would assume someone realizes they can see future and past events for a group from the group's page rather than the event's page, which isn't entirely intuitive.

**Comment by dboyer** [comment]
A message on the events page sounds great. The page on production is already lengthy so I'm not sure the bottom of the page makes sense. Perhaps just a line added to the top text.

**Comment by jfrankl** [comment]
Question: currently, what events do we show under browse events? Just events for groups that a user is following?

**Comment by dboyer** [comment]
Every event in the system. The events for the group the user is following is what populates the recommended section of the events tab on the dashboard.

**Comment by kdeloach** [comment]
My account was logged in during sprint review. May want to ask @maurizi for the meaning behind this.

**Comment by maurizi** [comment]
This was @RickMohr's idea I believe

**Comment by RickMohr** [comment]
@jfrankl summarized what we were thinking during post-RRP planning -- help them find events for a particular group using mechanisms we already have rather than creating new ones. Something like:

To find events sponsored by a particular group visit the group's page, accessible via [Groups](http://google.com).
