### ISSUE TITLE
No date or time picker when adding a new event on staging

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#484]

**Comment by maurizi** [comment]
@dboyer What browser was this on?

**Comment by dboyer** [comment]
This was in Firefox. Looks like it is working in Chrome.

**Comment by maurizi** [comment]
In Chrome we rely on the date/time pickers built-in to the browser, so it makes sense that it works in Chrome.

In desktop Firefox we use an external library.  It must have gotten broken somehow.

**Comment by dboyer** [comment]
It's also broken in IE. We need to support at least the most recent version of IE since group admins may have varying levels of technical knowledge.

**Comment by steventlamb** [comment]
Strange, I can reproduce this locally by hitting staging, but not my development environment, using the same version/install of firefox. I'd be surprised if this is some kind of provisioning issue Any chance this was fixed recently?

**Comment by maurizi** [comment]
@steventlamb maybe its an issue with the URL for the date/time shim loaded
by Modernizr's yepnope library?

Staging uses the production JS bundles, so it does differ from development
in what URLs we use for JS files

**Comment by steventlamb** [comment]
Thanks for the hint. I'm not seeing any network failures but I'll dig a little harder.
