### ISSUE TITLE
Styling needed on registration page

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#486]
1) Checkboxes on same line as label
2) Is the "terms of use" link the correct color?

![image](https://cloud.githubusercontent.com/assets/2162993/6155816/71be01ba-b203-11e4-8441-6f4e101aaf65.png)

**Comment by jfrankl** [comment]
This needs some changes that I can't figure out how to make (it's not in the template files, from what I can see).

- Each of the text fields should have class ```.form-control``` added to it.
- The lines with checkboxes should change so the checkboxes appear before the text. The semi-colon at the end of the text should change to period.

Example: [x] I am over 13 years old.

**Comment by jfrankl** [comment]
```.form-control``` is needed on input fields across the entire application, actually. Seems like these fields are being generated by django.

**Comment by kdeloach** [comment]
Sorry for the confusion, the templates for the registration pages are here: `src/nyc_trees/templates/registration`.

**Comment by jwalgran** [comment]
If it is a big-hastle to dig into the Django input tag rendering, we always have the option of running some JS on page load to add the class. The JS solution has the downside of a potential flash of unstyled content, but may be a reasonable tradeoff.

**Comment by maurizi** [comment]
It doesn't look too hard to add a class for everything using `floppyforms`.
Getting the registration pages to use `floppyforms` is a little harder, but doable.

**Comment by kdeloach** [comment]
I vote to take the generated HTML and put it directly into the template.

**Comment by jfrankl** [comment]
@maurizi,

The select fields need ```.form-control``` too. I don't think there are many of them, but I noticed them on the Optional Information page:

![image](https://cloud.githubusercontent.com/assets/1809908/6217435/d4d58c82-b5e1-11e4-8fd9-a3d11fe84151.png)

**Comment by maurizi** [comment]
@jfrankl Noted.  I'm going through trying to add `form-control` to our input/select elements everywhere.

It may need some additional design work once I'm done.

**Comment by maurizi** [comment]
@jfrankl Once #571 is merged I think you should be able to take care of the remaining styling issues.

**Comment by jfrankl** [comment]
I'm not going to be able to look at this until tomorrow. If you need to
have it merged before then please assign it to someone else.

On Mon, Feb 16, 2015 at 4:17 PM, Michael Maurizi <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> Once #571
> <https://github.com/azavea/nyc-trees/pull/571> is merged I think you
> should be able to take care of the remaining styling issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/486#issuecomment-74573776>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>
