### ISSUE TITLE
Profile page: Link is same color as surrounding text

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#489]
The "Make your profile public!" link should not be the same color as the other text
![image](https://cloud.githubusercontent.com/assets/2162993/6156091/1dca3c98-b205-11e4-82b0-6907865bd3cb.png)

**Comment by RickMohr** [comment]
Also a problem on login page:
![image](https://cloud.githubusercontent.com/assets/2162993/6157262/fc625910-b20d-11e4-9632-12763906b503.png)

**Comment by jfrankl** [comment]
Closed by 1942a8060bbbd1d030598878d048914ed2ec6902
