### ISSUE TITLE
Make favicons including iphone/android app sized

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#502]

**Comment by jfrankl** [comment]
@designmatty We've had success with this tool in the past: http://realfavicongenerator.net/

**Comment by designmatty** [comment]
@jfrankl Thanks. There are about 20 different files to choose from. Should all of them be uploaded or just a certain few?

**Comment by jfrankl** [comment]
@designmatty and I just chatted about this in person. He's going to try to use just a few icon sizes and test them on latest and older iOS and Android devices.

**Comment by dboyer** [comment]
Let's use this for now, but I'll need to check with Parks since there are branding rules about using the Parks logo without NYC Parks underneath it.

**Comment by dboyer** [comment]
Parks approved using their logo as the icon, even though it doesn't have NYC Parks underneath.
