### ISSUE TITLE
The sidebar needs to be scrollable so all options are accessible on a small screen

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#503]
![screen shot 2015-02-12 at 8 48 01 am](https://cloud.githubusercontent.com/assets/17363/6170749/fa7043ac-b293-11e4-961c-9f1ca171a5da.png)

**Comment by jfrankl** [comment]
@jwalgran, I think this is fixed now. Just tested on iOS, Chrome, and IE9.
