### ISSUE TITLE
What content should be displayed in the black circle on the sidebar? Should it be removed?

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#504]
![sidebar-pic](https://cloud.githubusercontent.com/assets/17363/6170783/34401b7a-b294-11e4-8496-14502721c0f6.png)

**Comment by dboyer** [comment]
I believe that is where your achievement badge goes.

**Comment by jwalgran** [comment]
In the case of multiple achievements, which one do we show here?

**Comment by jfrankl** [comment]
I believe we decided to show the most recent, but I'm not sure why I think
that. Showing the one that you're closest to completing makes sense too.
Deb, do you have a preference, or you want to ask Parks?

On Thu, Feb 12, 2015 at 1:06 PM, Justin Walgran <notifications@github.com>
wrote:

> In the case of multiple achievements, which one do we show here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/504#issuecomment-74120468>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
My understanding is that users can only have one achievement at a time as they're going to be somewhat linear (mapped X number of blocks, etc). We would show the most recent one they've achieved. Let's leave this for now as I don't have the achievements from Parks yet.

**Comment by jfrankl** [comment]
We're going to remove this!
