### ISSUE TITLE
Sidebar links are not clickable in Mobile Safari and Desktop Safari

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#505]
In the movie I am tapping two different sidebar items. The sidebar disappears but the new page does not load.

http://cl.ly/3d3F083m2P41/tapping-sidebar-items-on-iphone-4s.mov

**Comment by jwalgran** [comment]
Reproducible in the iOS simulator too

**Comment by dboyer** [comment]
I'm not seeing this issue on android.

**Comment by jwalgran** [comment]
Reproducible on desktop Safari too

**Comment by jwalgran** [comment]
Ah. There is an overlay that is most likely catching the clicks before they get to the anchor tags.

![screen shot 2015-02-12 at 11 19 41 am](https://cloud.githubusercontent.com/assets/17363/6173980/27beff14-b2a9-11e4-9652-4e1e048cc6c5.png)

**Comment by jwalgran** [comment]
@jfrankl need an assist on this one. I can't figure out why safari is extending ``overlay-menued`` over top of the ``header`` tag and not constraining it to the ``right-content`` div

**Comment by jwalgran** [comment]
Adding  ``left: 30rem`` to ``overlay-menued`` fixes it, but I am not sure if that is the right bandaid.

**Comment by maurizi** [comment]
Is this fallout from #463?

**Comment by jwalgran** [comment]
I don't think so, there is an overlay to catch non-sidebar clicks, and Safari is rendering it differently than everyone else. I played with the z to no effect.
