### ISSUE TITLE
Revise colors on progress map

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#511]
Try dark green for "mapped by you".

Maybe remove purple.

**Comment by jfrankl** [comment]
![image](https://cloud.githubusercontent.com/assets/1809908/6176105/0e20235a-b2ca-11e4-9eb4-74f711d29035.png)

![image](https://cloud.githubusercontent.com/assets/1809908/6176231/182f478a-b2cb-11e4-8f87-f5b985347559.png)

A couple of ideas I'm trying out.

**Comment by jfrankl** [comment]
![image](https://cloud.githubusercontent.com/assets/1809908/6177199/7568992c-b2d2-11e4-96cf-693f364d8733.png)

**Comment by jwalgran** [comment]
I like this color scheme. Much improved over the previous palette.
