### ISSUE TITLE
Put new individual mapper workflow in place

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#517]

**Comment by RickMohr** [comment]
1. User completes online training and in-field training event

2. User attends another training or mapping event 

2. After attending those two events (one training and one training or mapping), a "request individual mapper status" button appears on their user profile page with some text describing what this is. We do not need to put up any notification on the dashboard about this button.

3. Users clicks the button and automatically is approved as an individual mapper

4. After clicking the button, the user is immediately taken to a page (maybe this is a pop-up?) that says "you've been granted individual mapper status! learn more!" with a page of instructions on reservations. They then can click through to the reservations page. 

5. Parks staff can rescind individual mapper status by unchecking the individual mapper box on that user's page in the admin interface.

**Comment by kdeloach** [comment]
Should the reservations page be accessible for non-individual mappers? What should happen when they click Reservations in the sidebar, and what should happen when they try to create a New Reservation?

**Comment by jwalgran** [comment]
I would suggest that the "Reservations" sidebar item is hidden if you are not an individual mapper (much like the reservations section on the dashboard/profile). I would want a second on that from Deb/Parks before committing to it.

**Comment by jfrankl** [comment]
Number 3 on Rick's list above should also appear on the dashboard, since that is where a user will find out about ways they can engage with the tree census (follow a group, join an event, request individual mapper status).

**Comment by kdeloach** [comment]
Since the dashboard shares a partial template with the user profile page, this button appears in both places.

![selection_077](https://cloud.githubusercontent.com/assets/43062/6220295/d17aee1c-b602-11e4-9bb6-11f83be37d30.png)

**Comment by kdeloach** [comment]
@jfrankl Can we close this?
