### ISSUE TITLE
403 Error when user RSVPs to Training Event when online_training_complete is False

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#521]
The RSVP button should probably forward to either the training page or a page with instructions on how to complete field training.

**Comment by maurizi** [comment]
.... Shouldn't they be able to attend a *Training* event when `field_training_complete` is False?  That's the only way to get `field_training_complete` set to True, right?

**Comment by kdeloach** [comment]
I *think* a user must complete the quiz before RSVP-ing to a training event (online training).

**Comment by kdeloach** [comment]
Sorry, inaccurate issue title, updating now.
