### ISSUE TITLE
Tab/hash list need to be implemented for "All Events" page

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#523]
Clicking All, Mapping, or Training tab should result in a hash change so we can link directly to that tab.

URL: [http://localhost:8000/event/](http://localhost:8000/event/)

**Comment by steventlamb** [comment]
I don't think this is going to be a quick fix - these are not tabs in the bootstrap sense, so we don't get that behavior for free from tabhash. Is this required for a specific feature?

**Comment by kdeloach** [comment]
Kind of. There's at least one page in the app that likes directly to the training events tab. Click "Attend a training event".

[http://localhost:8000/training/instructions](http://localhost:8000/training/instructions)
