### ISSUE TITLE
Events map view shows large dots and is not zoomable

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#535]
![screen shot 2015-02-13 at 3 35 22 pm](https://cloud.githubusercontent.com/assets/17363/6196510/074fe00c-b396-11e4-974a-c251b49fb53a.png)

**Comment by jwalgran** [comment]
The screenshot is from Chrome. In Firefox, the page starts out like the screenshot, but automatically zooms in a strange way. Screencast: http://cl.ly/1N3s0I181B2n/firefox-event-map-auto-zoom.mov

**Comment by dboyer** [comment]
@jwalgran I'm no longer seeing this issue.

**Comment by jwalgran** [comment]
I am not seeing it either. I see the same auto zoom behavior as I do in firefox.

**Comment by jwalgran** [comment]
This still happens sometimes. Needs more investigation.

**Comment by maurizi** [comment]
I've encountered this (sometimes) in firefox as well.

**Comment by jwalgran** [comment]
Rather than track down the JS issue, it may be better to add the events extent to the event map div in the Django template.

**Comment by steventlamb** [comment]
Grabbing this for now because I'm looking at another zoomy map issue (#512)

**Comment by RickMohr** [comment]
@steventlamb, let me know if you need more details on how to "add the events extent to the event map div". (Or look at how the group detail page does it.)
