### ISSUE TITLE
Swipe to close menu

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#554]
Would be great if a user could swipe to close the menu. Could a developer help with this?

**Comment by kdeloach** [comment]
If there's no swipe functionality in bootstrap, we may be able to utilize jQtouch, which is a dependency we will likely be adding for the TreeKIT app.

**Comment by jfrankl** [comment]
From what I can find, bootstrap doesn't support swipe.

On Mon, Feb 16, 2015 at 2:03 PM, Kevin DeLoach <notifications@github.com>
wrote:

> If there's no swipe functionality in bootstrap, we may be able to utilize
> jQtouch, which is a dependency we will likely be adding for the TreeKIT app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/554#issuecomment-74556939>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
I second this. I instinctively try to swipe close the navigation even though I know it doesn't work.

**Comment by jwalgran** [comment]
I know zero about this, but it looks nice nice: https://github.com/Mango/slideout
