### ISSUE TITLE
Show reservations page to all users

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#556]
It looks like the reservations page doesn't appear in the navigation unless you have individual mapper privileges. The page should be visible to everyone but only approved individual mappers can make reservations. It's a way to encourage people to learn more about individual mapping and see reservations.

**Comment by kdeloach** [comment]
This was a misunderstanding on my part. Fixing now.

**Comment by jwalgran** [comment]
My bad. I think I said "hide it"
