### ISSUE TITLE
Nothing happens when user clicks request individual mapper status on group page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#560]
Is this feature finished? trying to determine whether or not we can include it in user testing

**Comment by kdeloach** [comment]
I was not aware that button existed, I'll wire it up now. You can also request group mapper status via the New Reservations page.

![selection_076](https://cloud.githubusercontent.com/assets/43062/6218402/7c4c9f00-b5ec-11e4-99f8-c74631f294e1.png)
