### ISSUE TITLE
Legend is incorrect on Reservations page

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#565]
On the Reservations page the legend indicates 5 categories, but we're only showing "Reserved by you". We should only show 1 category on the legend.

**Comment by dboyer** [comment]
Connected to #566

**Comment by kdeloach** [comment]
We should verify if this has been resolved by #594.

**Comment by jwalgran** [comment]
@steventlamb Sorry I stepped on you in #594.

**Comment by steventlamb** [comment]
np, reassigning to you
