### ISSUE TITLE
Blank "Reservations" map is confusing

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#566]
When a user first sees the Reservations page it shows no blockfaces. That is confusing since it's not clear that the page shows only the user's reservations.

Possible solutions:
* Call it the "My Reservations" page or make the page intent clear in the text
* Show other blockfaces in gray
* Include a "You have no reservations yet" message

**Comment by dboyer** [comment]
@jfrankl and I are discussing this now.

**Comment by jfrankl** [comment]
Let's show other blockfaces in gray.
