### ISSUE TITLE
Reservations page should zoom to the user's reservations

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#567]

**Comment by kdeloach** [comment]
I spent a few hours trying to do this without any luck. I couldn't figure out how to get the bounding box of blockfaces, because we store them as `MultilineStringField`.

**Comment by jwalgran** [comment]
It sounds like [GeoQuerySet.extent](https://docs.djangoproject.com/en/1.7/ref/contrib/gis/geoquerysets/#extent) should get you what you need

**Comment by RickMohr** [comment]
The group detail page has an example of doing this. Get the extent in Django, put it as a data attribute on the map element, and the map module will zoom to it automatically.

**Comment by kdeloach** [comment]
Ah, I must have been creating the queryset incorrectly, because `extent` wasn't available.

**Comment by maurizi** [comment]
Fixed by #662
