### ISSUE TITLE
Reservations page: "New" button gives 403 for non-individual-mapper

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#578]
(Once we re-enable the "Reservations" link for non-individual mappers)

Clicking "New" gives a "403 Forbidden" error page.

How shall we help people learn how to get trained (if they're not) and become an individual mapper?

**Comment by dboyer** [comment]
I'll need to get the exact text from Parks. For now, let's show a message saying: Only approved individual mappers can reserve block segments.

**Comment by kdeloach** [comment]
Refs #556
