### ISSUE TITLE
Show group and event content on dashboard even if the user doesn't have any

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#580]
If the user isn't following any groups, we should show a block of text with 2–3 sentences about groups and a link to the group page so they can select/find groups.

If the user isn't RSVPed for any events or doesn't have any upcoming events, we should show a block of text with 2–3 sentences about events with a link to the events page.

**Comment by dboyer** [comment]
Use this text:

Join local groups and community organizations across the city to map trees. Browse through the list of groups to find contact info or follow a group to learn about upcoming events. 

Browse our list of events and sign up to join local groups to count trees.

**Comment by jwalgran** [comment]
@dboyer I think this can be closed now that the logged in home page has been overhauled. Agree?

**Comment by dboyer** [comment]
Sure.
