### ISSUE TITLE
Individual mappers checkbox selection doesn't match actual value on group admin

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#593]
Seems like this checkbox value is no longer being populated correctly. If you mark it checked, then come back to this screen, it is still unchecked.

![image](https://cloud.githubusercontent.com/assets/43062/6220785/93eeb8ac-b608-11e4-8018-1e25fb2af497.png)

**Comment by dboyer** [comment]
I'm seeing this too @kdeloach. Putting into user testing.
