### ISSUE TITLE
Counter on home page has a higher z-index than the header

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#596]
![screen shot 2015-02-16 at 4 33 28 pm](https://cloud.githubusercontent.com/assets/17363/6220947/a110b67a-b5f9-11e4-8388-d312cf0c4d95.png)

**Comment by jfrankl** [comment]
Fixed by 04da8d922b8fcdff3a8116bba2921692ff15a396

**Comment by jfrankl** [comment]
![image](https://cloud.githubusercontent.com/assets/1809908/6232426/e14bc50e-b699-11e4-817d-a969433d5ecd.png)
