### ISSUE TITLE
Should clicking the logo in the header link to the homepage/dashboard

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#598]

**Comment by dboyer** [comment]
Let's not link it for now.

**Comment by jfrankl** [comment]
I vote for linking it. I think that's the expected behavior. Will also give people a quicker way to return back to the dashboard instead of expanding the menu.

**Comment by kdeloach** [comment]
I have definitely clicked the header more than once trying to return to the Dashboard.

**Comment by jfrankl** [comment]
Fixed by #1022
