### ISSUE TITLE
Need to think through image change UX on group admin

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#600]
![image](https://cloud.githubusercontent.com/assets/1809908/6223232/52d43e58-b632-11e4-845f-bf1bfe90b31f.png)

**Comment by designmatty** [comment]
Maybe we could do something along these lines... What do you think @jfrankl? 
![screen shot 2015-03-13 at 10 14 18 am](https://cloud.githubusercontent.com/assets/1928955/6639886/d2e6d3ea-c969-11e4-9403-e5bedfe715ed.png)

**Comment by jfrankl** [comment]
We'll need a develop to help us implement this.
