### ISSUE TITLE
Start Mapping button goes to bad link

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#604]
On my VM, when I finish adding new reservations, the Start Mapping button takes me to /survey/, which throws a 403 error. I believe this should direct the user to /blockface/.

![image](https://cloud.githubusercontent.com/assets/1809908/6229939/a22656ce-b689-11e4-99d5-eefaf736ac59.png)

![image](https://cloud.githubusercontent.com/assets/1809908/6229944/a74645d8-b689-11e4-8086-16e95d13399e.png)

**Comment by maurizi** [comment]
I wired up "Start Mapping" to go to the (yet to be implemented) "Choose a block to survey" page.
We can definitely change it though if thats not right.

Should we remove the *other* link to `/blockface` ("Check the Reservations Page")?

**Comment by jfrankl** [comment]
Oh, I'm sorry, I misunderstood the Start Mapping button. I think this is correct.

**Comment by dboyer** [comment]
That is correct. As a side note, however, we probably need a "start mapping" button the reservations page as users may be making their reservations and then mapping later. Thoughts, @jfrankl ?
