### ISSUE TITLE
Style needed for reservations instructions page

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#610]
This is the page shown to non-individual mappers when they click "Reservations" in the sidebar nav.

[http://localhost:8000/blockface/reservations-instructions/](http://localhost:8000/blockface/reservations-instructions/)

![image](https://cloud.githubusercontent.com/assets/43062/6232420/d2259e2e-b699-11e4-82a1-3d23777a2c09.png)

**Comment by jfrankl** [comment]
Fixed by #763

![image](https://cloud.githubusercontent.com/assets/1809908/6876147/e9d50d4c-d49a-11e4-843e-76fca5a4b83b.png)
