### ISSUE TITLE
Progress map location search box scrolls offscreen on iPhone 4s with iOS 8

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#612]
At our last sprint review, focusing the search text box made it scroll to the top of the page

Screencast: http://cl.ly/3u2U3J1y3g0G/seach-box-scrolls-offscreen-on-ios.mov

**Comment by jwalgran** [comment]
@jfrankl do you have any wisdom to share on this issue. I have a hunch it is related to recent style overhauls.

**Comment by jfrankl** [comment]
Odd. That doesn't happen on iOS7, but I do get it on iOS8 on the Progress
Map. It doesn't happen on any of the other maps from what I can tell.

Unfortunately, no additional insight for right now. That's definitely a
significant bug that I'd be glad to fix, but I won't be able to do it
before user testing.

On Tue, Feb 17, 2015 at 12:14 PM, Justin Walgran <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> do you have any wisdom to share on
> this issue. I have a hunch it is related to recent style overhauls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/612#issuecomment-74707432>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jfrankl** [comment]
Thanks for the video, by the way. Very helpful.

On Tue, Feb 17, 2015 at 12:28 PM, Jeff Frankl <jfrankl@azavea.com> wrote:

> Odd. That doesn't happen on iOS7, but I do get it on iOS8 on the Progress
> Map. It doesn't happen on any of the other maps from what I can tell.
>
> Unfortunately, no additional insight for right now. That's definitely a
> significant bug that I'd be glad to fix, but I won't be able to do it
> before user testing.
>
> On Tue, Feb 17, 2015 at 12:14 PM, Justin Walgran <notifications@github.com
> > wrote:
>
>> @jfrankl <https://github.com/jfrankl> do you have any wisdom to share on
>> this issue. I have a hunch it is related to recent style overhauls.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/azavea/nyc-trees/issues/612#issuecomment-74707432>.
>>
>
>
>
> --
> Jeff Frankl, UI/UX Designer
>
> Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
> Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
> <http://twitter.com>
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
Thanks for digging in a little. I didn't check the reservations page as I assumed it would be broken too. Nice sleuthing. That is an excellent clue to what is going on, and I updated the title to be more specific.

Googling around the issue, there are lots of comments about how scrolling to inputs changed in iOS 8, but I did not find one directly related to our situation.

**Comment by maurizi** [comment]
I was not able to replicate this bug (checked on iOS 8.1 on an iPhone 4S)

**Comment by maurizi** [comment]
@jwalgran can you see if you can replicate this?  If not I think we should close this issue.

**Comment by jwalgran** [comment]
I retested this on my personal 4s and with the 4s and 5 simulators on the latest iOS 8. This problem was probably styled away.
