### ISSUE TITLE
Visual indication of tabs

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#613]
We may want some kind of visual indication that these are tabs and also some default message if the current tab is empty.

![image](https://cloud.githubusercontent.com/assets/43062/6234767/6f0c4da8-b6ab-11e4-85ac-4a5b07e02f72.png)

![image](https://cloud.githubusercontent.com/assets/43062/6234823/b691fc9a-b6ab-11e4-8c9d-d107e1126a7e.png)

![image](https://cloud.githubusercontent.com/assets/43062/6234818/afa07bf0-b6ab-11e4-950a-3229267844fb.png)

etc.

**Comment by RickMohr** [comment]
We could show the number...
```
CURRENT (0)   PAST (7)
```

**Comment by jfrankl** [comment]
@kdeloach Yes, it would be great to have default text when there are no
