### ISSUE TITLE
Old events still show on event list

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#622]
There's an event from Feb 12 showing at the top of the events list. Events should be removed from the list after the date of the event has passed.

**Comment by steventlamb** [comment]
@dboyer can you confirm with event lists you'd like to see this behavior implemented for? In particular, the events page has two lists, 'your events this week' and  'browse events' (all events)
![screenshot from 2015-03-02 14 29 49](https://cloud.githubusercontent.com/assets/1699455/6448523/94f1f558-c0e8-11e4-91a8-33d0bc147dea.png)

**Comment by kdeloach** [comment]
@dboyer ^

**Comment by RickMohr** [comment]
I don't think we should show old events in the "all events" list. 

I see "Take a look at upcoming events and find your next connecting project.", and a bunch of events that happened 3 weeks ago.

![image](https://cloud.githubusercontent.com/assets/2162993/6529886/3fa3104a-c3fa-11e4-86ed-e81175df8978.png)

**Comment by dboyer** [comment]
I don't think we need to show past events in either the all events or the your events section.
