### ISSUE TITLE
Add ability to edit event slug

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#629]
If you rename an event, it retains the old slug for URLs, and there doesn't appear to be any way to change it outside of using the Django admin.

**Comment by maurizi** [comment]
Related to https://github.com/azavea/nyc-trees/issues/409

**Comment by maurizi** [comment]
We now rebuild the slug whenever an event title changes.  With that plus the ability to manually change slugs via the admin site, I think we should close this.
