### ISSUE TITLE
Use static_url template tag for footer logo

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#634]
This does not need to be fixed for user testing. I'm seeing the text (but no logo) on mobile in the footer but not when accessing via Firefox on desktop.

**Comment by jwalgran** [comment]
There are two overlapping items here. I changed the title of this issue to describe the logo reference bug that prevents the logo from appearing.

We opted to not show the footer on the desktop version until the styling is improved: https://github.com/azavea/nyc-trees/issues/609
