### ISSUE TITLE
When attempting to log in before activation, show a more instructive message

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#647]
Preferably with a link to resend the confirmation email.

![screen shot 2015-02-19 at 10 03 24 am](https://cloud.githubusercontent.com/assets/17363/6271584/cbb72e3c-b81e-11e4-9a80-8182dff320e8.png)

**Comment by dboyer** [comment]
Let's change it to: Please click the account activation link you received in your email. Click here to resend that account confirmation email.
