### ISSUE TITLE
After selecting an available blockface on the progress map the "Reserve It" link should go to the new reservation page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#648]

**Comment by dboyer** [comment]
Yes, @jfrankl - something to keep in mind for changes on the map and reservations pages.

**Comment by maurizi** [comment]
We removed this link in https://github.com/azavea/nyc-trees/commit/9c72f9ad6afb3cf2ea2930ea937795a96cc5399e#diff-851c09f5667ab6cc37149026a787153a, so I think we can close this issue
