### ISSUE TITLE
Leaflet attribution has a higher z-index than the header

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#651]
![screen shot 2015-02-19 at 10 41 03 am](https://cloud.githubusercontent.com/assets/17363/6272299/e5961cd2-b823-11e4-9b63-7ba789cbb499.png)

**Comment by dboyer** [comment]
I'm not seeing this on staging in chrome.

**Comment by jwalgran** [comment]
I still see it in chrome and safari in the latest staging release

**Comment by dboyer** [comment]
how odd - certainly worth looking into

**Comment by jfrankl** [comment]
Fixed by dc68d0f55e724de7660c6301b2ba9ca91e663d9d
