### ISSUE TITLE
Error message popup displayed over header

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#659]
When creating an event, make an invalid date or time, scroll to bottom, and save.

Error message pop-up is displayed on the header. This field and references is not scrolled into view.

![image](https://cloud.githubusercontent.com/assets/2162993/6307284/964ec094-b908-11e4-8bda-1ef91799068a.png)

**Comment by maurizi** [comment]
Something the treekit app does is focus on the first invalid field when you try and submit the form.

That seems like something worthwhile to replicate here (and possibly sitewide?).
