### ISSUE TITLE
No visual indication that user is a trusted mapper

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#660]
When a user becomes an individual mapper we display "Tree Mapper" next to their name on the profile page. But when a user becomes a trusted mapper for a group, the only way to tell that their status has changed, is that more blockfaces become available on the reservations page.

**Comment by dboyer** [comment]
Let's add a section that includes groups where the individual mapper has privileges. @jfrankl - on the user profile or the dashboard or both?

**Comment by jfrankl** [comment]
I like the idea of adding a block of text below the group's name in the group section (wherever groups are displayed). Here's what that looks like currently:

![image](https://cloud.githubusercontent.com/assets/1809908/6399667/f1d7e090-bdc1-11e4-93e2-0e0f223f2f98.png)

Here's my proposed revision:

![finished](https://cloud.githubusercontent.com/assets/1809908/6399707/477d4e36-bdc2-11e4-9da7-e60625a66731.png)

**Comment by RickMohr** [comment]
Looks good. Consider changing the label to "You can reserve this group's
blocks for mapping."

On Thu, Feb 26, 2015 at 2:18 PM, Jeff Frankl <notifications@github.com>
wrote:

> I like the idea of adding a block of text below the group's name in the
> group section (wherever groups are displayed). Here's what that looks like
> currently:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1809908/6399667/f1d7e090-bdc1-11e4-93e2-0e0f223f2f98.png>
>
> Here's my proposed revision:
>
> [image: finished]
> <https://cloud.githubusercontent.com/assets/1809908/6399707/477d4e36-bdc2-11e4-9da7-e60625a66731.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/660#issuecomment-76247314>.
>



-- 
Rick Mohr, Software Developer

Azavea |  340 N 12th St, Ste 402, Philadelphia, PA
rmohr@azavea.com  | T 215.701.7504  | F 215.925.2663
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>

**Comment by dboyer** [comment]
Have the text say: You can reserve and map blocks in this group's area.
