### ISSUE TITLE
Individual mappers should choose a block to map only from the "Reservations" page

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#664]
After you successfully reserve blocks we show a "Start mapping" button. But before you can start mapping you have to choose a block to map. Currently we do that on the "Reservations" page.

Rather than adding a second way to choose a block to map I suggest we adjust the UI of this page to take you to the "Reservations" page.

![image](https://cloud.githubusercontent.com/assets/2162993/6329887/12e86b38-bb42-11e4-92b5-117e0e97d10b.png)

Likewise, when asked "Map another block?" after completing a block survey, you should be taken back to the "Reservations" page if you mapped the block as an individual mapper (not as part of an event).

**Comment by dboyer** [comment]
This will be part of a planned change of the reservations page based on user testing.

**Comment by jfrankl** [comment]
This will be resolved by issue #965.
