### ISSUE TITLE
Add a "Register Your Group" link to groups page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#666]
Link to a place on Parks website where users can learn about registering their group to participate in the census.

**Comment by jfrankl** [comment]
I imagine this could use a similar pattern to the "New" button on the groups page:

![image](https://cloud.githubusercontent.com/assets/1809908/6509027/7b60490c-c32a-11e4-8d5c-2e11632be807.png)

**Comment by designmatty** [comment]
@dboyer do you know if a page already exists where users can learn about registering their group? Or should we be setting that page up?

**Comment by dboyer** [comment]
@designmatty The button will link to a page on Parks website. We don't need to set anything up.

**Comment by designmatty** [comment]
@dboyer do you have the link so I can implement this?

**Comment by dboyer** [comment]
Waiting on Parks for the link.

**Comment by dboyer** [comment]
This button should link to http://www.nycgovparks.org/trees/treescount/register-your-group
