### ISSUE TITLE
Survey select blockface endpoint needs design

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#670]
This UI should match the TreeKIT app.

![selection_096](https://cloud.githubusercontent.com/assets/43062/6353413/2117a22a-bc17-11e4-9248-4b4bbf3450b9.png)

![image](https://cloud.githubusercontent.com/assets/43062/6353439/37a76610-bc17-11e4-9eb8-00b161862219.png)

**Comment by jfrankl** [comment]
@designmatty is working on this!

**Comment by designmatty** [comment]
This is all done.
