### ISSUE TITLE
Dashboard "This week's events" shows events from last week

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#673]
Screenshot taken on 2/24.

![image](https://cloud.githubusercontent.com/assets/43062/6358802/4bfa7fce-bc3c-11e4-89cb-ceb5859de9cc.png)

Also affects the "Your events this week" section on `/event`.

![image](https://cloud.githubusercontent.com/assets/43062/6358849/9bc74ee2-bc3c-11e4-8f8b-f2b4a53b2b55.png)

**Comment by dboyer** [comment]
I believe this is connected to #622
