### ISSUE TITLE
Show current reservations on "New Reservation" map

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#674]
It would be nice to display your current reservations on the "New Reservations" map in case you want to reserve blocks nearby.

![selection_100](https://cloud.githubusercontent.com/assets/43062/6358975/776dfd10-bc3d-11e4-9764-0498d54f2460.png)

**Comment by dboyer** [comment]
Agreed, @jfrankl is reworking the reservation display process based on feedback from user testing.

**Comment by maurizi** [comment]
This has been done.
