### ISSUE TITLE
Text clipping on event detail page

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#696]
If you view an event with a particularly long name on a lower res screen...
![image](https://cloud.githubusercontent.com/assets/43062/6401429/48c6ac18-bdce-11e4-87e1-c1f6d62b4ac3.png)

**Comment by designmatty** [comment]
Would a change in the layout similar to the attached screen be ok? This will give more room for the text to flow.
![screen shot 2015-03-11 at 11 11 44 am](https://cloud.githubusercontent.com/assets/1928955/6599376/d91a94d0-c7df-11e4-834b-87d4779f5143.png)

**Comment by designmatty** [comment]
I also can create a word-break, however there is very minimal support for hyphenating these word-breaks throughout all major browsers. In Chrome, a long word would break like the following and is obviously an edge case.
![screen shot 2015-03-11 at 11 14 04 am](https://cloud.githubusercontent.com/assets/1928955/6599408/fe69f168-c7df-11e4-8744-cab78d7f9bbb.png)
