### ISSUE TITLE
Styling needed for "no data" messages

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#699]
Not sure if this exists yet, but we need some kind of reusable style for "no data" messages.
![image](https://cloud.githubusercontent.com/assets/43062/6414758/ff9297ce-be67-11e4-949e-2a8e87b454f7.png)

**Comment by designmatty** [comment]
If you use the class `.no-data` you will get a look similar to: 
![screen shot 2015-03-10 at 9 43 14 am](https://cloud.githubusercontent.com/assets/1928955/6576015/3f3653ac-c70a-11e4-9ea7-673c2248234b.png)
