### ISSUE TITLE
Browserify builds not always completing with `gulp watch`

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#712]
This was working really well at some point, except for adding new JS files after starting `watch`.

Now, the common bundle seems to get messed up quite frequently, leading to JS syntax errors.

Some googling seems to indicate that we may have just too much JS for factor-bundle and watchify to handle: https://github.com/substack/watchify/issues/112

**Comment by maurizi** [comment]
This is still occuring

**Comment by kdeloach** [comment]
Confirmed, still occurring for me too.
