### ISSUE TITLE
Use real counts in the dashboard header text

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#714]
It is currently mocked up with static data

![screen shot 2015-03-02 at 4 04 56 pm](https://cloud.githubusercontent.com/assets/17363/6452886/f78bb6b0-c0f5-11e4-9824-71b1f7129f5f.png)

**Comment by maurizi** [comment]
https://github.com/azavea/nyc-trees/commit/a237993ebdf399424e7ea4e51e95780f01bade34 removed this section, so there is no longer anything to fix
