### ISSUE TITLE
Hide the progress counts and "show me the map" link when in soft launch mode

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#715]
During the soft launch these counts will be zero, and the link goes to an inaccessible page.

![screen shot 2015-03-02 at 4 04 56 pm](https://cloud.githubusercontent.com/assets/17363/6452971/a470d752-c0f6-11e4-82d2-09f0b8b2a03a.png)

**Comment by maurizi** [comment]
This progress counts were removed from this in https://github.com/azavea/nyc-trees/commit/a237993ebdf399424e7ea4e51e95780f01bade34, so there's nothing to hide
