### ISSUE TITLE
Hide dashboard content when in soft launch mode

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#716]
A logged in user should see alternate content rather than the dashboard when in soft launch mode.

This is a current screenshot of the dashboard in soft launch mode

![screen shot 2015-03-02 at 4 40 04 pm](https://cloud.githubusercontent.com/assets/17363/6453419/ee4f1dbc-c0fa-11e4-9c35-07ced31ca745.png)

**Comment by kdeloach** [comment]
We are no longer in soft launch mode

**Comment by jwalgran** [comment]
Most likely reopened by accident.
