### ISSUE TITLE
Add class on body when actionbar is open

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#721]
I would like for a class to be added to the body element when data is sent to the ```.actionbar``` element for the first time on a page. For example, when someone loads the Progress Map, this class should not be added to ```body```. When they click on a blockface and data is sent to ```.actionbar```, we should add ```.actionbar-triggered``` to the ```body``` element. We don't need to remove this class.

This will allow me to hide the actionbar until it is useful, at which point the map will slide up to show the actionbar. This will serve a helpful double function of removing unneeded white space and drawing attention to that area when it becomes relevant.

**Comment by maurizi** [comment]
@jfrankl You may be able to do this without any JS by using the `:empty` selector: https://developer.mozilla.org/en-US/docs/Web/CSS/:empty

The only caveat is that we'll need to make sure that no whitespace is inside the actionbar element.

**Comment by jfrankl** [comment]
Interesting idea. However, it needs to be a little more complicated in this case because we also need to restyle the map element when this change happens, not just the empty element. I think we'll still need javascript.

**Comment by jwalgran** [comment]
Confirmed on staging

![screen shot 2015-04-23 at 8 48 11 am](https://cloud.githubusercontent.com/assets/17363/7301132/8c0b4540-e995-11e4-9640-049b0f600970.png)

![screen shot 2015-04-23 at 8 48 19 am](https://cloud.githubusercontent.com/assets/17363/7301134/8e6ebc72-e995-11e4-9dab-20bcf9138509.png)

**Comment by jfrankl** [comment]
Justin, this hasn't been added yet. The screens you show are for desktop, but this is actually more important for the mobile view. The goal is for the actionbar to be hidden by default, meaning that the map would actually touch the bottom of the page. When the actionbar is needed, it would be displayed on the bottom of the page and the bottom of the map would move up to accommodate it.

Currently, here's the progress map on page load:

![image](https://cloud.githubusercontent.com/assets/1809908/7303268/6d8e0d14-e9bd-11e4-969f-5358befe4b91.png)

Here's what I want it to look like:

![image](https://cloud.githubusercontent.com/assets/1809908/7303279/80fa9796-e9bd-11e4-99b6-6aa570db5d0e.png)

To make this work, I need to have a class added on the ```body``` element when someone first interacts with the application in a way that would result in information being displayed on the actionbar.
