### ISSUE TITLE
Remove "Follow" buttons from list of groups

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#736]
Users were confused with the Follow Buttons on the main /group/ page. Remove follow buttons; users can click on the links to see the group page and use the Follow Button there.

![image](https://cloud.githubusercontent.com/assets/1809908/6508496/27f130b8-c327-11e4-9757-3f30dd6e5ef5.png)

**Comment by RickMohr** [comment]
Should we help them discover that following is possible by including a message like "To stay informed about a group's events, go to the group's page and click the 'Follow' button"?

**Comment by maurizi** [comment]
Will this conflict with the training step of asking people to follow groups?

**Comment by jfrankl** [comment]
@dboyer Am I correct that asking people to follow groups will no longer be a required part of the training process? Instead, when they finish training, they will land on a page that links them to the groups page as a next step? But not one that is required?

**Comment by dboyer** [comment]
Parks will be sending us text so let's not worry about adding help text right now. 

@jfrankl - Correct, following groups will not be a required part of training. I'm good with them landing on that groups page, but no action should be required.
