### ISSUE TITLE
Admin Group Territory page is not responsive

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#749]
In https://treescount.azavea.com/census_admin/territory/ the controls for adding and removing territory go away when the screen size gets smaller.

I'm not sure if this page needs to be responsive or not. We should either 1) disable responsive styling on this page or 2) make certain that this page functions properly at small screen sizes.

**Comment by dboyer** [comment]
This functionality does not need to work on small screen sizes.
