### ISSUE TITLE
List of teammates doesn't autocomplete

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#756]
Perhaps this is related to design changes, but when I try to enter a teammate, I see a blue line on the left side indicating there are autocomplete options but I can't see what those options are. This happened on both desktop and phone so it's not related to screensize.

**Comment by dboyer** [comment]
![screenshot_2015-03-06-11-20-15](https://cloud.githubusercontent.com/assets/516764/6528890/1788ae96-c3f3-11e4-9f68-64edcd4a8b3a.png)

**Comment by jwalgran** [comment]
@designmatty @jfrankl there is some vendor CSS I brought in with the autocomplete control that may be clashing
https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/css/select2.css

**Comment by designmatty** [comment]
I'll take a look into this. I was about to style the select2 dropdowns so hopefully I can resolve this issue at the same time.

**Comment by dboyer** [comment]
This is still an issue as of end of day Friday testing.
