### ISSUE TITLE
"Request Individual Mapper Status" button not displayed

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#757]
When trying to make a reservation as user "admin" (on staging) I was invited to

![image](https://cloud.githubusercontent.com/assets/2162993/6528931/6616022a-c3f3-11e4-8fa2-e4e195fa7864.png)
but there was no button on either of those pages.

**Comment by jwalgran** [comment]
This happens when a user is "banned" from individual mapping by setting ``individual_mapper`` to "No." We need to show some alternate "sorry" content in this case, rather than the steps.

**Comment by kdeloach** [comment]
I think we should always show the button if `individual_mapper` is falsy... This is related to (and may be resolved by) https://github.com/azavea/nyc-trees/issues/610.

**Comment by kdeloach** [comment]
To clarify my previous comment, Jeff is working on this page to add styling and to make these instructions less ambiguous.
