### ISSUE TITLE
Unavailable blockface pop-up hidden under header bar

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#759]
This issue likely happens with other pop-ups on other pages too. Both desktop and mobile.

**Comment by dboyer** [comment]
![screenshot_2015-03-06-11-37-40](https://cloud.githubusercontent.com/assets/516764/6529263/62fc26da-c3f5-11e4-873c-793dbf726edf.png)

**Comment by dboyer** [comment]
@jfrankl For you, perhaps?

**Comment by jwalgran** [comment]
Likely related to #744

**Comment by designmatty** [comment]
I will take care of this.

**Comment by jwalgran** [comment]
@designmatty Is there a fix related to this issue that you would like me to take a look at?

**Comment by designmatty** [comment]
Yeah sorry, forgot to specify. I pushed the fix so the modal appears above the navbar when active.

**Comment by jwalgran** [comment]
Popups are now above the header
