### ISSUE TITLE
Disable survey map interactions while filling out tree details

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#766]
When using a large screen size, the survey form is shown over a fullscreen map. It is possible to interact with the map by accident, which could lead to applying a survey to the wrong block, or in the wrong direction. 

![screen shot 2015-03-06 at 11 40 23 am](https://cloud.githubusercontent.com/assets/17363/6531464/dae70092-c3f6-11e4-9f77-af0b8909613a.png)

**Comment by steventlamb** [comment]
Reopening because we may want to disable zooming and panning too.

**Comment by RickMohr** [comment]
Note disabling pan/zoom is easy to do if we want by including `static: true` in the mapModule creation options.

**Comment by maurizi** [comment]
@RickMohr but we can't do that, because the map needs to be interactive until you hit the survey form portion.

**Comment by RickMohr** [comment]
@maurizi good point... we can at least be inspired by the existing disabling code.

**Comment by steventlamb** [comment]
Unassigning myself for now because I worked on the previous iteration and there's nothing imminently planned for the second.
