### ISSUE TITLE
Species dropdown items need styling

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#786]
As the picture in #783 shows, the tree common name and scientific name In the drop-down currently have vanilla developer styling and could benefit from design help. 

Is It possible to compress vertically so two entire choices can be seen on a mobile device with its keyboard present?

**Comment by maurizi** [comment]
This may require changing the generated markup, which is currently wrapping both lines in `<p>` tags: https://github.com/azavea/nyc-trees/blob/fe015699bfcf3c377bfbd4aa0e656f702804f782/src/nyc_trees/js/src/surveyPage.js#L551

**Comment by designmatty** [comment]
If we remove the `<p>` tags then we will run into an issue where the italicized text will not fall onto a second line. Ultimately all that needs to be done is removing the margins on the `<p>` tags within select2 dropdown.

**Comment by RickMohr** [comment]
IMO it needs to be visually clear that the common name and scientific name go together and are separate from the next pair.

**Comment by designmatty** [comment]
I could easily do something like this where each selection is separated by a line.
![screen shot 2015-03-09 at 2 57 09 pm](https://cloud.githubusercontent.com/assets/1928955/6562113/99862628-c66c-11e4-8f95-41b4f6ed7992.png)

**Comment by RickMohr** [comment]
Since vertical space is at a premium (e.g. when a keyboard is displayed) perhaps we should show them on the same line and let the long ones wrap:

American Beach &ndash; *Fagus grandifolia*
American Hophornbeam &ndash; *Ostrya
&nbsp;&nbsp;&nbsp;&nbsp;virginiana*

**Comment by designmatty** [comment]
@RickMohr The only thing I'm concerned about with a single line display would be the options become to difficult to select due to their very small heights. 

I think I've read in the past the optimum height for tappable areas on mobile is about 40px. I might be overanalyzing though, thoughts?

**Comment by RickMohr** [comment]
@designmatty, I hadn't considered that. Let me know if you want help hitting your site from your phone.

**Comment by designmatty** [comment]
@RickMohr I've been having difficulty setting up my android phone to work with remote debugging. I fear it might be an issue with my phone though.

**Comment by designmatty** [comment]
I was able to squeeze 3 choices into the view on iphone5 @RickMohr 
![screen shot 2015-03-10 at 1 43 45 pm](https://cloud.githubusercontent.com/assets/1928955/6581169/9877bf84-c72b-11e4-9d28-c5edf83d0d7f.png)
