### ISSUE TITLE
Treecorder on non-retina iPad does not show selection prompts

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#787]
Screenshot from iOS simulator. Verified on v1 iPad mini.

![screen shot 2015-03-09 at 9 15 38 am](https://cloud.githubusercontent.com/assets/17363/6558998/05964828-c63d-11e4-88db-4a5d20672b1c.png)

**Comment by jwalgran** [comment]
Rotating to landscape orientation shows the content

![screen shot 2015-03-09 at 9 18 05 am](https://cloud.githubusercontent.com/assets/17363/6559022/3a620984-c63d-11e4-8363-775e9297db47.png)

**Comment by designmatty** [comment]
This might require adjusting the media queries. I'll take a look
