### ISSUE TITLE
Add font directory to static files in gulp process

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#830]
#829 adds in the icon font we're using across the site. In order to use these properly, we'll need this fonts directory to be accessible in ```[site]/static/fonts```, which I believe involves updating the gulp process to copy it during the build/watch process.

**Comment by maurizi** [comment]
We should already have this as part of our Gulp build process.  You'll just need to name the directory `font` instead of `fonts`

**Comment by jfrankl** [comment]
Works after running ```./scripts/npm.sh run build```

**Comment by jfrankl** [comment]
Still having troubles with this. Seem to get a 404 not found error when referring to a specific font file but a 403 forbidden when referring to the parent directory. Could you look into this?

![image](https://cloud.githubusercontent.com/assets/1809908/6618869/88529c24-c89c-11e4-879f-202f45224b61.png)

**Comment by jfrankl** [comment]
Take a look at branch feature/jdf/style-fontello to see what I'm working with.

**Comment by jfrankl** [comment]
Turns out that the command needed is ```./scripts/npm.sh run build-debug```
