### ISSUE TITLE
Styling issue on treecorder - 1 pixel gap for 2 button radio group

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#832]
![pixel-off](https://cloud.githubusercontent.com/assets/4432106/6621388/b35012f2-c8ac-11e4-9ba3-f019b22cacac.png)

Not a problem for the 3 or 4 groups

**Comment by RickMohr** [comment]
I also see it a 4 group:
![image](https://cloud.githubusercontent.com/assets/2162993/6623458/8d7f79a2-c8b9-11e4-9c25-565f5f89223e.png)
