### ISSUE TITLE
Treecorder - You can survey any block by putting it's ID in the hash

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#834]
Steps to reproduce:

 1) Find a blockface that is not reserved by the current user, and note it's ID (say 16489)
 2) Go to the survey URL with that ID in the hash: `http://localhost:8000/survey/#16489`

Expected results: The blockface is not selected, and you must pick one of your reserved blockfaces.
Actual results: The blockface is selected.

**Comment by maurizi** [comment]
The backend which returns geojson should check if this blockface is available to the current user.

**Comment by kdeloach** [comment]
Fixing this is a little trickier than it appears to be. I spent a whole day on this and did not arrive at a satisfactory conclusion. I'd like to hold off on this for now so that we can tackle more serious issues.
