### ISSUE TITLE
Event page says "starting soon" when the event is in progress

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#835]
![screen shot 2015-03-12 at 9 04 01 am](https://cloud.githubusercontent.com/assets/17363/6621959/d55da8ac-c896-11e4-94aa-4269e12e611c.png)

**Comment by maurizi** [comment]
@kdeloach This is fixed now right?

**Comment by kdeloach** [comment]
Fixed by caba19546ef63f1de4beaf305cb37429f8c285bb.
