### ISSUE TITLE
Management command to queue expiring reservation reminders

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#850]
Finds reservations that expire in N days for which notifications have not been queued, queues tasks to send them, and updates the record.

**Comment by RickMohr** [comment]
@dboyer, the Parks text says "Create a 7-day reservation for up to 20 block sides at a time..."

Does that mean they've decided reservations should expire in 7 days?

**Comment by dboyer** [comment]
Yes, just got confirmation that reservations are good for seven days.
