### ISSUE TITLE
Text changes in Treecorder

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#873]
1. Under Branch issues, change Lights to Lights/Wires

2. Tree Condition -> Tree Structure

3. I cannot map this block -> I cannot map this block because...

**Comment by dboyer** [comment]
Change Lights/Wires to Lights or wires so that it's consistent with the formatting of the other options. Sorry, I missed that the first time around. 

There's also an issue with Lights/Wires hitting the line dividing the options. See the attached screenshot. I saw this on desktop but not my Android.

![survey](https://cloud.githubusercontent.com/assets/516764/6714691/06b50804-cd70-11e4-8d3a-b2796d704fdd.png)

**Comment by dboyer** [comment]
Wires needs to be lowercase in Lights or wires to match the capitalization in the other options (Wires or rope, Sidewalk or stones)

**Comment by designmatty** [comment]
![screen shot 2015-03-27 at 11 42 53 am](https://cloud.githubusercontent.com/assets/1928955/6871068/6f7b8a54-d476-11e4-831b-9aeffe079a6d.png)
