### ISSUE TITLE
"New Reservation" page shows group territory as "available"

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#874]
1) Assign some blockfaces to a group's territory
2) Go to the "New Reservation" page and zoom into those blocks

Expected color: black
Actual color: blue

If you click on one it correctly says "The blockface you selected is not available for mapping".

**Comment by maurizi** [comment]
@RickMohr Is this still an issue?

**Comment by RickMohr** [comment]
Fixed.
