### ISSUE TITLE
Decrease size of TreeKIT logo

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#876]
In the Treecorder, the logo should be smaller than the Submit button and all on one line.

**Comment by designmatty** [comment]
Something along these lines @dboyer? 
![screen shot 2015-03-16 at 3 58 55 pm](https://cloud.githubusercontent.com/assets/1928955/6675226/6daa8d94-cbf5-11e4-832d-1489f8b00d15.png)

**Comment by dboyer** [comment]
It could even be a little smaller, but yes, that's the general idea.
