### ISSUE TITLE
Make the No Trees button more obvious

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#877]
Several users reported difficulty seeing the No Trees button in the Treecorder. I received the following feedback/suggestions:

1. Needs to be larger
2. Move to the left and place below Treecorder and above Tree 1
3. Place on separate line so doesn't seem like part of the Treecorder header
4. Change text to No Trees on This Block.

**Comment by dboyer** [comment]
@designmatty Let me know if you need more feedback on this.

**Comment by designmatty** [comment]
@dboyer this is currently waiting on a pull request along with moving the cannot block button. If you'd like to see what I did here are two screenshots. Feel free to give me any feedback on this. Thanks. 
![screen shot 2015-03-18 at 3 15 14 pm](https://cloud.githubusercontent.com/assets/1928955/6717296/e03a09f6-cd81-11e4-8d4e-fe829d806682.png)
![screen shot 2015-03-18 at 3 15 29 pm](https://cloud.githubusercontent.com/assets/1928955/6717295/e0391ea6-cd81-11e4-9044-4d2b72c09f5e.png)

**Comment by dboyer** [comment]
Can you change to No Trees On This Block? Otherwise, it looks great.

**Comment by designmatty** [comment]
Yeah, I'll do that right now.
