### ISSUE TITLE
Design printable maps and how to download them

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#880]
The event detail page should allow users to download a printable PDF map showing the event location.
The "My Reservations" page should allow users to download a printable PDF map showing the blockfaces they have reserved.

Design questions:
* What should a user click on the page to get the map?
* Besides the map, what other information should be on the page?

**Comment by dboyer** [comment]
For an event, let's add this info to the page:
- Name of the event
- Group organizing the event
- Date and time of the event

For the maps for an individual mapper, let's add the sentence:
- For more information about your block edge reservations, visit http://treescount.nycgovparks.org/blockedge.
