### ISSUE TITLE
Error when trying to add tree survey

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#883]
Parks and TreeKIT both reported receiving a "something went wrong" error message when they tried to add a survey. While testing, I also found the error on some surveys and not others. I think it may be linked to adding multiple trees.

**Comment by dboyer** [comment]
Parks reported seeing the issue when mapping as part of an event but not when mapping as an individual mapper. I was able to recreate the problem as an individual mapper, however.

**Comment by jwalgran** [comment]
This may be related to #840

**Comment by dboyer** [comment]
I've tested this some more and the only thing I can find that regularly causes the issue is adding a survey with multiple trees. Those fail when I map both as part of an event and as an individual mapper.
