### ISSUE TITLE
Issues with entering species

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#885]
As part of Treecorder testing, users reported two issues when adding a species from a phone.

1. On Galaxy S4 phone:  Species input would not allow text editing once an entry was selected.  After a species was selected, clicking on the species field again brought up the keyboard and immediately dropped it, and typing or deleting the current entry wasn’t possible.

Note from Deb: I could not recreate this problem on an HTC One.

2. On a iphone-5 sized screen the keyboard would cover the selections being offered by the auto-complete dialog.  This made it very difficult to select species, though the auto-complete itself seemed to function well.  One way to remedy this may be for the auto-complete suggestions to be offered above the field instead of below it, where the keyboard is?  Probably would be less of an issue on a tablet than on a phone.

**Comment by dboyer** [comment]
Another update with similar issues on Samsung Galaxy Tablet:

- Blank space shown under the species field. Blank space needs to be tapped twice in order to start inputting text. If tapped too quickly, on the second tap; the text input will automatically quit.
- If user opens the species field too close to the bottom of the screen, the entire menu will be invisible.
- Users will often think that you can scroll outside of the text box to scroll down the drop down menu.  If this happens, it will exit the entire drop down menu.

Possible suggested fixes included allowing the menu to stay open when sliding outside of the drop down menu and allowing the species menu to appear above the blank space when the field is on the lower half of hte screen.

**Comment by kdeloach** [comment]
Consider switching to full-page choice. Design/engineering collaboration.

(Also consider teammate dropdown)

**Comment by maurizi** [comment]
Full screen selection is already implemented for small screen sizes.

**Comment by maurizi** [comment]
I was able to replicate the issue with the dropdown closing immediately after opening, it appears to be a known bug in Select2 on Firefox for Android and the default android browser: https://github.com/select2/select2/issues/2300

This looks like it will be pretty tricky to fix, though I can give it a shot.
