### ISSUE TITLE
User profile: what privacy setting should control visibility of "Tree Mapper"?

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#89]
The user profile shows "Tree Mapper" if the user has "individual tree mapper" status.

I propose to show it if the user makes their "Achievements"  public. 

The other choice would be to show it if the user makes their profile public.

**Comment by kdeloach** [comment]
Can we close this?

**Comment by RickMohr** [comment]
@dboyer, is it OK that when an individual mapper makes their profile public everyone can see the "Tree Mapper" label?

**Comment by dboyer** [comment]
Yes, that's fine.
