### ISSUE TITLE
Create wrapper class for S3BotoStorage to remove query string auth

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#897]
There is a bug in Boto (https://github.com/boto/boto/issues/1477) that prevents disabling query string authentication for S3 URLs if the S3 connection was established with a security token. Disabling query string authentication at the `S3BotoStorage` backend makes URLs 403 because they still include a security token, but no access key. Enabling query string authentication allows things to work, but adds a lot of extra query strings to the URL, and eventually expires.

A proposed workaround to the issue: https://github.com/boto/boto/issues/1477#issuecomment-38759048

**Comment by kshepard** [comment]
I tried out the proposed workaround in CAC and it appears to work: 
https://github.com/azavea/cac-tripplanner/pull/107

**Comment by hectcastro** [comment]
Great to hear. I will add it to NYC and test today.
