### ISSUE TITLE
Add corner points for blockfaces on the printable context map for individual mappers

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#904]
The corner points on the printable map can be the same symbology as the corner points that show in the Treecorder when choosing a starting point. Some blocks are curved and the corner point is meant to help the mapper know where to start mapping.

**Comment by RickMohr** [comment]
@dboyer, do you think we also want corner points on the event map, since it shows the group's block edges which are near the event?

**Comment by dboyer** [comment]
@RickMohr I'm torn on this. While it could be useful, it could also be overwhelming since a group's census zone may be quite large and showing corner points for every block edge near the event could result in a lot of points on the map. I'm inclined to not display them for events but will check with Parks.

**Comment by dboyer** [comment]
Parks confirmed that corner points should only be displayed on the maps for individual reservations.
