### ISSUE TITLE
Create a static version of the site to use in case of failover

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#920]
Setup a static page that signals to users that the site is currently offline in the event of a failure.

Would be pointed to by the work in https://github.com/azavea/nyc-trees/pull/919.

**Comment by hectcastro** [comment]
Hey @jfrankl and @designmatty, any pointers on this? Willing to take a stab with a little direction on what page you'd like to mimic.

**Comment by dboyer** [comment]
@jfrankl This is something we may want to have in place for the soft launch on Wednesday. Any preferences as to the design?

**Comment by jfrankl** [comment]
Let's use the not-logged-in homepage template:

![image](https://cloud.githubusercontent.com/assets/1809908/6906502/4e3392b8-d6fd-11e4-9f0b-af26a39db096.png)

**Comment by jwalgran** [comment]
To clarify @jfrankl 's suggestion, the static site would not have the burger button and login/register links. Just the header and the text message.

**Comment by jfrankl** [comment]
How people feel about adding sad Stumpy the Tree to this page?

![image](https://cloud.githubusercontent.com/assets/1809908/6946584/69216da2-d86f-11e4-9b6a-d43dcc3dcb7e.png)

Illustration by @ctaylo37.

**Comment by RickMohr** [comment]
Cute! I think it would be less pitiful and just as cute without the amputated arm.

**Comment by jfrankl** [comment]
@hectcastro Does this issue still need work?

**Comment by hectcastro** [comment]
Not if you're cool with [this](http://treescount.nycgovparks.org.s3-website-us-east-1.amazonaws.com).

**Comment by jfrankl** [comment]
I think it works. Hopefully nobody ever sees it.
