### ISSUE TITLE
Reservations page map is blank in desktop view (Chrome, Windows)

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#930]
Blank in Chrome/Windows desktop view
Not blank in Chrome/Windows mobile view
Not blank in Firefox/Windows

If you double-click the map, the map appears but you cannot select blockfaces.

![image](https://cloud.githubusercontent.com/assets/2162993/6787263/019669de-d168-11e4-903e-b09beebc750c.png)

**Comment by maurizi** [comment]
@RickMohr Is this still an issue?

**Comment by RickMohr** [comment]
Closed in favor of #1120, which explains the actual problem.
