### ISSUE TITLE
Specify quoting for non-numeric fields when exporting CSVs

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#934]
Text field values need to be wrapped in quotes.  djqscsv supports passing arbitrary args to the CSV writer.

https://docs.python.org/2/library/csv.html#csv.QUOTE_NONNUMERIC

**Comment by steventlamb** [comment]
It's worth noting that these *must* be keyword arguments.

https://github.com/azavea/django-queryset-csv#keyword-arguments
