### ISSUE TITLE
Export events as shapefile instead of as a text file

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#935]

**Comment by dboyer** [comment]
Is there an open question for Parks on this issue? @jwalgran

**Comment by jwalgran** [comment]
Not yet. If Parks could benefit from having event points as a shapefile, we can provide that, but I didn't want to speculatively revise our existing export process unless there is a specific need.

**Comment by dboyer** [comment]
Yes, Parks would like to have the event points as a shapefile as part of the data export.
