### ISSUE TITLE
We don't prevent "Edit" and "RSVP" for events in the past

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#939]
1) On a Group page, click Events > PAST
2) Click on an event
3) Click Edit or RSVP

Expected: Edit and RSVP buttons are disabled or absent
Actual: You can edit or RSVP even though the event is history.

Allowing editing seems bad, tempting admins to re-use an old event, obscuring history. And what if the event has RSVP's?

**Comment by dboyer** [comment]
I agree that edit and RSVP buttons should be disabled. If, for some unexpected reason, the event needs to be edited, a census admin could always take care of that in the django admin.
