### ISSUE TITLE
Set blockface availability correctly after "Does this look right?" 

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#940]
When a survey is successfully submitted we set the blockface as not available.

For "Does this look right?" after finishing a survey, if mapper chooses:
* "No, Restart" we should set the blockface back to available (currently we do nothing)
* "No, Submit For Review" we should do nothing (the blockface has already been set as not available, no need to set it as not available again)

**Comment by steventlamb** [comment]
@RickMohr should this be:
> "No, Submit For Review" we should leave the blockface as not available (currently we set it as available)

?

**Comment by RickMohr** [comment]
@steventlamb, I updated the description to clarify.

**Comment by steventlamb** [comment]
@RickMohr Thanks.

Does this mean that the `complete_survey` view should now no longer try to set the blockface availability to `False`, since it will already always be `False`?

**Comment by RickMohr** [comment]
@steventlamb, yes.
