### ISSUE TITLE
Treecorder: Can't tell which number tree you're looking at

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#942]
From user testing:

The app has a tendency to slide vertically while being used, especially when opening and closing a keyboard.  This can create moments where it’s unclear which number tree you’re looking at.

**Comment by jwalgran** [comment]
The "sticky headers" we used on Wellbeing Toronto may be a solution http://cl.ly/0S0c3F0c3q0s/toronto-sticky-headers.mov

**Comment by kdeloach** [comment]
We'd like input from Design on how to always know which tree you're currently working on (without eating up vertical space on a tiny phone)

**Comment by jfrankl** [comment]
I like the idea of affixing the tree header in the way Justin demonstrated in that video.

@designmatty aka **master of the treecorder**, what do you think?

**Comment by RickMohr** [comment]
@jfrankl, what about the issue of eating up more precious vertical space on a small phone?

**Comment by designmatty** [comment]
@jwalgran integrating the sticky headers will be a good idea. I think a slightly different approach to the styling of the sticky headers will be a good solution:
![screen shot 2015-04-24 at 4 35 43 pm](https://cloud.githubusercontent.com/assets/1928955/7328075/7958ea72-eaa0-11e4-9981-80968de1b05a.png)

**Comment by jfrankl** [comment]
Matt, I like how that sort of design keeps the sticky idea but also doesn't
take up as much screen real estate. Very elegant.

On Fri, Apr 24, 2015 at 4:41 PM, Matt Williams <notifications@github.com>
wrote:

> @jwalgran <https://github.com/jwalgran> integrating the sticky headers
> will be a good idea. I think a slightly different approach to the styling
> of the sticky headers will be a good solution:
> [image: screen shot 2015-04-24 at 4 35 43 pm]
> <https://cloud.githubusercontent.com/assets/1928955/7328075/7958ea72-eaa0-11e4-9981-80968de1b05a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/942#issuecomment-96059124>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by designmatty** [comment]
I took a look at trying to handle this but it may be a bit beyond my know-how right now. @jwalgran could you or another developer could help implement this?

**Comment by jwalgran** [comment]
I am tied up at the moment. If you want to work on this now you will need to tap another team member.

**Comment by designmatty** [comment]
I'll ask around. Thanks
