### ISSUE TITLE
Change circumference label

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#943]
We're asking people to input circumference for trees (alive or dead) and diameter for stumps. By default, the area under Tree Trunk shows as Circumference. It doesn't change to Diameter unless Stump is selected.

There's some concern that people will see the circumference prompt and start measuring a stump's circumference before they select "stump" under Tree Structure and realize it should be diameter.

Change that section to just show a header labeled "Tree Trunk/Stump Size" and don't display the circumference or diameter prompt and entry form until after someone has selected the tree structure.

@designmatty Unassign yourself please if this is not a designer issue.

**Comment by dboyer** [comment]
If we need to display the field and not just the section header (since that's what we do for every other question), can we change it to Circumference/Diameter and then adjust based on what the user selected for tree structure?

**Comment by designmatty** [comment]
I believe a developer will have to handle this.

**Comment by jwalgran** [comment]
How about disabling the field and hiding details until the person chooses a structure

![screen shot 2015-05-01 at 2 14 22 pm](https://cloud.githubusercontent.com/assets/17363/7437467/6a14d26c-f00c-11e4-93da-d77d308a28b6.png)

**Comment by dboyer** [comment]
Call that field "Size" rather than Structure Size and it's fine to disable it and hide details (the header and field prompt) until the user has selected a tree structure.

**Comment by jwalgran** [comment]
Here is how it would look dropping the word "structure" from the field label

![size-field](https://cloud.githubusercontent.com/assets/17363/7455382/a4a45f62-f230-11e4-8ffc-1060fdb8b3b9.png)

**Comment by dboyer** [comment]
That seems fine as long as we can change the field header once the user selects either a tree or stump.
