### ISSUE TITLE
phantomjs on staging fails with "SSL handshake failed"

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#955]
On staging, phantomjs can't render `https://treescount.azavea.com/`:
`phantomjs --debug=true js/backend/url2pdf.js ssss https treescount.azavea.com / 1.0`

Fails with:
`Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://treescount.azavea.com/blockface/printable-map/"`

`curl https://treescount.azavea.com` succeeds.

phantomjs can render `https://google.com/`:
`phantomjs --debug=true js/backend/url2pdf.js ssss https google.com / 1.0` succeeds

**Comment by RickMohr** [comment]
@hectcastro, any thoughts?

**Comment by RickMohr** [comment]
OK, looks like passing `--ssl-protocol=tlsv1` fixes this

**Comment by hectcastro** [comment]
Yep, that was going to be my recommendation. We are on the latest security policy (`ELBSecurityPolicy-2015-03`), which prohibits SSLv3 (which apparently `phantomjs` defaults to):

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-policy-table.html
