### ISSUE TITLE
Replace lipsum on progress map and anywhere else it appears

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#957]
![screen shot 2015-03-26 at 10 13 36 am](https://cloud.githubusercontent.com/assets/17363/6852268/cfc8824e-d3a0-11e4-929b-1cde2afa3746.png)

**Comment by maurizi** [comment]
![request-mapper-status](https://cloud.githubusercontent.com/assets/4432106/6905370/6f669b36-d6f5-11e4-947b-5809df89b3af.png)

This shows up on the group detail page if the group allows individual mappers

**Comment by maurizi** [comment]
![training-getting-started2](https://cloud.githubusercontent.com/assets/4432106/6905378/846737fc-d6f5-11e4-8b29-0ad65e1cfe14.png)
![training-getting-started1](https://cloud.githubusercontent.com/assets/4432106/6905377/8466cb6e-d6f5-11e4-8fef-a4ef017fd762.png)
![training](https://cloud.githubusercontent.com/assets/4432106/6905379/846f133c-d6f5-11e4-97da-bd0bb06d216e.png)

Various training pages

**Comment by jwalgran** [comment]
Adding the real training page content falls under https://github.com/azavea/nyc-trees/issues/959

**Comment by maurizi** [comment]
@jwalgran Oops. I'll delete that comment.

**Comment by maurizi** [comment]
![email-attendees](https://cloud.githubusercontent.com/assets/4432106/6905598/17ce313e-d6f7-11e4-84ca-94837e45caeb.png)
Shown when a group admin attempts to email event attendees, but no one has RSVPed to the event yet

**Comment by dboyer** [comment]
Progress Map Text

<b>The legend on the default view at /blockedge/progress/:</b>
Welcome to the TreesCount! 2015 progress map!

This map shows where your fellow tree-loving citizens have already mapped street trees in NYC. Explore the map to view overall progress, your progress, and the progress of TreesCount! Partner groups!

<b>Legend at /blockedge/progress/#all:</b>
This map shows the block edges mapped so far by all volun<b>treer</b>s for TreesCount! 2015.  Sign up for an event to help us finish mapping our street trees!  

<b>Legend at /blockedge/progress/#my:</b>
This map shows the block edges that have been mapped by you! 
   
Sign up for an event or make a block edge reservation to keep on mapping!  

<b>Legend at /blockedge/progress/#groups:</b>
This map shows you our TreesCount! Partner groups’ Census Zones and their mapping progress.  Click on a Census Zone for more details!

**Comment by dboyer** [comment]
Text for Individual Mapping Section on Group Page:

Volun<b>treers</b> are able to map trees on their own, outside of scheduled events!  Click the button below to request individual mapping status within this group’s Census Zone.  Remember to contact your local loaning hub to check out individual tools and start mapping on your own.

**Comment by dboyer** [comment]
Text for Emails from Group Admins to RSVPs

<b>When there are no RSVPs yet:</b>
There are no volun<b>treers</b> RSVPed for your event.  Please try again when there is at least 1 volun<b>treer</b> RSVPed.

<b>When there are RSVPs:</b>
This form will allow you to contact your event registrants, either before the event or up to 7 days after the event.  <i>Note that only event attendees who have opted into emails will receive these updates!!  Do not use this to update your event details – edit the event details directly instead.</i>
