### ISSUE TITLE
Determine if we want resources files for cloud.typography.com assets

### ISSUE THREAD

**Issue by hectcastro** [azavea/nyc-trees#960]
@jfrankl mentioned that we could be given files for the Treescount fonts from typography.com. As things stand right now, the production URL works with the cloud.typography.com assets.

**Comment by jfrankl** [comment]
It's my understanding that we need the assets for it to work once we start
serving more users. The "development mode" is only intended for testing and
I think we'll go over our limit when the site launches.

On Thu, Mar 26, 2015 at 2:38 PM, Hector Castro <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> mentioned that we could be given
> files for the Treescount fonts from typography.com. As things stand right
> now, the production URL works with the cloud.typography.com assets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/960>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
@jfrankl Do you know how we get files? I assume NYC has to get them for us.

**Comment by jwalgran** [comment]
@jfrankl Do you know how we get files? I assume NYC has to get them for us.

**Comment by jwalgran** [comment]
@jfrankl Do you know how we get files? I assume NYC has to get them for us.

**Comment by jwalgran** [comment]
@jfrankl We have requested details from parks, but have not yet heard back.

**Comment by jfrankl** [comment]
It might be easier if they give us account information so we can do it. Up
to them.

On Fri, Mar 27, 2015 at 6:31 PM, Justin Walgran <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> We have requested details from
> parks, but have not yet heard back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/960#issuecomment-87108353>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by jwalgran** [comment]
We are now bundling the font with the application

Fixed by #1046
