### ISSUE TITLE
Selectable progress view

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#968]
Add dropdown to the header to select a a version of the progress layer
- Classic
- User filtered
- Group polygons

**Comment by RickMohr** [comment]
@jfrankl, the new Progress Map is simpler in some respects than the current one (for the "All Users" and "My Progress" options). Clarifying:

Currently we show 5 legend entries. We will change to just 2 (mapped and not mapped).

Currently you can click/tap to select a block edge, and see its status (e.g. "Blockface reserved by Experts"). If it's available you get a "Reserve it" link (not implemented). We will change to make block edges not selectable.
