### ISSUE TITLE
Link dashboard progress circles to pages and modals

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#972]
2015_03_26_nyc_wireframes_v4 p35-17

1. Blocks and % complete to Progress Mapp

2. Species to a modal that displays: 124 White Oak
32 Pin Oak
0 Callery Pear

3. Users to a modal with user related data: "[x] users have attended [y] events and joined [z] groups".

4. Events to Events Page

**Comment by kdeloach** [comment]
Is this for the logged out home page only? Or should the user contributions circles also be clickable?

**Comment by jfrankl** [comment]
Let's make it for all pages.

Does this issue include being able to tab through the three different types of progress (All time, past week, my trees)? Or should I create a different issue for that?

![image](https://cloud.githubusercontent.com/assets/1809908/6986164/a979659a-da08-11e4-939e-15e1ac7008b1.png)

**Comment by kdeloach** [comment]
No need to create another issue.
