### ISSUE TITLE
Show filterable status counts on logged in home page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#973]
2015_03_26_nyc_wireframes_v4 p31-34

**Comment by RickMohr** [comment]
@jfrankl, in the "Progress" section of the logged in home page one of the choices is "THIS WEEK". I'm guessing we want this to mean "in the last 7 days" rather than "since Monday", and I propose changing the label to "PAST WEEK" to clarify.

**Comment by jfrankl** [comment]
+1 "PAST WEEK"

Good call.

**Comment by RickMohr** [comment]
@jfrankl, do you want the progress circles to be all the same color as shown in the wireframes, or different colors as they are currently?
If the same color, should we also unify the progress circle colors on the homepage?

**Comment by jfrankl** [comment]
Great question. Let's do different colors for each. That means we'll need
different colors for:

   - Blocks
   - % Complete
   - Users
   - Events
   - Species

I'll figure out two more colors, but can I do that later in a way that
won't block you?

What do you think is the best way to handle this? Add a class on each?
Inject the color inline?

On Wed, Apr 1, 2015 at 3:51 PM, Rick Mohr <notifications@github.com> wrote:

> @jfrankl <https://github.com/jfrankl>, do you want the progress circles
> to be all the same color as shown in the wireframes, or different colors as
> they are currently?
> If the same color, should we also unify the progress circle colors on the
> homepage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/973#issuecomment-88611557>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by RickMohr** [comment]
Since this is a local color scheme (not something like "every time I see blue it's about events") seems to me we could keep it simple and just use primary/secondary/quaternary left-to-right for whatever three circles we're showing.

But it will be easy to change colors by defining a class if you want.

**Comment by RickMohr** [comment]
@jfrankl, the user's "progress circles" are currently shown on their profile page as well as on their logged-in home page. I propose removing the progress circles from the profile, since they will always see them on login and will seldom visit their profile.

We could also show the entire new "Progress" section on the profile page if you want. Or we could show just the existing progress circles on the profile, but that would take extra work.

**Comment by jfrankl** [comment]
The profile is meant to be a representation of a user that other users see.
I think having progress circles that are related to the user would be
useful for that purpose. So, how many trees/blocks a person mapped, species
mapped, events attended. Basically, what is currently listed under My
Trees. Does that work?

[image: Inline image 1]

On Thu, Apr 2, 2015 at 10:12 AM, Rick Mohr <notifications@github.com> wrote:

> @jfrankl <https://github.com/jfrankl>, the user's "progress circles" are
> currently shown on their profile page as well as on their logged-in home
> page. I propose removing the progress circles from the profile, since they
> will always see them on login and will seldom visit their profile.
>
> We could also show the entire new "Progress" section on the profile page
> if you want. Or we could show just the existing progress circles on the
> profile, but that would take extra work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/973#issuecomment-88920306>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by RickMohr** [comment]
OK. Currently they use the same code as the dashboard. I'll break it up.
