### ISSUE TITLE
Show filterable events on logged in home page

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#974]
“I’m Attending” (RSVPed) and “Recommended” (events for groups followed by the user) filters.

Show text if the filtered list is empty:

“I’m attending” -> You are not yet registered to attend any events. [[ link to the events page ]]

“Recommended” -> You are not yet following any groups [[ link to groups page ]]
or
The groups you are following do not have any events scheduled.

**Comment by steventlamb** [comment]
Right now the scope of the list is limited to immediate events (coming soon). Do we want to additionally expand that criteria since we're adding filters?

**Comment by steventlamb** [comment]
> “Recommended” -> You are not yet following any groups [[ link to groups page ]]

But what if the user **is** following groups, but those groups don't have any events?

**Comment by jwalgran** [comment]
RE: filter scope, good question. It would be a good idea ask @jfrankl for his input. If you follow a few big groups that have their calendar planned out through the summer, there could be 50+ events in the "recommended" list, so I don't think we want to list all of them on the dashboard.

**Comment by jwalgran** [comment]
Good catch on the "Recommended" placeholder text. We do have to handle both "empty" cases separately.

**Comment by jwalgran** [comment]
I amended the issue description to reflect the fact that there are 2 different empty list cases for Recommended

**Comment by jfrankl** [comment]
Can we show the top 10 results along with a "see more" link that pulls in the rest or a link to the events page?

**Comment by steventlamb** [comment]
@jfrankl sure, we can do that. That's slightly different from the question of what the underlying, outermost query should be. To clarify, in your idea, if you don't click either filter, but you do click 'see more', you should see every single event in the database? If so, we should scope to all events.

We can also  scope to all events but not include the `ALL` filter, so that the the most you could ever see is all events that are captured by one of the two filters.

**Comment by jfrankl** [comment]
I think we should not include an ALL filter. We can include a link to the events page if people want to see everything. I think this meets the goal of the dashboard, which is to be an entryway into actions.
