### ISSUE TITLE
Can't complete registration on a freshly provisioned dev VM due to missing file email backend directory

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#99]
![screen shot 2014-11-20 at 1 05 27 pm](https://cloud.githubusercontent.com/assets/17363/5130125/073250be-70b6-11e4-8446-1bfcbbc55440.png)

**Comment by designmatty** [comment]
@RickMohr did you mean to assign this to me?

**Comment by RickMohr** [comment]
@designmatty, I didn't assign that to you (I was walking around a Florida lake at the time). Mysterious.

**Comment by designmatty** [comment]
huh strange @RickMohr. I guess it will remain a mystery.
